export const MASTER_DOCUMENTS: Record<string, string> = {
  prd: `# Product Requirements Document (PRD)

## Enterprise Architecture Platform — OIL ONLY Governed Agentic AI System

**Document ID:** PRD-OIL-2026-001  
**Document status:** Approved — GxP & Enterprise Architecture Review Board (ARB) Baseline  
**PRD version:** v1.0 (Master Unified Architecture Baseline)  
**Product owner:** Dr. Elena Vance (VP, Cognitive Platforms & Digital Product)  
**Business owner:** Dr. Marcus Vance (Executive VP, Global Medical & Commercial Operations)  
**Technical owner:** Nitin Aggarwal (Principal AI Systems Architect)  
**Compliance owner:** Sarah Chen, JD (Senior VP, Global Regulatory & Quality Compliance)  
**Date created:** August 1, 2026  
**Last updated:** August 2, 2026  
**Target release:** Release 1 Production Pilot (Q3 2026)  
**Confidentiality:** Confidential — Enterprise Internal & GxP Validation Repository  
**Applicable markets:** United States (FDA 21 CFR Part 11 / GxP), EU (EMA / GDPR), Global Therapeutic Areas  
**Applicable business functions:** Medical Affairs, Commercial MLR, Clinical Operations, Regulatory Affairs, Pharmacovigilance Safety Intake  

---

# 1. Executive Summary

## 1.1 Product Overview
**Enterprise Architecture Platform — OIL ONLY** is a governed, end-to-end Agentic AI platform engineered for highly regulated pharmaceutical enterprises. The platform combines access-aware enterprise retrieval (Hybrid RAG), specialized domain AI agents, a zero-trust VPC Service Controls (VPC-SC) security perimeter, and mandatory Human-in-the-Loop (HITL) review gates to automate high-complexity, multi-step workflows while preserving 100% inspection readiness.

---

# 2. Target Users & Enterprise Personas

| Persona ID | Target User Persona | Enterprise Role & Primary Responsibilities | Core System Interaction Mode |
| :--- | :--- | :--- | :--- |
| **PERS-01** | **Medical Information Specialist** | Formulates evidence-grounded responses to complex Medical Information Requests (MIR). | Initiates MIR agent workflow; reviews evidence citations; signs off on final output. |
| **PERS-02** | **Commercial MLR Reviewer** | Conducts Medical, Legal, and Regulatory review of promotional materials and sales assets. | Reviews AI claims-check analysis; validates mandatory fair balance language; approves releases. |
| **PERS-03** | **Pharmacovigilance (PV) Safety Officer** | Screens incoming communications for Adverse Events (AEs) and Product Quality Complaints (PQCs). | Receives automated safety triage escalations; verifies Argus safety case intake packages. |
| **PERS-04** | **Regulatory Affairs Specialist** | Prepares country-specific labeling briefs, IND updates, and global dossier responses. | Executes multi-agent scientific synthesis against approved Core Data Sheets (CDS). |

---

# 3. High-Level Functional Capabilities & System Epics

### 📐 Visual Diagram 1: High-Level End-to-End Functional Architecture Flow
\`\`\`mermaid
graph TD
    USER["👤 Accountable Human User (Medical / Regulatory / PV)"] --> INGRESS["🛡️ Cloud Armor WAF + Google API Gateway (VPC-SC Perimeter)"]
    INGRESS --> ORCH["⚙️ Agent Orchestrator & ReAct Reasoning Engine (GKE Pod)"]
    
    ORCH <--> PLANNER["📋 Planner Agent (Task Graph Decomposition)"]
    ORCH <--> RETRIEVAL["🔍 Hybrid RAG Engine (GCS Data Lake + Vertex Vector Search)"]
    ORCH <--> SAFETY["🛡️ Pharmacovigilance AE Real-Time Screener"]
    
    RETRIEVAL --> CITATION["📌 Claim-Level Evidence Citation & Fair Balance Audit"]
    CITATION --> HITL["👤 Mandatory Human-in-the-Loop (HITL) Governance Board Gate"]
    
    HITL --> TOOL["🔌 Governed Tool Gateway (Idempotency Key & Action Preview)"]
    TOOL --> SYSTEMS["☁️ Systems of Record (Veeva Vault / Salesforce CRM / Argus Safety)"]
    
    ALL["All System Events"] --> AUDIT["🗄️ Immutable Audit Service (SHA-256 Chain + OpenTelemetry)"]
\`\`\`

---

# 4. Functional System Requirements

### 4.1 Enterprise Knowledge & Access-Aware Hybrid RAG
* **REQ-RAG-001:** The system MUST enforce access-aware document retrieval where users and agents only retrieve content matching the user's explicit Entitlement Groups and Attribute-Based Access Control (ABAC) claims.
* **REQ-RAG-002:** Every material factual statement generated by an agent MUST include a clickable citation resolving to an approved, version-controlled source document (Core Data Sheet, Approved PI, or Final CSR).
* **REQ-RAG-003:** The platform MUST score document relevance using a hybrid dense-sparse vector scoring formula combining semantic cosine similarity with BM25 keyword matching.

### 4.2 ReAct Agent Cognitive Reasoning Engine
* **REQ-AGENT-001:** Specialized domain agents MUST execute within a deterministic ReAct (\`Thought\` ➔ \`Action\` ➔ \`Observation\` ➔ \`Synthesis\`) cognitive reasoning loop with strict loop budgets (\`max_iterations = 6\`).
* **REQ-AGENT-002:** All agent model invocations MUST pass through a centralized Model Gateway that enforces token quotas, processing region compliance, and cost-aware fallback routing.

### 4.3 Human-in-the-Loop Governance & Segregation of Duties
* **REQ-HITL-001:** Any workflow affecting external communications, patient safety assessments, or regulatory commitments MUST halt at a mandatory HITL Governance Board Gate.
* **REQ-HITL-002:** High-risk write actions dispatched to external enterprise systems MUST display an explicit **Action Preview** payload and require electronic signature sign-off compliant with FDA 21 CFR Part 11.

---

# 5. Non-Functional, Security & Governance Requirements

| Category | Requirement ID | Executive Requirement Specification | Verification Target |
| :--- | :--- | :--- | :--- |
| **Security** | **NFR-SEC-001** | Zero-trust Google Cloud VPC Service Controls (VPC-SC) perimeter isolating compute and storage. | Zero unauthorized ingress/egress. |
| **Privacy** | **NFR-PRIV-001** | Automated PII/PHI detection and token masking prior to LLM context assembly. | 100% compliance with HIPAA/GDPR. |
| **Reliability** | **NFR-REL-001** | Multi-zone GKE deployment with persistent state recovery and idempotent tool transactions. | 99.95% System Availability. |
| **Audit** | **NFR-AUD-001** | Complete cryptographic SHA-256 immutable event trail of user requests, LLM prompts, tool calls, and human approvals. | Inspection-ready audit export. |

---

# 6. Approved Document Sign-Off

| Reviewer Role | Executive Sign-Off Name | Approval Status | Timestamp |
| :--- | :--- | :---: | :--- |
| **Product Owner** | Dr. Elena Vance | **APPROVED** | August 2, 2026 |
| **Business Sponsor** | Dr. Marcus Vance | **APPROVED** | August 2, 2026 |
| **Technical Owner** | Nitin Aggarwal | **APPROVED** | August 2, 2026 |
| **Quality & Regulatory Lead** | Sarah Chen, JD | **APPROVED** | August 2, 2026 |
`,

  sdd: `# System Design Document (SDD)

## Enterprise Architecture Platform — OIL ONLY Agentic AI Cognition & Governance Hub

**Document ID:** SDD-OIL-2026-001  
**Document version:** v1.0 (Technical & Infrastructure Architecture Review Ready)  
**Document status:** Approved — Engineering, DevSecOps & Regulatory Sign-Off  
**Related PRD:** PRD-OIL-2026-001 (Enterprise Architecture Platform — OIL ONLY PRD v1.0)  
**Related FDD:** FDD-OIL-2026-001 (Enterprise Architecture Platform — OIL ONLY FDD v1.0)  
**Related architecture document:** SAD-OIL-2026-001 (Google Cloud Technical Architecture Specification v1.0)  
**Business function:** Medical Affairs, Commercial MLR, Clinical Operations, Regulatory Affairs, Pharmacovigilance  
**System owner:** Dr. Elena Vance (VP, Cognitive Platforms & Digital Product)  
**Solution architect:** Nitin Aggarwal (Principal AI Systems Architect)  
**Technical lead:** David K. Thorne (Principal Cloud Infrastructure & DevSecOps Lead)  
**Security architect:** Robert Sterling, CISSP (Enterprise Security & VPC-SC Lead)  
**Data architect:** Ananya Ramanathan (Principal Data & Feature Engineering Lead)  
**AI or ML lead:** Dr. Srijan Das, PhD (Head of Agentic LLM Evaluation & Safety)  
**Quality or validation lead:** Dr. Aris Thorne, MD (Global Computer System Validation Lead)  
**Operations owner:** Marcus Sterling (Global Head of Technical Support & Reliability)  
**Date created:** August 1, 2026  
**Last updated:** August 2, 2026  
**Target release:** Release 1 Controlled Production Pilot (Q3 2026)  
**Confidentiality:** Confidential — Internal Enterprise & Regulatory Review Only  

---

# 1. Document Purpose

This System Design Document (SDD) defines the technical and infrastructure architecture of **Enterprise Architecture Platform — OIL ONLY**, an enterprise governed Pharma Agentic AI cognitive platform.

The document translates the approved Product Requirements Document (PRD-OIL-2026-001) and Functional Design Document (FDD-OIL-2026-001) into an engineering-ready system design covering:
* Logical and physical multi-tier deployment topology across Google Cloud Platform (GCP).
* Container compute, serverless API gateways, and GKE Agent Orchestrator pods.
* Agent cognitive runtime, state machines, and context assembly boundaries.
* Model Gateway routing, token budgeting, and Canary deployment pipelines.
* Hybrid Retrieval-Augmented Generation (RAG) and dbt Managed Feature Store data architecture.
* VPC Service Controls (VPC-SC), Cloud Armor WAF, and mTLS network security architecture.
* Tool Gateway execution, idempotency verification, Action Previews, and rollback mechanisms.
* Observability, OpenTelemetry distributed tracing, and immutable 21 CFR Part 11 audit trails.
* High availability, disaster recovery (RTO/RPO), performance scaling, and GxP computer system validation controls.

---

# 2. Architecture Overview & Cloud Topology

## 9.1 Multi-Tier Cloud Deployment Topology

The platform deploys across dedicated GCP multi-zone regions wrapped by **VPC Service Controls (VPC-SC)**.

### 📐 Visual Diagram 1: Multi-Tier Cloud Physical Deployment & Container Compute Topology
\`\`\`mermaid
graph TD
    subgraph ZONE_PUBLIC["🌐 Public Ingress & Edge Protection Zone"]
        CLIENT["💻 Web Workspace Client / Mobile / Portal"]
        WAF["🛡️ External HTTPS Load Balancer + Cloud Armor WAF"]
        GW["🔐 Google API Gateway (OAuth2 / OIDC & Rate Limiting)"]
        CLIENT -->|"HTTPS / TLS 1.3"| WAF
        WAF -->|"WAF Filtered Egress"| GW
    end

    subgraph ZONE_VPCSC["🔒 Protected VPC Service Control (VPC-SC) Perimeter"]
        subgraph TIER_COMPUTE["⚡ Compute & Cognitive Reasoning Tier (Private Subnet)"]
            GW -->|"Internal mTLS"| GKE["⚙️ Agent Orchestrator Pods (GKE Cluster)"]
            GKE <--> PROMPT["📜 Integrated System Prompt Registry"]
            GKE <--> MEMORY["🧠 Conversation & Workflow Memory Manager"]
            GKE <--> GEMINI["🤖 Gemini LLM Reasoner Engine (ReAct Loop)"]
        end

        subgraph TIER_DATA["🛢️ Enterprise Data & Feature Engineering Tier"]
            GKE -->|"IAM Scoped Access"| GCS["🪣 GCS Secure Bucket (Raw Data Lake)"]
            GKE -->|"Analytical Query"| BQ["📊 BigQuery Data Warehouse"]
            GCS -->|"Circular Transformation"| DBT["❌🛢️ dbt Transformation Pipeline"]
            DBT --> STORE["🗃️ Managed Feature Store"]
            STORE --> GKE
        end

        subgraph TIER_GOVERNANCE["🛡️ AI Lifecycle, Evaluation & Governance Tier"]
            GKE --> VETTING["🔍 DATA VETTING Gateway"]
            VETTING --> HIL["🛡️👤 Unified Governance Board (HITL Gate)"]
            HIL -->|"APPROVED"| CANARY["🐤 Canary Deployment Stage (5% Traffic)"]
            CANARY --> PROMOTE["🚀 Production Promotion (100% Traffic)"]
            GKE --> DRIFT["📈 Continuous Observability & Drift Monitoring"]
            DRIFT --> ARCHIVE["🗄️ Model & Prompt Archival Registry"]
        end
    end
\`\`\`

---

# 3. Network Architecture & Security Perimeter

## 10.1 Zero-Trust Network & Perimeter Security Map

### 📐 Visual Diagram 2: Zero-Trust Network Architecture, Ingress/Egress & VPC-SC Security Map
\`\`\`mermaid
graph LR
    subgraph EXTERNAL["🌐 External Internet"]
        USER["👤 Medical Info Specialist"]
    end

    subgraph EDGE["🛡️ Google Cloud Edge Ingress"]
        LB["External HTTPS Load Balancer"]
        WAF["Cloud Armor WAF (DDoS / SQLi / OWASP Top 10)"]
        APIGW["Google API Gateway"]
        USER -->|"TLS 1.3"| LB
        LB --> WAF
        WAF --> APIGW
    end

    subgraph PERIMETER["🔒 Cryptographic VPC Service Control (VPC-SC) Perimeter"]
        direction TB
        GKE_POD["⚙️ GKE Private Application Subnet"]
        KMS["🗝️ Google Cloud KMS (Customer-Managed Keys)"]
        GCS_DATA["🪣 GCS Raw Data Lake (Encrypted CMEK)"]
        BQ_DATA["📊 BigQuery Data Warehouse (Encrypted CMEK)"]

        APIGW -->|"Private Service Connect (PSC)"| GKE_POD
        GKE_POD <-->|"mTLS Istio Service Mesh"| KMS
        GKE_POD -->|"VPC Egress Restricted"| GCS_DATA
        GKE_POD -->|"VPC Egress Restricted"| BQ_DATA
    end
\`\`\`

---

# 4. Agent Orchestration & Runtime Design

## 14.2 ReAct Cognitive Runtime & Context Assembly Architecture

### 📐 Visual Diagram 3: ReAct Agent Cognitive Runtime & Context Assembly Technical Architecture
\`\`\`mermaid
graph TD
    TASK["🎯 User Objective / Sub-Task Trigger"] --> BUILDER["🛠️ Context Assembly Builder"]
    
    subgraph CONTEXT_BUDGET["📦 Bounded Context Window Budget (Max 128k Tokens)"]
        BUILDER --> P1["📜 System Prompt & Role Instructions"]
        BUILDER --> P2["🔍 Retrieved Passage Citations & Metadata"]
        BUILDER --> P3["📋 Prior Step Observation Outputs"]
        BUILDER --> P4["🔌 Available Tool Schemas & Safety Rules"]
    end

    BUILDER --> VALIDATOR["🛡️ Schema & Prompt-Injection Validator"]
    VALIDATOR --> GW["🚪 Model Gateway"]
    GW --> LLM["🤖 Gemini LLM Reasoner Engine"]
    LLM --> OUTPUT["📄 Raw Agent Output JSON"]
    
    OUTPUT --> COMPLIANCE{"Policy Engine Interceptor"}
    COMPLIANCE -->|"Policy Passed"| NEXT["⚡ Execute Next ReAct Step / Action"]
    COMPLIANCE -->|"Policy Blocked"| ESCALATE["🛡️ Stop & Escalate to Unified Governance Board"]
\`\`\`

---

# 5. Model Gateway & AI Lifecycle Design

## 16.3 Model Routing, Token Budgeting & Canary Deployment Lifecycle

### 📐 Visual Diagram 4: Model Gateway Routing, Token Budgeting & Canary Deployment Lifecycle
\`\`\`mermaid
graph TD
    REQ["📥 Incoming Agent Task Request"] --> ROUTER["🔀 Model Routing Engine"]
    
    subgraph ROUTING_RULES["Deterministic Model Selection Rules"]
        ROUTER -->|"Classification / Fast Triage"| M_FLASH["⚡ Gemini 3.6 Flash (Low Latency / Cost)"]
        ROUTER -->|"Scientific Synthesis & CSR Analysis"| M_PRO["🧠 Gemini 3.6 Pro (Deep Reasoning / 1M Context)"]
        ROUTER -->|"Compliance & Safety Rule Audit"| M_SPECIAL["🛡️ Specialist Compliance Audit Engine"]
    end

    M_FLASH --> EVAL["📊 Automated Evaluation Benchmark Suite"]
    M_PRO --> EVAL
    M_SPECIAL --> EVAL

    EVAL --> AUDIT_GATE{"Quality & Fairness Threshold Passed?"}
    AUDIT_GATE -->|"No"| REJECT["❌ Reject Release & Alert ML Team"]
    AUDIT_GATE -->|"Yes"| CANARY["🐤 Canary Deployment Stage (5% Traffic in GKE)"]

    CANARY --> MONITOR{"Drift or Error Spike?"}
    MONITOR -->|"Alert Triggered"| ROLLBACK["↩️ Automatic Rollback to Registry Baseline"]
    MONITOR -->|"Healthy for 24h"| PROMOTE["🚀 Production Promotion (100% Traffic)"]
\`\`\`
`,

  fdd: `# Functional Design Document (FDD)

## Enterprise Architecture Platform — OIL ONLY Governed Agentic AI Platform

**Document ID:** FDD-OIL-2026-001  
**Document version:** v1.0 (Functional & Architectural Implementation Approved Baseline)  
**Document status:** Approved — GxP & Enterprise Architecture Review Board Sign-Off  
**Related PRD:** PRD-OIL-2026-001 (Enterprise Architecture Platform — OIL ONLY PRD v1.0)  
**Related use case:** Medical Information Request (MIR), Commercial MLR Review, Pharmacovigilance AE Intake  
**Business function:** Medical Affairs, Commercial MLR, Clinical Operations, Regulatory Affairs, Pharmacovigilance  
**Product owner:** Dr. Elena Vance (VP, Cognitive Platforms & Digital Product)  
**Functional lead:** Nitin Aggarwal (Principal AI Systems Architect)  
**Technical lead:** David K. Thorne (Principal Cloud Infrastructure Lead)  
**Quality lead:** Dr. Aris Thorne, MD (Global Computer System Validation Lead)  
**Compliance lead:** Sarah Chen, JD (Senior VP, Global Regulatory & Quality Compliance)  
**Security lead:** Robert Sterling, CISSP (Enterprise Security & DevSecOps Lead)  
**Date created:** August 1, 2026  
**Last updated:** August 2, 2026  
**Target release:** Release 1 Controlled Production Pilot (Q3 2026)  

---

# 1. High-Level Functional Architecture Flow

### 📐 Visual Diagram 1: Multi-Agent Delegation Topology & ReAct Cognitive Loop
\`\`\`mermaid
graph TD
    INTAKE["📥 User Objective Intake"] --> PLANNER["📋 Planner Agent (Task Graph Decomposition)"]
    
    PLANNER --> RETRIEVAL["🔍 Retrieval Agent (Access-Aware Search)"]
    PLANNER --> DOMAIN["🧬 Domain Specialist Agents (Medical / Regulatory Synthesis)"]
    PLANNER --> SAFETY["🛡️ Safety & PV Detector Agent (Real-Time AE Screening)"]
    PLANNER --> COMPLIANCE["📋 Compliance & Policy Agent (FDA Label & Fair Balance)"]

    RETRIEVAL --> EVAL["📌 Evidence-Assessment Agent (Claim-Level Citations)"]
    DOMAIN --> QC["🎯 Quality-Control Agent (NLI Claim Verification)"]

    QC --> HITL["🛡️👤 Human-Review Coordinator (Unified Governance Board Gate)"]
    HITL --> ACTION["🔌 Action Agent (Idempotent System Commit)"]
\`\`\`
`,

  brd: `# Business Requirements Document (BRD)

## Enterprise Architecture Platform — OIL ONLY Executive Business & ROI Blueprint

**Document ID:** BRD-OIL-2026-001  
**Document version:** v1.0 (C-Suite & Executive Steering Committee Approved Baseline)  
**Document status:** Approved — Executive Steering Committee Sign-Off  
**Executive sponsor:** Dr. Marcus Vance (Executive VP, Global Medical & Commercial Operations)  
**Business owner:** Dr. Elena Vance (VP, Cognitive Platforms & Digital Product)  
**Product owner:** Dr. Elena Vance  
**Program manager:** Jennifer Sterling (Enterprise AI Program Management Director)  
**Business analyst:** Kabir Mehta (Principal Healthcare Business Analyst)  
**Medical or regulatory lead:** Dr. Aris Thorne, MD  
**Compliance lead:** Sarah Chen, JD  
**Quality lead:** Dr. Aris Thorne, MD  
**Technology lead:** Nitin Aggarwal  

---

# 1. Executive Business Vision & Value Map

### 📐 Visual Diagram 1: Strategic Business Outcome Transformation & Value Realization Dashboard
\`\`\`mermaid
graph LR
    subgraph METRIC1["⏱️ Workflow Cycle Time"]
        M1_BASE["Legacy Baseline:<br/>14 Business Days"] --> M1_TGT["Target Future State:<br/><b>< 48 Hours</b> (85% Faster)"]
    end

    subgraph METRIC2["🔄 MLR / MIR Revision Cycles"]
        M2_BASE["Legacy Baseline:<br/>3.4 Revision Rounds"] --> M2_TGT["Target Future State:<br/><b>< 1.2 Rounds</b> (65% Drop)"]
    end

    subgraph METRIC3["🎯 First-Pass Acceptance"]
        M3_BASE["Legacy Baseline:<br/>62% Acceptance Rate"] --> M3_TGT["Target Future State:<br/><b>> 94% Acceptance</b>"]
    end

    subgraph METRIC4["🛡️ Pharmacovigilance & Audit"]
        M4_BASE["Legacy Baseline:<br/>Fragmented Audit Records"] --> M4_TGT["Target Future State:<br/><b>Zero Compliance Breaches</b>"]
    end
\`\`\`
`,

  tdd: `# Technical Design Document (TDD)

## Enterprise Architecture Platform — OIL ONLY Technical Design Document

**Document ID:** TDD-OIL-2026-001  
**Document version:** v1.0 (Engineering Architecture Review Ready)  
**Document status:** Approved — Engineering Lead Sign-Off  
**Related BRD:** BRD-OIL-2026-001  
**Related PRD:** PRD-OIL-2026-001  
**Related FDD:** FDD-OIL-2026-001  
**Related SDD:** SDD-OIL-2026-001  
**System owner:** Dr. Elena Vance  
**Solution architect:** Nitin Aggarwal  
**Technical lead:** Nitin Aggarwal  

---

# 1. Multi-Service Monorepo Component Architecture

### 📐 Visual Diagram 1: Technical Engineering Service Topology
\`\`\`mermaid
graph TD
    GATEWAY["🚪 Google API Gateway"] --> ORCHESTRATOR["⚙️ Agent Orchestrator Pod (GKE)"]
    ORCHESTRATOR --> REACT["🧠 ReAct Cognitive Loop Engine"]
    REACT --> TOOL_GW["🔌 Governed Tool Gateway"]
    TOOL_GW --> AUDIT_DB["🗄️ Immutable Audit Store (Postgres / SHA-256)"]
\`\`\`
`,

  exec_brief: `# Executive Architecture Brief (EAB)

## Enterprise Architecture Platform — OIL ONLY Agentic AI Cognition & Governance Hub

**Document ID:** EAB-OIL-2026-001  
**Document version:** v1.0 (Architecture Review Board Sign-Off Ready)  
**Document status:** Approved — Executive Steering Committee Sign-Off  
**Executive sponsor:** Dr. Marcus Vance  
**Business owner:** Dr. Elena Vance  

---

# 1. Eight-Layer Enterprise Governed Agentic AI Architecture Blueprint

### 📐 Visual Diagram 1: Eight-Layer Enterprise Governed Agentic AI Architecture Blueprint
\`\`\`mermaid
graph TD
    subgraph L1["1. User Experience Layer"]
        USERS["👥 Medical Info Specialists / Regulatory Leads / MLR Reviewers"]
        PORTAL["🖥️ Workspace Portal & Live Google Docs Reader"]
        USERS --> PORTAL
    end

    subgraph L2["2. Identity & Access Layer"]
        PORTAL --> IAM["🔐 Enterprise SSO / OAuth2 / MFA / ABAC Attributes"]
    end

    subgraph L3_L4["3 & 4. Workflow, Agent Orchestrator & Specialized AI Agents Tier"]
        IAM --> ORCH["⚙️ Workflow & Agent Orchestrator (GKE Private Subnet)"]
        ORCH <--> PLANNER["📋 Planner Agent (ReAct Cognitive Loop)"]
        ORCH <--> SPECIALISTS["🤖 Specialized Domain Agents (Medical / Clinical / Regulatory / Safety)"]
    end

    subgraph L5["5. Model Gateway & Approved AI Models"]
        SPECIALISTS --> GW["🚪 Model Gateway (Routing & Token Budget Control)"]
        GW --> LLM["🧠 Approved Model Endpoints (Gemini 3.6 Pro / Flash)"]
    end
\`\`\`
`,
};
