// Blueprint 29 V2 — high-readability 6Rs Migration Disposition Matrix.
// Native editable mxGraph master; self-contained and deterministic.

const BOX='rounded=1;arcSize=8;whiteSpace=wrap;html=1;verticalAlign=middle;fontFamily=Inter;';
const TEXT='text;html=1;strokeColor=none;fillColor=none;fontFamily=Inter;verticalAlign=middle;';
const BLUE='#0B3B82';
function esc(v:unknown):string{return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function safe(v:unknown):string{const r=String(v??'');if(r.includes('&lt;')||r.includes('&#'))return r;return esc(r).replace(/\n/g,'&lt;br&gt;');}
function v(id:string,value:string,style:string,x:number,y:number,w:number,h:number):string{return `<mxCell id="${id}" value="${safe(value)}" style="${style}" vertex="1" parent="1"><mxGeometry x="${x}" y="${y}" width="${w}" height="${h}" as="geometry"/></mxCell>`;}
function e(id:string,source:string,target:string,color='#175CD3',dashed=false,label=''):string{return `<mxCell id="${id}" value="${safe(label)}" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;strokeColor=${color};strokeWidth=2;${dashed?'dashed=1;dashPattern=6 4;':''}endArrow=block;endFill=1;fontSize=10;fontColor=#344054;labelBackgroundColor=#FFFFFF;" edge="1" parent="1" source="${source}" target="${target}"><mxGeometry relative="1" as="geometry"/></mxCell>`;}
function badge(id:string,label:string,x:number,y:number,w:number):string{return v(id,label,`${BOX}fillColor=#FFFFFF;strokeColor=#B4C8EA;strokeWidth=1;fontColor=#344054;fontStyle=1;fontSize=10.5;align=center;`,x,y,w,26);}
function section(id:string,n:number,title:string,sub:string,x:number,y:number,w:number):string[]{return[v(id,'',`${BOX}fillColor=${BLUE};strokeColor=${BLUE};`,x,y,w,46),v(`${id}_n`,String(n),'ellipse;html=1;fillColor=#FFFFFF;strokeColor=#FFFFFF;fontColor=#0B3B82;fontStyle=1;fontSize=12;align=center;',x+8,y+9,26,26),v(`${id}_t`,`&lt;b&gt;${esc(title)}&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9.8px;font-weight:400&quot;&gt;${esc(sub)}&lt;/span&gt;`,`${TEXT}fontColor=#FFFFFF;fontSize=12.2;align=left;`,x+42,y+3,w-50,39)];}
function card(id:string,title:string,body:string,x:number,y:number,w:number,h:number,stroke='#B4C8EA',fill='#FFFFFF',titleColor='#101828'):string[]{return[v(id,'',`${BOX}fillColor=${fill};strokeColor=${stroke};strokeWidth=1.1;`,x,y,w,h),v(`${id}_txt`,`&lt;b&gt;${esc(title)}&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9.7px;color:#475467;line-height:1.35&quot;&gt;${esc(body)}&lt;/span&gt;`,`${TEXT}fontColor=${titleColor};fontSize=10.6;align=left;spacing=6;whiteSpace=wrap;overflow=hidden;`,x+7,y+4,w-14,h-8)];}
function pill(id:string,label:string,value:string,x:number,y:number,w:number,color:string):string{return v(id,`&lt;b&gt;${esc(label)}&lt;/b&gt;&nbsp;&nbsp;${esc(value)}`,`${BOX}fillColor=#FFFFFF;strokeColor=#D0D5DD;strokeWidth=1;fontColor=${color};fontSize=9.5;align=center;`,x,y,w,28);}

export function getApprovedSixRsMigrationMatrixV2Xml():string{
 const n:string[]=['<mxCell id="0"/>','<mxCell id="1" parent="0"/>'];const edges:string[]=[];const W=1760,H=1040;
 n.push(v('count','&lt;b&gt;29 OF 50&lt;/b&gt;',`${BOX}fillColor=#175CD3;strokeColor=#175CD3;fontColor=#FFFFFF;fontStyle=1;fontSize=17;align=center;`,16,14,118,40));
 n.push(v('title','&lt;b&gt;6Rs Migration Disposition Matrix&lt;/b&gt;',`${TEXT}fontColor=#101828;fontSize=30;fontStyle=1;align=left;`,154,8,900,42));
 n.push(v('subtitle','End-to-end cloud migration disposition: Rehost, Replatform, Refactor, Retain, Retire and Repurchase — with explicit scoring, decision rules, dependencies, sequencing and outcome evidence.',`${TEXT}fontColor=#475467;fontSize=12.2;align=left;`,154,48,1180,32));
 n.push(v('master','MASTER BLUEPRINT',`${BOX}fillColor=#FFFFFF;strokeColor=#175CD3;strokeWidth=1.2;fontColor=#175CD3;fontStyle=1;fontSize=11;align=center;`,1560,14,180,30));
 n.push(badge('chip1','App & Integration',16,88,145));n.push(badge('chip2','Logical',170,88,90));n.push(badge('chip3','Layer 4 (Application)',269,88,175));n.push(badge('chip4','Phase 5: Transition Planning & Operational Readiness',453,88,365));n.push(badge('chip5','Blueprint P5-APP-L-01',827,88,190));
 n.push(...section('s1',1,'CURRENT ESTATE / INVENTORY','Discover & classify workload estate',16,126,240));n.push(...section('s2',2,'ASSESSMENT ENGINE','Score, gate and explain the decision',266,126,390));n.push(...section('s3',3,'6R DISPOSITION RECOMMENDATION','Select the optimal path for each workload',666,126,820));n.push(...section('s4',4,'TARGET OUTCOME & VALUE','Business outcomes & evidence',1496,126,248));
 n.push(v('estate_shell','',`${BOX}fillColor=#F8FAFF;strokeColor=#B4C8EA;strokeWidth=1;`,16,178,240,600));n.push(v('estate_h','&lt;b&gt;Source Systems & Assets&lt;/b&gt;',`${TEXT}fontSize=11.4;fontColor=${BLUE};align=center;`,28,185,216,22));
 const estate=[['Legacy Databases','Oracle, SQL Server, DB2, Sybase'],['Mainframe Systems','CICS, IMS, VSAM'],['Custom Applications','.NET, Java, PHP, COBOL'],['Packaged Applications','SAP, PeopleSoft, JD Edwards'],['File Shares & Content','NAS, file servers, SharePoint'],['APIs & Integrations','REST, SOAP, MQ, Kafka'],['Data & Analytics','DW, ETL, reporting, ML'],['Infrastructure','VMware, physical, network']];
 estate.forEach((r,i)=>{const y=214+i*55;n.push(v(`est_i_${i}`,String(i+1),'ellipse;html=1;fillColor=#EFF6FF;strokeColor=#7AA7E8;fontColor=#175CD3;fontStyle=1;fontSize=10;align=center;',30,y+7,28,28));n.push(v(`est_${i}`,`&lt;b&gt;${esc(r[0])}&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9.2px&quot;&gt;${esc(r[1])}&lt;/span&gt;`,`${TEXT}fontSize=10.3;fontColor=#101828;align=left;`,68,y,166,42));});
 n.push(v('snapshot','&lt;b&gt;Inventory Snapshot&lt;/b&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;318&lt;/b&gt; Apps &nbsp;&nbsp; &lt;b&gt;842&lt;/b&gt; DBs &nbsp;&nbsp; &lt;b&gt;156 TB&lt;/b&gt; Data&lt;br&gt;&lt;b&gt;612&lt;/b&gt; Integrations',`${BOX}fillColor=#FFFFFF;strokeColor=#7AA7E8;strokeWidth=1.1;fontColor=#344054;fontSize=10;align=center;`,28,674,216,88));
 n.push(v('assess_shell','',`${BOX}fillColor=#F8FAFF;strokeColor=#B4C8EA;strokeWidth=1;`,266,178,390,600));n.push(v('dims_h','&lt;b&gt;Assessment Dimensions (Weighted)&lt;/b&gt;',`${TEXT}fontSize=11.2;fontColor=${BLUE};align=left;`,280,185,230,22));
 const dims=[['Business','30%','Business value\nStrategic alignment\nCriticality\nStakeholder impact','#039855','#F2FBF6'],['Technical','40%','Technical debt\nComplexity & maintainability\nPerformance\nDependency / shared-DB coupling','#175CD3','#F4F8FF'],['Cloud Readiness','30%','Platform fit\nService availability\nEffort & risk\nOperational maturity','#7F56D9','#F8F5FF']];
 dims.forEach((d,i)=>{const y=214+i*119;n.push(v(`dim_${i}`,'',`${BOX}fillColor=${d[5]};strokeColor=${d[4]};strokeWidth=1.2;`,280,y,220,109));n.push(v(`dim_${i}_t`,`&lt;b&gt;${d[0]}&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9.3px;color:#344054&quot;&gt;• ${esc(d[2]).replace(/\n/g,'&lt;br&gt;• ')}&lt;/span&gt;`,`${TEXT}fontSize=10.8;fontColor=${d[4]};align=left;`,291,y+7,158,93));n.push(v(`dim_${i}_w`,`&lt;b&gt;${d[1]}&lt;/b&gt;`,`${BOX}fillColor=#FFFFFF;strokeColor=${d[4]};strokeWidth=1.1;fontColor=${d[4]};fontStyle=1;fontSize=15;align=center;`,452,y+30,38,48));});
 n.push(v('score_model','&lt;b&gt;Score Inputs (0–100)&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9.2px&quot;&gt;Business Value • Technical Fit • Cloud Compatibility&lt;br&gt;Effort↓ • Risk↓ • TCO • Time to Value • Compliance/Data Sensitivity&lt;/span&gt;',`${BOX}fillColor=#FFFFFF;strokeColor=#D0D5DD;strokeWidth=1;fontColor=#344054;fontSize=10;align=center;`,510,214,132,110));
 n.push(v('hard_gates','&lt;b&gt;Hard Constraints / Gates&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9.2px&quot;&gt;Regulatory / residency • unsupported service • vendor lock-in • shared database • integration criticality • outage tolerance&lt;/span&gt;',`${BOX}fillColor=#FFF8EB;strokeColor=#F79009;strokeWidth=1.1;fontColor=#7A2E0E;fontSize=10;align=center;`,510,334,132,120));
 n.push(v('decision_engine','&lt;b&gt;Disposition Engine&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9px;color:#475467&quot;&gt;Weighted score + hard gates + dependency graph + decision rules → ranked 6R recommendation + confidence&lt;/span&gt;',`${BOX}fillColor=#FFFFFF;strokeColor=#175CD3;strokeWidth=1.3;fontColor=#175CD3;fontSize=10.8;align=center;`,280,470,362,96));
 n.push(v('decision_rules','&lt;b&gt;Disposition Decision Rules&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9px&quot;&gt;&lt;b&gt;Rehost:&lt;/b&gt; low change + urgent move&lt;br&gt;&lt;b&gt;Replatform:&lt;/b&gt; managed-service fit + moderate change&lt;br&gt;&lt;b&gt;Refactor:&lt;/b&gt; high debt + strategic differentiation&lt;br&gt;&lt;b&gt;Retain:&lt;/b&gt; hard constraint / poor value now&lt;br&gt;&lt;b&gt;Retire:&lt;/b&gt; low value / redundant&lt;br&gt;&lt;b&gt;Repurchase:&lt;/b&gt; commodity capability + strong SaaS fit&lt;/span&gt;',`${BOX}fillColor=#F4F8FF;strokeColor=#7AA7E8;strokeWidth=1.2;fontColor=#175CD3;fontSize=10;align=left;spacing=7;`,280,579,362,137));
 n.push(v('sequence','&lt;b&gt;Assessment Process&lt;/b&gt;&lt;br&gt;Discover → Score → Apply Gates → Compare 6Rs → Recommend → Sequence',`${BOX}fillColor=#FFFFFF;strokeColor=#D0D5DD;strokeWidth=1;fontColor=#344054;fontSize=9.7;align=center;`,280,728,362,35));
 edges.push(e('estate_to_assess','estate_shell','assess_shell'));edges.push(e('score_to_engine','score_model','decision_engine'));edges.push(e('gates_to_engine','hard_gates','decision_engine','#F79009',true));edges.push(e('rules_to_engine','decision_rules','decision_engine','#175CD3',true));
 const rs=[{id:'rehost',name:'1 Rehost',sub:'Lift & Shift',color:'#175CD3',fill:'#F4F8FF',def:'Move with minimal application change',best:'Stable workload\nLow technical debt',target:'Compute Engine / Migrate to VMs\nPersistent Disk',eff:'Low',risk:'Low',speed:'Fast',value:'Fastest infra exit',timeline:'30–60d'},{id:'replatform',name:'2 Replatform',sub:'Lift & Reshape',color:'#0E9384',fill:'#F2FBF9',def:'Optimize with managed services',best:'Moderate change\nManaged-service fit',target:'Cloud Run / GKE\nCloud SQL / AlloyDB',eff:'Medium',risk:'Medium',speed:'Medium',value:'Lower ops burden',timeline:'60–120d'},{id:'refactor',name:'3 Refactor',sub:'Re-architect',color:'#7F56D9',fill:'#F8F5FF',def:'Redesign to cloud-native',best:'High technical debt\nStrategic differentiation',target:'Microservices / serverless\nPub/Sub / Spanner',eff:'High',risk:'High',speed:'Slow',value:'Strategic modernization',timeline:'120–360d'},{id:'retain',name:'4 Retain',sub:'Revisit / Hybrid',color:'#475467',fill:'#F9FAFB',def:'Keep current location for now',best:'Hard constraint\nWeak migration value',target:'On-prem / private cloud\nHybrid connectivity + revisit date',eff:'Low',risk:'Low–Med',speed:'Fast',value:'Avoid premature change',timeline:'Review date'},{id:'retire',name:'5 Retire',sub:'Decommission',color:'#D92D20',fill:'#FFF7F7',def:'Remove obsolete capability',best:'Low value\nRedundant / unused',target:'Archive required data\nRemove infra, licenses, integrations',eff:'Low–Med',risk:'Low',speed:'Fast',value:'Direct cost elimination',timeline:'30–90d'},{id:'repurchase',name:'6 Repurchase',sub:'Replace with SaaS',color:'#B54708',fill:'#FFF9ED',def:'Replace with SaaS / managed product',best:'Commodity capability\nStrong vendor fit',target:'SaaS + identity mapping\nData migration + integration repointing',eff:'Medium',risk:'Medium',speed:'Medium',value:'Faster feature adoption',timeline:'60–180d'}];
 const rx=672,rw=130,gap=7;rs.forEach((r,i)=>{const x=rx+i*(rw+gap);n.push(v(`r_${r.id}`,'',`${BOX}fillColor=${r.fill};strokeColor=${r.color};strokeWidth=1.25;`,x,178,rw,470));n.push(v(`r_${r.id}_h`,`&lt;b&gt;${r.name}&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9px&quot;&gt;${r.sub}&lt;/span&gt;`,`${TEXT}fontColor=${r.color};fontSize=11.1;align=center;`,x+5,187,rw-10,36));n.push(v(`r_${r.id}_def`,r.def,`${TEXT}fontColor=#344054;fontSize=9.5;align=center;`,x+7,228,rw-14,45));n.push(...card(`r_${r.id}_best`,'Best For',r.best,x+6,280,rw-12,74,r.color,'#FFFFFF',r.color));n.push(...card(`r_${r.id}_target`,'Target / Example',r.target,x+6,362,rw-12,92,r.color,'#FFFFFF','#101828'));n.push(pill(`r_${r.id}_eff`,'Effort',r.eff,x+6,462,rw-12,r.color));n.push(pill(`r_${r.id}_risk`,'Risk',r.risk,x+6,494,rw-12,r.color));n.push(pill(`r_${r.id}_speed`,'Speed',r.speed,x+6,526,rw-12,r.color));n.push(v(`r_${r.id}_value`,`&lt;b&gt;Value&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:8.9px&quot;&gt;${r.value}&lt;/span&gt;`,`${BOX}fillColor=#FFFFFF;strokeColor=${r.color};strokeWidth=1;fontColor=${r.color};fontSize=9.3;align=center;`,x+6,560,rw-12,40));n.push(v(`r_${r.id}_timeline`,`&lt;b&gt;Illustrative timeline&lt;/b&gt;&lt;br&gt;${r.timeline}`,`${BOX}fillColor=${r.fill};strokeColor=${r.color};strokeWidth=1;fontColor=${r.color};fontSize=9.1;align=center;`,x+6,606,rw-12,35));});for(const r of rs)edges.push(e(`decision_${r.id}`,'decision_engine',`r_${r.id}`,'#175CD3',true));
 n.push(v('confidence','',`${BOX}fillColor=#FFFFFF;strokeColor=#B4C8EA;strokeWidth=1.1;`,666,660,820,118));n.push(v('confidence_h','&lt;b&gt;Decision Confidence, Rationale & Execution Sequencing&lt;/b&gt;',`${TEXT}fontSize=10.9;fontColor=${BLUE};align=center;`,676,664,800,20));const conf=[['Confidence','High / Med / Low'],['Primary Drivers','Top 3 factors'],['Constraints','Blocking gates'],['Dependencies','Up/downstream + shared DB'],['Assumptions','Key assumptions'],['Wave / Sequence','Wave 1–N + prerequisites'],['Next Step','Action + owner']];conf.forEach((c,i)=>n.push(v(`conf_${i}`,`&lt;b&gt;${c[0]}&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:8.5px&quot;&gt;${c[1]}&lt;/span&gt;`,`${BOX}fillColor=#F8FAFF;strokeColor=#D0D5DD;strokeWidth=0.8;fontColor=#344054;fontSize=9.4;align=center;`,676+i*113,692,106,70)));
 n.push(v('out_shell','',`${BOX}fillColor=#F8FAFF;strokeColor=#B4C8EA;strokeWidth=1;`,1496,178,248,600));const outcomes=[['Cost Optimization','Reduce OpEx / licensing','#039855','#F2FBF6'],['Risk Reduction','Lower security & operational risk','#D92D20','#FFF7F7'],['Agility & Innovation','Faster delivery & time to market','#175CD3','#F4F8FF'],['Operational Excellence','Automate, standardize, improve reliability','#7F56D9','#F8F5FF'],['Strategic Alignment','Enable business goals & transformation','#B54708','#FFF9ED']];outcomes.forEach((o,i)=>n.push(v(`out_${i}`,`&lt;b&gt;${o[0]}&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9.4px&quot;&gt;${o[1]}&lt;/span&gt;`,`${BOX}fillColor=${o[3]};strokeColor=${o[2]};strokeWidth=1;fontColor=${o[2]};fontSize=10.5;align=left;spacing=8;`,1508,194+i*72,224,62)));n.push(v('reports','&lt;b&gt;REPORTING & ARTIFACTS&lt;/b&gt;&lt;br&gt;&lt;br&gt;• 6R Disposition Report&lt;br&gt;• Workload Heatmap&lt;br&gt;• Dependency / Shared-DB Map&lt;br&gt;• Migration Wave Roadmap&lt;br&gt;• Business Case & ROI&lt;br&gt;• Risk & Compliance Report&lt;br&gt;• Decision Rationale / Assumptions',`${BOX}fillColor=#FFFFFF;strokeColor=#7AA7E8;strokeWidth=1.1;fontColor=#344054;fontSize=9.8;align=left;spacing=10;`,1508,558,224,204));edges.push(e('reco_to_out','r_replatform','out_0','#0E9384'));
 n.push(v('cross','',`${BOX}fillColor=#F8FAFF;strokeColor=#B4C8EA;strokeWidth=1.1;`,16,794,1728,108));n.push(v('cross_h','&lt;b&gt;CROSS-CUTTING CONSIDERATIONS — apply to every disposition and wave&lt;/b&gt;',`${TEXT}fontSize=10.8;fontColor=${BLUE};align=center;`,30,800,1700,22));const cross=[['Security & Compliance','IAM, least privilege, CMEK, VPC-SC, data classification'],['Network & Connectivity','VPC, firewall, private access, Interconnect/VPN, DNS'],['Data Management','Backup/DR, retention, archival, lifecycle, data migration'],['Observability','Monitoring, logging, alerting, dashboards, SLOs'],['FinOps & Cost Governance','TCO, budgets, rightsizing, commitments, chargeback'],['Operational Readiness','Runbooks, automation, SRE, capacity, support']];cross.forEach((c,i)=>n.push(v(`cross_${i}`,`&lt;b&gt;${c[0]}&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9px&quot;&gt;${c[1]}&lt;/span&gt;`,`${BOX}fillColor=#FFFFFF;strokeColor=#D0D5DD;strokeWidth=0.8;fontColor=#344054;fontSize=9.7;align=center;`,28+i*282,834,270,52)));
 n.push(v('footer','',`${BOX}fillColor=#FFFFFF;strokeColor=#B4C8EA;strokeWidth=1;`,16,914,1728,104));n.push(v('legend','&lt;b&gt;LEGEND&lt;/b&gt;&lt;br&gt;━━ Evaluation / decision flow &nbsp;&nbsp; ┄┄ Rule / dependency influence &nbsp;&nbsp; → Outcome / execution flow',`${TEXT}fontSize=9.2;fontColor=#344054;align=left;`,30,925,350,58));n.push(v('defs','&lt;b&gt;6R DEFINITIONS&lt;/b&gt;&lt;br&gt;Rehost = lift & shift | Replatform = managed-service optimization | Refactor = re-architect | Retain = keep/revisit or strategic hybrid | Retire = decommission | Repurchase = replace with SaaS/managed product',`${TEXT}fontSize=9.1;fontColor=#344054;align=left;`,390,925,760,58));n.push(v('semantics','&lt;b&gt;SCORING / CONFIDENCE&lt;/b&gt;&lt;br&gt;Scores are workload-specific. Confidence reflects evidence quality and decision consistency; timelines and ROI shown in this blueprint are illustrative only, not universal benchmarks.',`${TEXT}fontSize=9.1;fontColor=#344054;align=left;`,1160,925,555,58));n.push(v('framework','Framework references: Google Cloud Well-Architected Framework | Cloud Adoption Framework | FinOps | NIST | CIS Controls | organizational policy and risk standards',`${TEXT}fontSize=8.8;fontColor=#667085;align=center;`,250,988,1260,18));
 return `<mxfile host="app.diagrams.net" modified="2026-08-20T19:45:00.000Z" agent="PromptCanvas" version="24.0.0" type="device"><diagram id="six_rs_migration_disposition_matrix_v2" name="6Rs Migration Disposition Matrix"><mxGraphModel dx="${W}" dy="${H}" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="${W}" pageHeight="${H}" background="#FFFFFF"><root>${n.join('\n')}${edges.join('\n')}</root></mxGraphModel></diagram></mxfile>`;
}
