import { SupportedLanguage } from './i18n';

export function getLocalizedWorkspaceStrings(lang: SupportedLanguage) {
  const dict: Record<SupportedLanguage, Record<string, string>> = {
    hi: {
      canvasLabel: 'कैनवास:',
      diagramLabel: 'आरेख:',
      versionText: 'संस्करण 21 (नवीनतम)',
      resetBtn: 'रिसेट',
      activeWorkspaceHeader: 'सक्रिय वर्कस्पेस एवं डिज़ाइन',
      updatedAgo: '11 घंटे पहले अपडेट किया गया • आरेख संस्करण v28',
      architectSuite: 'आर्किटेक्ट सूट एवं AI',
      estCost: 'अनुमानित $14,670/माह',
      exportStudio: 'एक्सपोर्ट स्टूडियो',
      composeDoc: 'दस्तावेज़ लिखें',
      secAuditBtn: 'सुरक्षा ऑडिट',
      suggestedRefinements: 'सुझाए गए सुधार',
      promptPlaceholder: 'उदा., PK/FK संबंधों के साथ Dim_Customer_Account तालिका जोड़ें...',
      sug1: 'Dim_Customer_Account और Dim_Merchant तालिकाओं को जोड़ें',
      sug2: 'Fact_Account_Transactions को 1:N कार्डिनलिटी से जोड़ें',
      sug3: 'PCI-DSS और KYC अनुपालन नियम लागू करें',
      sug4: 'कार्ड नेटवर्क शुल्क टियर विशेषताएँ जोड़ें',
      refineHint: 'भेजने के लिए Enter दबाएं। Gemini 3.6 Pro आपके आरेख को अद्यतन करेगा।',
      diagramTitle10: '10. एकीकृत सिस्टम दृश्य'
    },
    es: {
      canvasLabel: 'LIENZO:',
      diagramLabel: 'DIAGRAMA:',
      versionText: 'Versión 21 (Última)',
      resetBtn: 'Restablecer',
      activeWorkspaceHeader: 'ESPACIO DE TRABAJO Y DISEÑO ACTIVO',
      updatedAgo: 'Actualizado hace 11h • Versión de Diagrama v28',
      architectSuite: 'SUITE DE ARQUITECTO E IA',
      estCost: 'Est. $14,670/mes',
      exportStudio: 'Estudio Exportar',
      composeDoc: 'Redactar Doc',
      secAuditBtn: 'Auditoría de Seguridad',
      suggestedRefinements: 'MEJORAS SUGERIDAS',
      promptPlaceholder: 'ej., Agregar tabla Dim_Customer_Account con relaciones PK/FK...',
      sug1: 'Agregar tablas Dim_Customer_Account y Dim_Merchant',
      sug2: 'Conectar Fact_Account_Transactions con cardinalidad 1:N',
      sug3: 'Aplicar Reglas de Cumplimiento PCI-DSS y KYC',
      sug4: 'Agregar Atributos de Tarifa de Red de Tarjetas',
      refineHint: 'Presione Enter para enviar. Gemini 3.6 Pro perfeccionará su diagrama.',
      diagramTitle10: '10. Vista Unificada del Sistema'
    },
    pt: {
      canvasLabel: 'TELA:',
      diagramLabel: 'DIAGRAMA:',
      versionText: 'Versão 21 (Mais Recente)',
      resetBtn: 'Redefinir',
      activeWorkspaceHeader: 'ESPAÇO DE TRABALHO E DESIGN ATIVO',
      updatedAgo: 'Atualizado há 11h • Versão do Diagrama v28',
      architectSuite: 'SUÍTE DE ARQUITETO E IA',
      estCost: 'Est. $14.670/mês',
      exportStudio: 'Estúdio de Exportação',
      composeDoc: 'Compor Doc',
      secAuditBtn: 'Auditoria de Segurança',
      suggestedRefinements: 'MELHORIAS SUGERIDAS',
      promptPlaceholder: 'ex., Adicionar tabela Dim_Customer_Account com chaves PK/FK...',
      sug1: 'Adicionar tabelas Dim_Customer_Account e Dim_Merchant',
      sug2: 'Conectar Fact_Account_Transactions com cardinalidade 1:N',
      sug3: 'Aplicar Regras de Conformidade PCI-DSS e KYC',
      sug4: 'Adicionar Atributos de Tarifa da Rede de Cartões',
      refineHint: 'Pressione Enter para enviar. Gemini 3.6 Pro aprimorará seu diagrama.',
      diagramTitle10: '10. Visão Unificada de Sistema'
    },
    ja: {
      canvasLabel: 'キャンバス:',
      diagramLabel: '図面:',
      versionText: 'バージョン 21 (最新)',
      resetBtn: 'リセット',
      activeWorkspaceHeader: 'アクティブなワークスペースとデザイン',
      updatedAgo: '11時間前に更新 • 図面バージョン v28',
      architectSuite: '設計スイートとAI',
      estCost: '見積もり $14,670/月',
      exportStudio: 'エクスポートスタジオ',
      composeDoc: 'ドキュメント作成',
      secAuditBtn: 'セキュリティ監査',
      suggestedRefinements: '推奨される改善提案',
      promptPlaceholder: '例: PK/FKリレーションを持つDim_Customer_Accountテーブルを追加...',
      sug1: 'Dim_Customer_AccountとDim_Merchantテーブルを追加',
      sug2: 'Fact_Account_Transactionsを1:N多重度で接続',
      sug3: 'PCI-DSSおよびKYCコンプライアンスルールを適用',
      sug4: 'カードネットワーク手数料層属性を追加',
      refineHint: 'Enterキーで送信。Gemini 3.6 Proがアクティブな構成図を洗練します。',
      diagramTitle10: '10. 統合システム構成図'
    },
    fr: {
      canvasLabel: 'CANEVAS:',
      diagramLabel: 'DIAGRAMME:',
      versionText: 'Version 21 (Dernière)',
      resetBtn: 'Réinitialiser',
      activeWorkspaceHeader: 'ESPACE DE TRAVAIL & DESIGN ACTIF',
      updatedAgo: 'Mis à jour il y a 11h • Version du Diagramme v28',
      architectSuite: 'SUITE ARCHITECTE & IA',
      estCost: 'Est. 14 670 $/mois',
      exportStudio: 'Studio d\x27Exportation',
      composeDoc: 'Rédiger Doc',
      secAuditBtn: 'Audit de Sécurité',
      suggestedRefinements: 'AMÉLIORATIONS SUGGÉRÉES',
      promptPlaceholder: 'ex., Ajouter la table Dim_Customer_Account avec relations PK/FK...',
      sug1: 'Ajouter les tables Dim_Customer_Account & Dim_Merchant',
      sug2: 'Connecter Fact_Account_Transactions avec cardinalité 1:N',
      sug3: 'Appliquer les règles de conformité PCI-DSS & KYC',
      sug4: 'Ajouter les attributs de frais de réseau de cartes',
      refineHint: 'Appuyez sur Entrée pour envoyer. Gemini 3.6 Pro affinera votre schéma.',
      diagramTitle10: '10. Vue Système Unifiée'
    },
    de: {
      canvasLabel: 'LEINWAND:',
      diagramLabel: 'DIAGRAMM:',
      versionText: 'Version 21 (Neueste)',
      resetBtn: 'Zurücksetzen',
      activeWorkspaceHeader: 'AKTIVER ARBEITSBEREICH & DESIGN',
      updatedAgo: 'Aktualisiert vor 11 Std. • Diagrammversion v28',
      architectSuite: 'ARCHITEKTUR-SUITE & KI',
      estCost: 'Ca. 14.670 $/Monat',
      exportStudio: 'Export-Studio',
      composeDoc: 'Dokument verfassen',
      secAuditBtn: 'Sicherheitsaudit',
      suggestedRefinements: 'EMPFOHLENE VERBESSERUNGEN',
      promptPlaceholder: 'z.B. Tabelle Dim_Customer_Account mit PK/FK-Beziehungen hinzufügen...',
      sug1: 'Tabellen Dim_Customer_Account & Dim_Merchant hinzufügen',
      sug2: 'Fact_Account_Transactions mit 1:N Kardinalität verknüpfen',
      sug3: 'PCI-DSS & KYC Compliance-Regeln erzwingen',
      sug4: 'Kartennetzwerk-Gebührenstufe-Attribute hinzufügen',
      refineHint: 'Eingabetaste zum Senden. Gemini 3.6 Pro verfeinert Ihr Diagramm.',
      diagramTitle10: '10. Vereinheitlichte Systemansicht'
    },
    ar: {
      canvasLabel: 'لوحة الرسم:',
      diagramLabel: 'المخطط:',
      versionText: 'الإصدار 21 (الأحدث)',
      resetBtn: 'إعادة ضبط',
      activeWorkspaceHeader: 'مساحة العمل والتصميم النشطة',
      updatedAgo: 'تم التحديث منذ 11 ساعة • إصدار المخطط v28',
      architectSuite: 'مجموعة المهندس الذكي والذكاء الاصطناعي',
      estCost: 'تقديري 14,670$/شهر',
      exportStudio: 'استوديو التصدير',
      composeDoc: 'كتابة وثيقة',
      secAuditBtn: 'تدقيق الأمان',
      suggestedRefinements: 'التحسينات المقترحة',
      promptPlaceholder: 'مثال: إضافة جدول Dim_Customer_Account مع علاقات المفاتيح...',
      sug1: 'إضافة جادول Dim_Customer_Account و Dim_Merchant',
      sug2: 'ربط Fact_Account_Transactions مع ارتباط 1:N',
      sug3: 'تطبيق قواعد امتثال PCI-DSS و KYC',
      sug4: 'إضافة سمات طبقة رسوم شبكة البطاقات',
      refineHint: 'اضغط Enter للإرسال. سيعمل Gemini 3.6 Pro على تحسين مخططك.',
      diagramTitle10: '10. عرض النظام الموحد'
    },
    zh: {
      canvasLabel: '画布:',
      diagramLabel: '图表:',
      versionText: '版本 21 (最新)',
      resetBtn: '重置',
      activeWorkspaceHeader: '当前工作区与设计',
      updatedAgo: '11小时前更新 • 图表版本 v28',
      architectSuite: '架构师套件与AI',
      estCost: '预估 $14,670/月',
      exportStudio: '导出中心',
      composeDoc: '撰写文档',
      secAuditBtn: '安全审计',
      suggestedRefinements: '建议下一步优化',
      promptPlaceholder: '例如: 添加具有主外键关系的 Dim_Customer_Account 数据表...',
      sug1: '添加 Dim_Customer_Account 与 Dim_Merchant 维度表',
      sug2: '按 1:N 基数连接 Fact_Account_Transactions 事实表',
      sug3: '执行 PCI-DSS 和 KYC 合规合规规则',
      sug4: '添加卡组织费率层级属性',
      refineHint: '按 Enter 发送。Gemini 3.6 Pro 将优化您的当前架构图。',
      diagramTitle10: '10. 统一系统架构视图'
    },
    id: {
      canvasLabel: 'KANVAS:',
      diagramLabel: 'DIAGRAM:',
      versionText: 'Versi 21 (Terbaru)',
      resetBtn: 'Atur Ulang',
      activeWorkspaceHeader: 'RUANG KERJA & DESAIN AKTIF',
      updatedAgo: 'Diperbarui 11 jam lalu • Versi Diagram v28',
      architectSuite: 'SUITE ARSITEK & AI',
      estCost: 'Est. $14.670/bulan',
      exportStudio: 'Studio Ekspor',
      composeDoc: 'Tulis Dokumen',
      secAuditBtn: 'Audit Keamanan',
      suggestedRefinements: 'PENYEMPURNAAN YANG DISARANKAN',
      promptPlaceholder: 'contoh, Tambahkan tabel Dim_Customer_Account dengan relasi PK/FK...',
      sug1: 'Tambahkan tabel Dim_Customer_Account & Dim_Merchant',
      sug2: 'Hubungkan Fact_Account_Transactions dengan kardinalitas 1:N',
      sug3: 'Terapkan Aturan Kepatuhan PCI-DSS & KYC',
      sug4: 'Tambahkan Atribut Tingkat Biaya Jaringan Kartu',
      refineHint: 'Tekan Enter untuk mengirim. Gemini 3.6 Pro akan menyempurnakan diagram Anda.',
      diagramTitle10: '10. Tampilan Sistem Terpadu'
    },
    en: {
      canvasLabel: 'CANVAS:',
      diagramLabel: 'DIAGRAM:',
      versionText: 'Version 21 (Latest)',
      resetBtn: 'Reset',
      activeWorkspaceHeader: 'ACTIVE WORKSPACE & DESIGN',
      updatedAgo: 'Updated 11h ago Diagram Version v28',
      architectSuite: 'ARCHITECT SUITE & AI',
      estCost: 'Est. $14,670/mo',
      exportStudio: 'Export Studio',
      composeDoc: 'Compose Doc',
      secAuditBtn: 'Security Audit',
      suggestedRefinements: 'SUGGESTED NEXT REFINEMENTS',
      promptPlaceholder: 'e.g., Add Dim_Customer_Account table with PK/FK relationships...',
      sug1: 'Add Dim_Customer_Account & Dim_Merchant tables',
      sug2: 'Connect Fact_Account_Transactions with 1:N cardinality',
      sug3: 'Enforce PCI-DSS & KYC Compliance Rules',
      sug4: 'Add Card Network Fee Tier Attributes',
      refineHint: 'Press Enter to send. Gemini 3.6 Pro will refine your active diagram.',
      diagramTitle10: '10. Unified System View'
    }
  };
  return dict[lang] || dict.en;
}

export function localizeDrawioXmlDeep(xml: string, lang: SupportedLanguage): string {
  if (lang === 'en' || !xml) return xml;

  const multilangLexicon: Record<SupportedLanguage, Array<[string, string]>> = {
    en: [],
    hi: [
      ["Enterprise Architecture Platform - 10. 10. UNIFIED SYSTEM VIEW (End-to-End without Compromise).", "एंटरप्राइज़ आर्किटेक्चर प्लेटफॉर्म - 10. एकीकृत सिस्टम दृश्य (एंड-टू-एंड)"],
      ["PLAN &amp; DATA FOUNDATION (Vetting &amp; ERD Integration)", "योजना एवं डेटा फ़ाउंडेशन (सत्यापन एवं ERD इंटीग्रेशन)"],
      ["PLAN & DATA FOUNDATION (Vetting & ERD Integration)", "योजना एवं डेटा फ़ाउंडेशन (सत्यापन एवं ERD इंटीग्रेशन)"],
      ["Project Planning", "परियोजना योजना"],
      ["Data Vetting", "डेटा सत्यापन"],
      ["Ethical Sourcing", "नैतिक स्रोत"],
      ["Dimensional Data Model (ERD)", "विमीय डेटा मॉडल (ERD)"],
      ["Track 2a: DATA ENGINEERING &amp; DFD", "ट्रैक 2a: डेटा इंजीनियरिंग एवं DFD"],
      ["Track 2a: DATA ENGINEERING & DFD", "ट्रैक 2a: डेटा इंजीनियरिंग एवं DFD"],
      ["Track 2b: FEATURE ENGINEERING FLOW", "ट्रैक 2b: फ़ीचर इंजीनियरिंग प्रवाह"],
      ["Track 2c: AI MODEL &amp; PROMPT DEVELOPMENT LIFECYCLE", "ट्रैक 2c: AI मॉडल एवं प्रॉम्प्ट विकास जीवनचक्र"],
      ["Track 2c: AI MODEL & PROMPT DEVELOPMENT LIFECYCLE", "ट्रैक 2c: AI मॉडल एवं प्रॉम्प्ट विकास जीवनचक्र"],
      ["Governance Boundary incorporating the full unified audits from Image 15", "पूर्ण एकीकृत ऑडिट को शामिल करने वाली शासन एवं सुरक्षा सीमा"],
      ["COGNITIVE ARCHITECTURE &amp; SECURE DEPLOYMENT", "संज्ञानात्मक आर्किटेक्चर एवं सुरक्षित परिनियोजन"],
      ["COGNITIVE ARCHITECTURE & SECURE DEPLOYMENT", "संज्ञानात्मक आर्किटेक्चर एवं सुरक्षित परिनियोजन"],
      ["Primary Governed VPC Network (Secure Managed Environment)", "प्राथमिक शासित वीपीसी नेटवर्क (सुरक्षित प्रबन्धित वातावरण)"],
      ["Private Application Subnet (Isolated)", "निजी एप्लिकेशन सबनेट (पृथक)"],
      ["Core Agent Orchestrator (GKE Pod)", "कोर एजेंट ऑर्केस्ट्रेटर (GKE पॉड)"],
      ["Integrated System Prompt", "एकीकृत सिस्टम प्रॉम्प्ट"],
      ["Conversation Memory", "बातचीत मेमोरी"],
      ["Gemini LLM (Reasoner)", "जेमिनी एलएलएम (तर्क इंजन)"],
      ["Public Internet Traffic", "सार्वजनिक इंटरनेट ट्रैफिक"],
      ["Global HTTPS Load Balancer (WAF)", "ग्लोबल एचटीटीपीएस लोड बैलेन्सर (WAF)"],
      ["Cloud API Gateway", "क्लाउड एपीआई गेटवे"],
      ["Private Data/AI Subnet (Isolated)", "निजी डेटा/AI सबनेट (पृथक)"],
      ["Key Definitions", "मुख्य परिभाषाएं"],
      ["Managed Compute", "प्रबंधित कंप्यूट"],
      ["Control Flow Boundary", "नियंत्रण प्रवाह सीमा"],
      ["Data Boundaries", "डेटा सीमाएं"],
      ["Why It Works:", "यह क्यों प्रभावी है:"],
      ["WHY IT WORKS:", "यह कैसे काम करता है:"],
      ["(References Image 15 &amp; 3)", "(संदर्भ चित्र 15 एवं 3)"],
      ["(References Image 15 & 3)", "(संदर्भ चित्र 15 एवं 3)"],
      ["DATA VETTING", "डेटा सत्यापन"],
      ["CREATED (Model/Prompt)", "निर्मित (मॉडल/प्रॉम्प्ट)"],
      ["TRAINING (Retraining/Refinement Loop)", "प्रशिक्षण (पुनः प्रशिक्षण/परिष्करण लूप)"],
      ["EVALUATED", "मूल्यांकित"],
      ["Accuracy/F1", "सटीकता / F1 स्कोर"],
      ["Bias &amp; Fairness Audit", "पूर्वाग्रह एवं निष्पक्षता ऑडिट"],
      ["Bias & Fairness Audit", "पूर्वाग्रह एवं निष्पक्षता ऑडिट"],
      ["Human-in-the-Loop (Unified Governance Board)", "मानव-सत्यापन (एकीकृत शासन बोर्ड)"],
      ["APPROVED", "स्वीकृत एवं प्रमाणित"],
      ["GKE inference compute", "GKE अनुमान कंप्यूट"],
      ["Canary deployment on GKE", "GKE पर कैनेरी परिनियोजन"],
      ["Canary", "कैनेरी रिलीज़"],
      ["Promote", "उत्पादन प्रोन्नति"],
      ["Offline Metrics", "ऑफ़लाइन मेट्रिक्स"],
      ["Explicit rollback", "स्पष्ट रोलबैक"],
      ["Rollback Promotion", "रोलबैक प्रोन्नति"],
      ["Compliance", "अनुपालन"],
      ["Adversarial", "प्रतिकूल ऑडिट"],
      ["Bias", "पूर्वाग्रह"],
      ["Containers/Endpoints (via PSC)", "कंटेनर / एंडपॉइंट (PSC द्वारा)"],
      ["Tool 1: Enterprise Knowledge (Managed RAG)", "टूल 1: एंटरप्राइज़ ज्ञान (प्रबंधित RAG)"],
      ["Tool 2: Business Analytics (Analytics)", "टूल 2: बिजनेस एनालिटिक्स"],
      ["Tool 3: Agentic API Tools", "टूल 3: एजेंटिक एपीआई टूल"],
      ["Monitoring &amp; Observability", "निगरानी एवं अवलोकन योग्य तंत्र"],
      ["Monitoring & Observability", "निगरानी एवं अवलोकन योग्य तंत्र"],
      ["Drift Detection", "विचलन पहचान (Drift)"],
      ["ARCHIVAL (Retired Model/Prompt)", "संग्रहण (सेवानिवृत्त मॉडल/प्रॉम्प्ट)"],
      ["Incoming triggers", "आने वाले ट्रिगर्स"],
      ["Detailed role integration", "विस्तृत भूमिका एकीकरण"],
      ["Continuous Observation &amp; Alerting monitoring", "सतत अवलोकन एवं चेतावनी निगरानी"],
      ["Continuous Observation & Alerting monitoring", "सतत अवलोकन एवं चेतावनी निगरानी"],
      ["Inference drift", "अनुमान विचलन"],
      ["Prompt injection", "प्रॉम्प्ट इंजेक्शन संरक्षण"],
      ["Societal Changes", "सामाजिक परिवर्तन"],
      ["Regulatory Change", "विनियामक परिवर्तन"],
      ["Regulation", "विनिमय नियम"],
      ["Societal Drift", "सामाजिक विचलन"],
      ["Safety Incident", "सुरक्षा घटना"],
      ["Client Gateway", "क्लाइंट गेटवे"],
      ["Salesforce", "सेल्सफोर्स CRM"],
      ["Postgres", "पोस्टग्रेस डेटाबेस"],
      ["Cloud Run", "क्लाउड रन कंप्यूट"],
      ["Cloud SQL", "क्लाउड SQL"],
      ["BigQuery", "बिगक्वेरी डेटा वेयरहाउस"],
      ["Staging", "स्टेजिंग लेयर"],
      ["Transform", "रूपांतरण लेयर"],
      ["Dim_Customer_Entity", "Dim_Customer_Entity (ग्राहक तालिका)"],
      ["Fact_Clinical", "Fact_Clinical (क्लिनिकल फैक्ट तालिका)"],
      ["Derived", "व्युत्पन्न टेबल"],
      ["Raw Data", "कच्चा डेटा"],
      ["Access", "पहुँच नियंत्रण"],
      ["Outcomes", "परिणाम विश्लेषण"],
      ["Medical", "चिकित्सा रिकॉर्ड"],
      ["Competitive Intel", "प्रतिस्पर्धी बुद्धिमत्ता"],
      ["Clean", "डेटा सफाई"],
      ["Normalize", "सामान्यीकरण"],
      ["Aggregate", "समीकरण / एग्रीगेट"],
      ["Encode", "एनकोडिंग"],
      ["Feature Store", "फ़ीचर स्टोर"],
      ["Model Registry", "मॉडल रजिस्ट्री"],
      ["Key Description line types", "मुख्य विवरण रेखा प्रकार"],
      ["Line developmental relationships and monitoring elements", "रेखा विकास संबंध एवं निगरानी तत्व"]
    ],
    es: [
      ["UNIFIED SYSTEM VIEW", "VISTA DE SISEMA UNIFICADA"],
      ["PLAN & DATA FOUNDATION", "FUNDAMENTO DE PLANIFICACIÓN Y DATOS"],
      ["Project Planning", "Planificación de Proyecto"],
      ["Data Vetting", "Validación de Datos"],
      ["Dimensional Data Model", "Modelo de Datos Dimensional"],
      ["DATA ENGINEERING & DFD", "INGENIERÍA DE DATOS Y DFD"],
      ["FEATURE ENGINEERING FLOW", "FLUJO DE INGENIERÍA DE CARACTERÍSTICAS"],
      ["AI MODEL & PROMPT DEVELOPMENT LIFECYCLE", "CICLO DE VIDA DE DESARROLLO DE MODELOS IA"],
      ["Primary Governed VPC Network", "Red VPC Gobernada Principal"],
      ["Private Application Subnet", "Subred Privada de Aplicación"],
      ["Core Agent Orchestrator", "Orquestador Principal de Agentes"],
      ["Key Definitions", "Definiciones Clave"],
      ["Managed Compute", "Cómputo Administrado"],
      ["WHY IT WORKS:", "POR QUÉ FUNCIONA:"]
    ],
    pt: [
      ["UNIFIED SYSTEM VIEW", "VISÃO UNIFICADA DE SISTEMA"],
      ["PLAN & DATA FOUNDATION", "FUNDAÇÃO DE PLANEJAMENTO E DADOS"],
      ["Project Planning", "Planejamento de Projeto"],
      ["Data Vetting", "Validação de Dados"],
      ["Dimensional Data Model", "Modelo de Dados Dimensional"],
      ["DATA ENGINEERING & DFD", "ENGENHARIA DE DADOS E DFD"],
      ["FEATURE ENGINEERING FLOW", "FLUXO DE ENGENHARIA DE RECURSOS"],
      ["AI MODEL & PROMPT DEVELOPMENT LIFECYCLE", "CICLO DE VIDA DE DESENVOLVIMENTO DE IA"],
      ["Primary Governed VPC Network", "Rede VPC Governada Principal"],
      ["Private Application Subnet", "Sub-rede Privada de Aplicação"],
      ["Core Agent Orchestrator", "Orquestrador Principal de Agentes"],
      ["Key Definitions", "Definições Chave"],
      ["Managed Compute", "Computação Gerenciada"],
      ["WHY IT WORKS:", "POR QUE FUNCIONA:"]
    ],
    ja: [
      ["UNIFIED SYSTEM VIEW", "統合システム構成図"],
      ["PLAN & DATA FOUNDATION", "計画およびデータ基盤"],
      ["Project Planning", "プロジェクト計画"],
      ["Data Vetting", "データ検証"],
      ["Dimensional Data Model", "次元データモデル"],
      ["DATA ENGINEERING & DFD", "データエンジニアリングとDFD"],
      ["FEATURE ENGINEERING FLOW", "特徴量エンジニアリングフロー"],
      ["AI MODEL & PROMPT DEVELOPMENT LIFECYCLE", "AIモデルおよびプロンプト開発ライフサイクル"],
      ["Primary Governed VPC Network", "プライマリ制御VPCネットワーク"],
      ["Private Application Subnet", "プライベートアプリケーションサブネット"],
      ["Core Agent Orchestrator", "コアエージェントオーケストレーター"],
      ["Key Definitions", "主要な定義"],
      ["Managed Compute", "マネージドコンピュート"],
      ["WHY IT WORKS:", "推奨される理由:"]
    ],
    fr: [
      ["UNIFIED SYSTEM VIEW", "VUE SYSTÈME UNIFIÉE"],
      ["PLAN & DATA FOUNDATION", "FONDATION DE PLANIFICATION ET DONNÉES"],
      ["Project Planning", "Planification de Projet"],
      ["Data Vetting", "Validation des Données"],
      ["Dimensional Data Model", "Modèle de Données Dimensionnel"],
      ["DATA ENGINEERING & DFD", "INGÉNIERIE DES DONNÉES & DFD"],
      ["FEATURE ENGINEERING FLOW", "FLUX D'INGÉNIERIE DES FONCTIONNALITÉS"],
      ["AI MODEL & PROMPT DEVELOPMENT LIFECYCLE", "CYCLE DE DÉVELOPPEMENT DE MODÈLES IA"],
      ["Primary Governed VPC Network", "Réseau VPC Gouverné Principal"],
      ["Private Application Subnet", "Sous-réseau d'Application Privé"],
      ["Core Agent Orchestrator", "Orchestrateur d'Agent Principal"],
      ["Key Definitions", "Définitions Clés"],
      ["Managed Compute", "Calcul Géré"],
      ["WHY IT WORKS:", "POURQUOI CELA FONCTIONNE:"]
    ],
    de: [
      ["UNIFIED SYSTEM VIEW", "VEREINHEITLICHTE SYSTEMANSICHT"],
      ["PLAN & DATA FOUNDATION", "PLANUNG & DATENFUNDAMENT"],
      ["Project Planning", "Projektplanung"],
      ["Data Vetting", "Datenprüfung"],
      ["Dimensional Data Model", "Dimensionales Datenmodell"],
      ["DATA ENGINEERING & DFD", "DATENINGENIEURWESEN & DFD"],
      ["FEATURE ENGINEERING FLOW", "FEATURE-ENGINEERING-FLUSS"],
      ["AI MODEL & PROMPT DEVELOPMENT LIFECYCLE", "KI-MODELL- & PROMPT-ENTWICKLUNGSLEBENSZYKLUS"],
      ["Primary Governed VPC Network", "Primäres Verwaltetes VPC-Netzwerk"],
      ["Private Application Subnet", "Privates Anwendungs-Subnetz"],
      ["Core Agent Orchestrator", "Kern-Agenten-Orchester"],
      ["Key Definitions", "Wichtige Definitionen"],
      ["Managed Compute", "Verwaltete Rechenleistung"],
      ["WHY IT WORKS:", "WARUM ES FUNKTIONIERT:"]
    ],
    ar: [
      ["UNIFIED SYSTEM VIEW", "عرض النظام الموحد"],
      ["PLAN & DATA FOUNDATION", "أساس التخطيط والبيانات"],
      ["Project Planning", "تخطيط المشروع"],
      ["Data Vetting", "تدقيق البيانات"],
      ["Dimensional Data Model", "نموذج البيانات البعدي"],
      ["DATA ENGINEERING & DFD", "هندسة البيانات ومخطط تدفق البيانات"],
      ["FEATURE ENGINEERING FLOW", "مسار هندسة الميزات"],
      ["AI MODEL & PROMPT DEVELOPMENT LIFECYCLE", "دورة حياة تطوير نماذج الذكاء الاصطناعي"],
      ["Primary Governed VPC Network", "شبكة VPC الحاكمة الأساسية"],
      ["Private Application Subnet", "الشبكة الفرعية التطبيقية الخاصة"],
      ["Core Agent Orchestrator", "منسق الوكيل الأساسي"],
      ["Key Definitions", "التعاريف الرئيسية"],
      ["Managed Compute", "الحوسبة المدارة"],
      ["WHY IT WORKS:", "لماذا يعمل هذا النظام:"]
    ],
    zh: [
      ["UNIFIED SYSTEM VIEW", "统一系统架构视图"],
      ["PLAN & DATA FOUNDATION", "规划与数据基础设施"],
      ["Project Planning", "项目规划"],
      ["Data Vetting", "数据审核"],
      ["Dimensional Data Model", "多维数据模型"],
      ["DATA ENGINEERING & DFD", "数据工程与数据流图"],
      ["FEATURE ENGINEERING FLOW", "特征工程流程"],
      ["AI MODEL & PROMPT DEVELOPMENT LIFECYCLE", "AI模型与提示词开发生命周期"],
      ["Primary Governed VPC Network", "受控主VPC网络"],
      ["Private Application Subnet", "私有应用子网"],
      ["Core Agent Orchestrator", "核心智能体编排器"],
      ["Key Definitions", "核心定义"],
      ["Managed Compute", "托管计算"],
      ["WHY IT WORKS:", "核心架构优势:"]
    ],
    id: [
      ["UNIFIED SYSTEM VIEW", "TAMPILAN SISTEM TERPADU"],
      ["PLAN & DATA FOUNDATION", "PONDASI PERENCANAAN & DATA"],
      ["Project Planning", "Perencanaan Proyek"],
      ["Data Vetting", "Verifikasi Data"],
      ["Dimensional Data Model", "Model Data Dimensional"],
      ["DATA ENGINEERING & DFD", "REKAYASA DATA & DFD"],
      ["FEATURE ENGINEERING FLOW", "ALUR REKAYASA FITUR"],
      ["AI MODEL & PROMPT DEVELOPMENT LIFECYCLE", "SIKLUS HIDUP PENGEMBANGAN MODEL AI"],
      ["Primary Governed VPC Network", "Jaringan VPC Terkelola Utama"],
      ["Private Application Subnet", "Subnet Aplikasi Privat"],
      ["Core Agent Orchestrator", "Orkestrator Agen Utama"],
      ["Key Definitions", "Definisi Kunci"],
      ["Managed Compute", "Komputasi Terkelola"],
      ["WHY IT WORKS:", "MENGAPA INI EFEKTIF:"]
    ]
  };

  const replacements = multilangLexicon[lang] || [];
  let out = xml;
  for (const [from, to] of replacements) {
    out = out.split(from).join(to);
  }
  return out;
}
