/**
 * Machine-Readable Canonical Architecture Contracts for Templates 01–34
 * Enforces strict semantic boundaries, required elements, forbidden antipatterns,
 * edge types, L1/L2/L3 levels, and automated QA certification status.
 */

export interface CanonicalContract {
  id: string;
  grammar: string;
  family: 'Understand' | 'Process' | 'Structure' | 'Flow' | 'Infrastructure' | 'Security & Governance' | 'Delivery & Operations' | 'Analysis & Planning' | 'Reference Architectures';
  level: ('L1' | 'L2' | 'L3')[];
  semanticQuestion: string; // What core architecture question does this grammar answer?
  requiredElements: string[];
  forbiddenElements: string[];
  edgeTypes: string[];
  iconPolicy: 'semantic-vector' | 'authentic-brand' | 'hybrid';
  sourceImage: string;
  generatorVersion: string;
  certificationStatus: 'certified' | 'in_review' | 'pending';
}

export const CANONICAL_CONTRACTS: Record<string, CanonicalContract> = {
  '01': {
    id: '01',
    grammar: 'System Context',
    family: 'Understand',
    level: ['L1'],
    semanticQuestion: 'Who/what interacts with the system from the outside and why?',
    requiredElements: ['platform-boundary', 'internal-actors', 'external-partners', 'connected-systems', 'governance-enablers'],
    forbiddenElements: ['internal-microservices', 'database-schemas', 'container-runtimes'],
    edgeTypes: ['user-ingress', 'b2b-integration', 'governance-oversight'],
    iconPolicy: 'authentic-brand',
    sourceImage: '01.png',
    generatorVersion: '3.0',
    certificationStatus: 'certified'
  },
  '02': {
    id: '02',
    grammar: 'Capability Map',
    family: 'Understand',
    level: ['L1'],
    semanticQuestion: 'What business and technical capabilities does the organization/platform possess?',
    requiredElements: ['business-capabilities', 'ai-foundation', 'shared-services', 'governance-matrix'],
    forbiddenElements: ['temporal-sequence-flows', 'point-to-point-network-lines'],
    edgeTypes: [],
    iconPolicy: 'semantic-vector',
    sourceImage: '02.png',
    generatorVersion: '1.0',
    certificationStatus: 'in_review'
  },
  '03': {
    id: '03',
    grammar: 'Business Process / Swimlane',
    family: 'Process',
    level: ['L1', 'L2'],
    semanticQuestion: 'How do distinct roles and departments hand off activities and decisions over time?',
    requiredElements: ['department-swimlanes', 'activity-steps', 'decision-diamonds', 'audit-milestones'],
    forbiddenElements: ['infrastructure-subnets', 'hardware-servers'],
    edgeTypes: ['process-flow', 'handoff', 'exception-branch'],
    iconPolicy: 'semantic-vector',
    sourceImage: '03.png',
    generatorVersion: '1.0',
    certificationStatus: 'in_review'
  },
  '04': {
    id: '04',
    grammar: 'Value Stream',
    family: 'Understand',
    level: ['L1'],
    semanticQuestion: 'How is business value created end-to-end and where are the lead-time bottlenecks?',
    requiredElements: ['value-stages', 'key-activities', 'value-metrics', 'value-flow', 'delivered-outcomes'],
    forbiddenElements: ['class-hierarchies', 'low-level-api-endpoints'],
    edgeTypes: ['stage-progression', 'value-flow-arrow'],
    iconPolicy: 'semantic-vector',
    sourceImage: '04.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '05': {
    id: '05',
    grammar: 'As-Is / To-Be',
    family: 'Understand',
    level: ['L1'],
    semanticQuestion: 'What is the architectural delta between current legacy state and future target state?',
    requiredElements: ['as-is-column', 'transformation-bridge', 'to-be-column', 'business-roi'],
    forbiddenElements: ['unlabeled-transitions', 'mixed-state-entities'],
    edgeTypes: ['migration-arrow', 'modernization-bridge'],
    iconPolicy: 'semantic-vector',
    sourceImage: '05.png',
    generatorVersion: '1.0',
    certificationStatus: 'in_review'
  },
  '06': {
    id: '06',
    grammar: 'C4 Context',
    family: 'Structure',
    level: ['L1'],
    semanticQuestion: 'Strict C4 Level 1: People + Software System in Scope + External Systems with explicit labeled verbs.',
    requiredElements: ['software-system-in-scope', 'user-personas', 'external-software-systems', 'labeled-relationships'],
    forbiddenElements: ['internal-containers', 'code-classes', 'unlabeled-arrows'],
    edgeTypes: ['c4-uses-relationship', 'c4-delivers-relationship'],
    iconPolicy: 'semantic-vector',
    sourceImage: '06.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '07': {
    id: '07',
    grammar: 'C4 Container',
    family: 'Structure',
    level: ['L2'],
    semanticQuestion: 'Strict C4 Level 2: What high-level applications, microservices, databases, and file stores exist?',
    requiredElements: ['c4-containers', 'technology-labels', 'inter-container-protocols', 'external-systems'],
    forbiddenElements: ['low-level-methods', 'code-functions'],
    edgeTypes: ['http-rest', 'grpc', 'pubsub-event', 'sql-query'],
    iconPolicy: 'semantic-vector',
    sourceImage: '07.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '08': {
    id: '08',
    grammar: 'Component Architecture',
    family: 'Structure',
    level: ['L2', 'L3'],
    semanticQuestion: 'Strict C4 Level 3: What internal controllers, services, adapters, and repositories compose a container?',
    requiredElements: ['controllers', 'domain-services', 'adapters', 'repositories', 'interface-ports'],
    forbiddenElements: ['physical-cloud-vpcs', 'multi-region-dns'],
    edgeTypes: ['direct-call', 'interface-implementation', 'event-emission'],
    iconPolicy: 'semantic-vector',
    sourceImage: '08.png',
    generatorVersion: '1.0',
    certificationStatus: 'in_review'
  },
  '09': {
    id: '09',
    grammar: 'Data Flow Architecture',
    family: 'Flow',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'How does data move, transform, and settle across Bronze, Silver, and Gold lakehouse stages?',
    requiredElements: ['numbered-data-flows', 'data-stores', 'transformation-engines', 'serving-layers', 'feedback-loop'],
    forbiddenElements: ['user-auth-tokens', 'iam-role-hierarchies'],
    edgeTypes: ['data-ingestion', 'etl-transformation', 'cdc-stream', 'serving-query'],
    iconPolicy: 'semantic-vector',
    sourceImage: '09.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '10': {
    id: '10',
    grammar: 'Integration Architecture',
    family: 'Flow',
    level: ['L2'],
    semanticQuestion: 'How are disparate systems connected via API gateways, event brokers, and B2B protocols?',
    requiredElements: ['api-gateway-pillar', 'event-broker-pillar', 'data-connector-pillar', 'cross-cutting-services'],
    forbiddenElements: ['internal-database-tables', 'single-threaded-code'],
    edgeTypes: ['sync-rest', 'async-pubsub', 'batch-sftp', 'graphql'],
    iconPolicy: 'semantic-vector',
    sourceImage: '10.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '11': {
    id: '11',
    grammar: 'Sequence Diagram',
    family: 'Process',
    level: ['L2', 'L3'],
    semanticQuestion: 'What is the precise time-ordered message exchange between participants including alternative branches?',
    requiredElements: ['lifelines', 'activation-bars', 'sequential-step-numbers', 'alt-opt-enclaves', 'summary-table'],
    forbiddenElements: ['network-subnets', 'static-class-hierarchies'],
    edgeTypes: ['sync-call', 'async-message', 'return-response', 'self-call'],
    iconPolicy: 'semantic-vector',
    sourceImage: '11.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '12': {
    id: '12',
    grammar: 'State Machine',
    family: 'Process',
    level: ['L2', 'L3'],
    semanticQuestion: 'What discrete lifecycle states exist for an entity and what events/guards trigger transitions?',
    requiredElements: ['start-end-states', 'discrete-states', 'transition-events', 'guard-conditions', 'analytical-cards'],
    forbiddenElements: ['unbounded-infinite-loops', 'unlabeled-transitions'],
    edgeTypes: ['state-transition', 'error-fallback-transition'],
    iconPolicy: 'semantic-vector',
    sourceImage: '12.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '13': {
    id: '13',
    grammar: 'Decision Flow / Tree',
    family: 'Process',
    level: ['L1', 'L2'],
    semanticQuestion: 'What conditional business rules, safety filters, and algorithmic criteria determine an outcome?',
    requiredElements: ['multi-stage-gates', 'decision-diamonds', 'yes-no-branches', 'audit-trail-logging'],
    forbiddenElements: ['class-inheritance-hierarchies'],
    edgeTypes: ['branch-yes', 'branch-no', 'escalation-route'],
    iconPolicy: 'semantic-vector',
    sourceImage: '13.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '14': {
    id: '14',
    grammar: 'Data Model / ERD',
    family: 'Structure',
    level: ['L2', 'L3'],
    semanticQuestion: 'What are the database entities, attributes, primary/foreign keys, and relational cardinalities?',
    requiredElements: ['entity-boxes', 'primary-keys', 'foreign-keys', 'crows-foot-relationships', 'domain-clusters'],
    forbiddenElements: ['api-endpoints', 'cloud-load-balancers'],
    edgeTypes: ['one-to-many', 'many-to-many', 'one-to-one'],
    iconPolicy: 'semantic-vector',
    sourceImage: '14.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '15': {
    id: '15',
    grammar: 'Network Topology',
    family: 'Infrastructure',
    level: ['L2', 'L3'],
    semanticQuestion: 'How are VPCs, subnets, CIDR ranges, route tables, and private service connections physically wired?',
    requiredElements: ['public-dmz', 'multi-az-private-subnets', 'data-subnets', 'managed-service-bus', 'nat-gateway'],
    forbiddenElements: ['unlabeled-subnets', 'direct-public-db-access'],
    edgeTypes: ['vpc-peering', 'psc-endpoint', 'internal-routing', 'egress-nat'],
    iconPolicy: 'semantic-vector',
    sourceImage: '15.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '16': {
    id: '16',
    grammar: 'Deployment Architecture',
    family: 'Infrastructure',
    level: ['L2', 'L3'],
    semanticQuestion: 'Where are application workloads physically scheduled across cloud regions, clusters, and runtimes?',
    requiredElements: ['global-lb', 'primary-region-multi-az', 'dr-region-standby', 'regional-data-tier', 'env-strategy'],
    forbiddenElements: ['unbounded-unhosted-workloads'],
    edgeTypes: ['anycast-ingress', 'internal-lb-routing', 'cross-region-replication'],
    iconPolicy: 'semantic-vector',
    sourceImage: '16.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '17': {
    id: '17',
    grammar: 'Identity & Access Flow',
    family: 'Security & Governance',
    level: ['L2', 'L3'],
    semanticQuestion: 'How do users and services authenticate, federate tokens, and obtain least-privilege authorizations?',
    requiredElements: ['identity-providers', 'token-exchange-service', 'iam-least-privilege-pyramid', 'audit-logging'],
    forbiddenElements: ['unauthenticated-access-paths'],
    edgeTypes: ['oidc-auth', 'token-minting', 'saml-federation', 'rbac-enforcement'],
    iconPolicy: 'semantic-vector',
    sourceImage: '17.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '18': {
    id: '18',
    grammar: 'Security / Trust Boundary',
    family: 'Security & Governance',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'What are the explicit network perimeters, encryption zones, and data classification levels?',
    requiredElements: ['trust-boundary-boxes', 'edge-perimeter', 'application-zone', 'data-zone', 'data-classification'],
    forbiddenElements: ['unlabeled-cross-boundary-flow'],
    edgeTypes: ['trusted-data-flow', 'admin-control-flow', 'classification-crossing'],
    iconPolicy: 'semantic-vector',
    sourceImage: '18.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '19': {
    id: '19',
    grammar: 'HA / DR Architecture',
    family: 'Infrastructure',
    level: ['L2', 'L3'],
    semanticQuestion: 'How does the system survive regional disasters with automated failover and defined RTO/RPO?',
    requiredElements: ['primary-active-region', 'secondary-standby-region', 'replication-buses', 'failover-sequence'],
    forbiddenElements: ['single-point-of-failure-data'],
    edgeTypes: ['async-replication', 'sync-replication', 'health-check-probe', 'failover-route'],
    iconPolicy: 'semantic-vector',
    sourceImage: '19.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '20': {
    id: '20',
    grammar: 'CI/CD Pipeline',
    family: 'Delivery & Operations',
    level: ['L2', 'L3'],
    semanticQuestion: 'How is code securely built, tested, scanned, and progressively deployed across environments?',
    requiredElements: ['commit-triggers', 'build-test-stages', 'security-gates', 'deployment-patterns', 'rollback-plan'],
    forbiddenElements: ['manual-untested-prod-deploy'],
    edgeTypes: ['pipeline-stage-transition', 'quality-gate-pass', 'rollback-branch'],
    iconPolicy: 'semantic-vector',
    sourceImage: '20.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '21': {
    id: '21',
    grammar: 'Observability / SRE',
    family: 'Delivery & Operations',
    level: ['L2', 'L3'],
    semanticQuestion: 'How are metrics, logs, and traces collected, aggregated, and mapped to SLO alerts?',
    requiredElements: ['telemetry-sources', 'metrics-logs-traces-pillars', 'ingestion-pipeline', 'slo-alerting'],
    forbiddenElements: ['unmonitored-production-services'],
    edgeTypes: ['telemetry-stream', 'alert-trigger', 'dashboard-query'],
    iconPolicy: 'semantic-vector',
    sourceImage: '21.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '22': {
    id: '22',
    grammar: 'Migration / Transition',
    family: 'Delivery & Operations',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'What is the phase-by-phase migration journey of workloads using 6-Rs modernization patterns?',
    requiredElements: ['as-is-state', 'migration-phases', 'to-be-state', 'coexistence-bridge', 'six-rs-patterns'],
    forbiddenElements: ['big-bang-unmitigated-switchover'],
    edgeTypes: ['phase-progression', 'data-sync-bridge'],
    iconPolicy: 'semantic-vector',
    sourceImage: '22.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '23': {
    id: '23',
    grammar: 'Agent Interaction Architecture',
    family: 'Flow',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'How do specialized AI agents decompose goals, delegate tasks, invoke tools, and share memory?',
    requiredElements: ['supervisor-agent', 'specialized-subagents', 'tool-execution-layer', 'shared-memory-store'],
    forbiddenElements: ['unbounded-agent-loops', 'unmonitored-autonomous-execution'],
    edgeTypes: ['goal-delegation', 'tool-invocation', 'memory-read-write', 'synthesis-return'],
    iconPolicy: 'semantic-vector',
    sourceImage: '23.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '24': {
    id: '24',
    grammar: 'RAG / Knowledge Flow',
    family: 'Flow',
    level: ['L2', 'L3'],
    semanticQuestion: 'How is unstructured knowledge ingested, embedded, retrieved via hybrid search, and grounded into LLM prompts?',
    requiredElements: ['ingestion-chunking-path', 'vector-graph-indices', 'hybrid-retriever', 'reranker', 'llm-synthesis'],
    forbiddenElements: ['ungrounded-hallucinated-synthesis'],
    edgeTypes: ['document-ingest', 'embedding-generation', 'similarity-query', 'prompt-grounding'],
    iconPolicy: 'semantic-vector',
    sourceImage: '24.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '25': {
    id: '25',
    grammar: 'Tool / Protocol Interaction',
    family: 'Flow',
    level: ['L2', 'L3'],
    semanticQuestion: 'What are the exact JSON-RPC, MCP, A2A, and OpenAPI transport protocols connecting models to tools?',
    requiredElements: ['mcp-host-client', 'mcp-server', 'protocol-layers', 'tool-catalogs', 'sandbox-isolation'],
    forbiddenElements: ['unauthenticated-arbitrary-command-execution'],
    edgeTypes: ['mcp-jsonrpc-call', 'a2a-handshake', 'openapi-request'],
    iconPolicy: 'semantic-vector',
    sourceImage: '25.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '26': {
    id: '26',
    grammar: 'HITL / Governance Flow',
    family: 'Security & Governance',
    level: ['L1', 'L2'],
    semanticQuestion: 'When and how must human experts review, approve, override, or audit automated AI outputs?',
    requiredElements: ['confidence-threshold-eval', 'human-review-cockpit', 'escalation-queue', 'immutable-audit-log'],
    forbiddenElements: ['unsupervised-critical-action-execution'],
    edgeTypes: ['auto-approve-route', 'human-review-route', 'dual-signature-signoff'],
    iconPolicy: 'semantic-vector',
    sourceImage: '26.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '27': {
    id: '27',
    grammar: 'Threat Model Architecture',
    family: 'Security & Governance',
    level: ['L2', 'L3'],
    semanticQuestion: 'What are the STRIDE threats across all 11 attack surfaces and how are they specifically mitigated?',
    requiredElements: ['trust-zones', 'attack-surface-map', 'stride-catalog-table', 'threat-scenarios-table', 'incident-response-flow'],
    forbiddenElements: ['unmitigated-critical-threats'],
    edgeTypes: ['data-flow', 'trust-boundary-crossing', 'attack-vector'],
    iconPolicy: 'semantic-vector',
    sourceImage: '27.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '28': {
    id: '28',
    grammar: 'Failure / Exception Flow',
    family: 'Delivery & Operations',
    level: ['L2', 'L3'],
    semanticQuestion: 'What happens when a service, worker, or model fails: retry policies, circuit breaking, DLQ, and fallback?',
    requiredElements: ['failure-sources', 'retry-exponential-backoff', 'circuit-breaker', 'dead-letter-queue', 'escalation-runbook'],
    forbiddenElements: ['silent-dropped-exceptions'],
    edgeTypes: ['primary-flow', 'retry-loop', 'dlq-routing', 'fallback-execution'],
    iconPolicy: 'semantic-vector',
    sourceImage: '28.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '29': {
    id: '29',
    grammar: 'Cutover / Operational Runbook',
    family: 'Delivery & Operations',
    level: ['L3'],
    semanticQuestion: 'What is the minute-by-minute execution timeline, owner RACI, verification checks, and rollback procedure for go-live?',
    requiredElements: ['timeline-phases', 'minute-by-minute-tasks', 'go-no-go-gates', 'rollback-procedure', 'war-room-raci'],
    forbiddenElements: ['unverified-untested-cutover'],
    edgeTypes: ['sequential-step-dependency', 'gate-approval', 'rollback-trigger'],
    iconPolicy: 'semantic-vector',
    sourceImage: '29.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '30': {
    id: '30',
    grammar: 'FinOps / Cost Flow',
    family: 'Delivery & Operations',
    level: ['L1', 'L2'],
    semanticQuestion: 'How are cloud and AI token costs ingested, attributed across business units, and continuously optimized?',
    requiredElements: ['cost-ingestion-sources', 'attribution-allocation-engine', 'showback-chargeback-views', 'anomaly-detection-alerts'],
    forbiddenElements: ['unallocated-black-box-cloud-spend'],
    edgeTypes: ['billing-data-ingest', 'cost-allocation-flow', 'optimization-recommendation'],
    iconPolicy: 'semantic-vector',
    sourceImage: '30.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '31': {
    id: '31',
    grammar: 'Dependency / Relationship Map',
    family: 'Analysis & Planning',
    level: ['L2'],
    semanticQuestion: 'What are the cross-tier many-to-many dependencies between users, applications, data, and platform integrations?',
    requiredElements: ['user-tier', 'application-tier', 'data-tier', 'integration-tier', 'platform-tier', 'orthogonal-dependency-edges'],
    forbiddenElements: ['circular-hidden-dependencies'],
    edgeTypes: ['sync-dependency', 'async-dependency', 'data-dependency', 'platform-dependency'],
    iconPolicy: 'semantic-vector',
    sourceImage: '31.png',
    generatorVersion: '1.2',
    certificationStatus: 'certified'
  },
  '32': {
    id: '32',
    grammar: 'Architecture Evolution & Roadmap',
    family: 'Analysis & Planning',
    level: ['L1', 'L2'],
    semanticQuestion: 'How does the architecture evolve across Foundation, Scale, Intelligent, and Autonomous multi-year phases?',
    requiredElements: ['time-horizons', 'architecture-pillars', 'maturity-milestones', 'technology-transitions'],
    forbiddenElements: ['unanchored-timelines'],
    edgeTypes: ['evolution-progression-arrow', 'dependency-link'],
    iconPolicy: 'semantic-vector',
    sourceImage: '32.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '33': {
    id: '33',
    grammar: 'Architecture Matrix Heatmap',
    family: 'Analysis & Planning',
    level: ['L1', 'L2'],
    semanticQuestion: 'How do multiple architectural options or candidate tools score across weighted functional and non-functional criteria?',
    requiredElements: ['evaluation-criteria-rows', 'candidate-option-columns', 'weighted-scores-legend', 'recommendation-summary'],
    forbiddenElements: ['unweighted-arbitrary-scoring'],
    edgeTypes: [],
    iconPolicy: 'semantic-vector',
    sourceImage: '33.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '34': {
    id: '34',
    grammar: 'Geographic / Regional Architecture',
    family: 'Infrastructure',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'How are sovereign cloud boundaries, regional deployments, edge points of presence, and cross-border data replication managed?',
    requiredElements: ['global-user-edge', 'regional-sovereign-enclaves', 'cross-region-replication-backbone', 'compliance-residency-tags'],
    forbiddenElements: ['cross-border-unauthorized-phi-transfer'],
    edgeTypes: ['edge-anycast-routing', 'cross-region-interconnect', 'sovereign-audit-stream'],
    iconPolicy: 'semantic-vector',
    sourceImage: '34.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '35': {
    id: '35',
    grammar: 'FinTech & Autonomous Wealth Engine',
    family: 'Reference Architectures',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'How does an autonomous wealth management platform coordinate AI agents, trading execution, and institutional trust?',
    requiredElements: ['channels-experience', 'identity-onboarding-trust', 'core-wealth-platform', 'autonomous-ai-agents', 'trading-external-market', 'data-intelligence-layer', 'risk-compliance-governance', 'platform-devsecops', 'security-reliability-foundation'],
    forbiddenElements: ['unregulated-direct-market-access', 'untraceable-rebalancing'],
    edgeTypes: ['onboarding-flow', 'data-flow', 'ai-decision-flow', 'order-execution-flow', 'compliance-review-flow', 'event-streaming-flow'],
    iconPolicy: 'hybrid',
    sourceImage: '35.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '36': {
    id: '36',
    grammar: 'Smart Manufacturing & Industrial IoT',
    family: 'Reference Architectures',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'How does plant floor OT telemetry integrate with cloud AI, MES/MOM, and enterprise ERP for intelligent manufacturing?',
    requiredElements: ['shop-floor-ot-channels', 'edge-control-site-ops', 'manufacturing-operations-mes', 'ai-optimization-layer', 'enterprise-ecosystem-erp', 'data-industrial-intelligence', 'risk-safety-compliance', 'platform-devops-mlops', 'security-reliability-foundation'],
    forbiddenElements: ['unbuffered-edge-telemetry', 'uncontrolled-cloud-to-actuator-commands'],
    edgeTypes: ['telemetry-data-flow', 'command-control-flow', 'ai-optimization-flow', 'enterprise-integration-flow', 'compliance-flow', 'event-streaming-flow'],
    iconPolicy: 'hybrid',
    sourceImage: '36.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '37': {
    id: '37',
    grammar: 'Dedicated Network & Infrastructure Blueprint',
    family: 'Reference Architectures',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'How is a zero-trust hybrid cloud network architected with Shared VPC, Private Service Connect, and strict egress inspection?',
    requiredElements: ['external-users-partners', 'hybrid-connectivity-edge', 'private-ingress-layer', 'hub-and-spoke-shared-vpc', 'application-service-layer', 'private-service-connect-psc', 'private-egress-outbound-controls', 'data-platform-shared-controls', 'security-operations-foundation'],
    forbiddenElements: ['direct-public-ip-workloads', 'unmonitored-egress-channels'],
    edgeTypes: ['private-data-flow', 'control-mgmt-flow', 'internet-public-flow', 'psc-connectivity-flow', 'hybrid-connectivity-flow'],
    iconPolicy: 'hybrid',
    sourceImage: '37.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '38': {
    id: '38',
    grammar: 'Cloud Landing Zone & Enterprise Shared Services',
    family: 'Reference Architectures',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'How does an enterprise structure multi-tenant cloud organization hierarchy, landing zone networking, shared services, and FinOps guardrails?',
    requiredElements: ['enterprise-business-units', 'organization-structure-hierarchy', 'identity-access-admin', 'core-landing-zone-network', 'enterprise-shared-services-platform', 'security-risk-compliance', 'data-integration-ai-shared', 'reliability-dr-platform-ops', 'finops-billing-chargeback'],
    forbiddenElements: ['flat-unstructured-cloud-accounts', 'unbounded-admin-privilege'],
    edgeTypes: ['private-data-flow', 'control-mgmt-flow', 'public-flow', 'hybrid-flow', 'policy-guardrails'],
    iconPolicy: 'hybrid',
    sourceImage: '38.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  },
  '39': {
    id: '39',
    grammar: 'Sovereign Cloud & Data Privacy Blueprint',
    family: 'Reference Architectures',
    level: ['L1', 'L2', 'L3'],
    semanticQuestion: 'How is national and regional data sovereignty enforced with in-country isolation, automated residency enforcement, and privacy controls?',
    requiredElements: ['governance-sovereign-oversight', 'stakeholders-access-gate', 'sovereign-cloud-environment', 'data-classification-residency', 'privacy-security-controls', 'infrastructure-sovereignty', 'data-exchange-controls', 'monitoring-audit-assurance', 'compliance-frameworks', 'key-principles'],
    forbiddenElements: ['unauthorized-cross-border-copy', 'unclassified-data-stores'],
    edgeTypes: ['data-flow', 'control-governance-flow', 'audit-monitoring-flow'],
    iconPolicy: 'hybrid',
    sourceImage: '39.png',
    generatorVersion: '1.0',
    certificationStatus: 'certified'
  }
};
