/**
 * Draw.io XML to 100% Native Editable Word (.docx) & Google Docs Specification Compiler
 * Generates a rich .docx document that can be opened in Microsoft Word or uploaded to Google Drive
 * ("Open with Google Docs") where all headings, component tables, data flow matrices, and architecture
 * descriptions are 100% native editable text & tables, paired with the high-resolution diagram.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  HeadingLevel,
  AlignmentType,
  ImageRun,
} from 'docx';
import { parseDrawioXmlForPptx } from './editablePptxCompiler';
import { exportDiagramPng } from './diagramRaster';

function stripHtmlForDocx(html: string): { title: string; details: string } {
  if (!html) return { title: '', details: '' };
  const decoded = html
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ');
  const noSvg = decoded.replace(/<svg[\s\S]*?<\/svg>/gi, '');
  const lines = noSvg
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/div>/gi, '\n')
    .replace(/<\/p>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
  return {
    title: lines[0] || '',
    details: lines.slice(1).join(' • ') || 'Enterprise Cloud Node',
  };
}

function dataUrlToUint8Array(dataUrl: string): Uint8Array | null {
  try {
    const base64Index = dataUrl.indexOf(';base64,');
    if (base64Index === -1) return null;
    const base64 = dataUrl.substring(base64Index + 8);
    const binaryString = window.atob(base64);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes;
  } catch (e) {
    console.warn('Failed to convert image dataUrl for docx:', e);
    return null;
  }
}

export async function exportDrawioToEditableDocx(
  xmlContent: string,
  diagramName: string = 'Architecture Blueprint',
  blueprintId: string = 'VIS-MASTER',
  options?: { returnBlob?: boolean }
): Promise<Blob | void> {
  const { cells } = parseDrawioXmlForPptx(xmlContent);
  const vertices = cells.filter((c) => c.vertex && stripHtmlForDocx(c.value).title.length > 0);
  const edges = cells.filter((c) => c.edge);

  const cellTitleMap = new Map<string, string>();
  vertices.forEach((v) => {
    cellTitleMap.set(v.id, stripHtmlForDocx(v.value).title);
  });

  // Rasterize high-res PNG for embedding inside Google Docs / Word
  let imageBytes: Uint8Array | null = null;
  try {
    const pngDataUrl = await exportDiagramPng(xmlContent, { scale: 2, transparent: false });
    if (pngDataUrl) {
      imageBytes = dataUrlToUint8Array(pngDataUrl);
    }
  } catch (err) {
    console.warn('Docx diagram image embed skipped:', err);
  }

  const children: any[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [
        new TextRun({
          text: `${diagramName} — Architecture Specification & Blueprint`,
          bold: true,
          size: 36,
          color: '0F172A',
          font: 'Arial',
        }),
      ],
      spacing: { after: 120 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Blueprint ID: ${blueprintId}  |  Generated by PromptCanvas Vision Engine  |  Date: ${new Date().toLocaleDateString()}`,
          size: 20,
          color: '475569',
          font: 'Arial',
        }),
      ],
      spacing: { after: 240 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: 'Google Docs & Microsoft Word Editability Guide: ',
          bold: true,
          size: 20,
          color: '0284C7',
          font: 'Arial',
        }),
        new TextRun({
          text: 'Every section, heading, component specification table, and integration matrix in this document is 100% natively editable in Google Docs (Upload to Google Drive -> Open with Google Docs) or Microsoft Word. To edit individual diagram vector boxes directly in Google Slides, use the companion "Export PPTX (Editable Slides)" button.',
          size: 20,
          color: '334155',
          font: 'Arial',
        }),
      ],
      spacing: { after: 300 },
    }),
  ];

  // Embed High-Res Diagram Image if available
  if (imageBytes) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [
          new TextRun({
            text: '1. Visual System Architecture Topology',
            bold: true,
            size: 28,
            color: '0F172A',
            font: 'Arial',
          }),
        ],
        spacing: { before: 200, after: 160 },
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new ImageRun({
            data: imageBytes,
            transformation: {
              width: 620,
              height: 350,
            },
            type: 'png',
          }),
        ],
        spacing: { after: 300 },
      })
    );
  }

  // Section 2: Editable Component Inventory Table
  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [
        new TextRun({
          text: `2. Architectural Component Inventory (${vertices.length} Addressable Objects)`,
          bold: true,
          size: 28,
          color: '0F172A',
          font: 'Arial',
        }),
      ],
      spacing: { before: 240, after: 160 },
    })
  );

  const componentRows: TableRow[] = [
    new TableRow({
      tableHeader: true,
      children: ['Object ID', 'Component / Enclave Name', 'Category / Role', 'Specifications & Attributes'].map(
        (headerText) =>
          new TableCell({
            shading: { fill: '0F172A' },
            children: [
              new Paragraph({
                children: [new TextRun({ text: headerText, bold: true, color: 'FFFFFF', size: 18, font: 'Arial' })],
              }),
            ],
          })
      ),
    }),
  ];

  vertices.forEach((v, idx) => {
    const { title, details } = stripHtmlForDocx(v.value);
    const isContainer = v.style.container === '1' || v.width * v.height > 90000;
    const objId = `OBJ-${String(idx + 1).padStart(2, '0')}`;

    componentRows.push(
      new TableRow({
        children: [
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: objId, bold: true, color: '0284C7', size: 18, font: 'Arial' })],
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: title, bold: true, color: '0F172A', size: 18, font: 'Arial' })],
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: isContainer ? 'Architectural Enclave / Tier' : 'Service Node / Component',
                    color: '475569',
                    size: 18,
                    font: 'Arial',
                  }),
                ],
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: details, color: '334155', size: 18, font: 'Arial' })],
              }),
            ],
          }),
        ],
      })
    );
  });

  children.push(
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: componentRows,
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
        left: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
        right: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
        insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0' },
        insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0' },
      },
    })
  );

  // Section 3: Editable Data Flow & Integration Matrix Table
  if (edges.length > 0) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [
          new TextRun({
            text: `3. Data Flow & Protocol Integration Matrix (${edges.length} Connectors)`,
            bold: true,
            size: 28,
            color: '0F172A',
            font: 'Arial',
          }),
        ],
        spacing: { before: 300, after: 160 },
      })
    );

    const edgeRows: TableRow[] = [
      new TableRow({
        tableHeader: true,
        children: ['Connector ID', 'Source Component', 'Target Component', 'Protocol / Label'].map(
          (headerText) =>
            new TableCell({
              shading: { fill: '0F172A' },
              children: [
                new Paragraph({
                  children: [new TextRun({ text: headerText, bold: true, color: 'FFFFFF', size: 18, font: 'Arial' })],
                }),
              ],
            })
        ),
      }),
    ];

    edges.forEach((edge, idx) => {
      const srcTitle = (edge.source && cellTitleMap.get(edge.source)) || edge.source || 'Source System';
      const tgtTitle = (edge.target && cellTitleMap.get(edge.target)) || edge.target || 'Target System';
      const label = stripHtmlForDocx(edge.value).title || 'Direct Architecture Link';

      edgeRows.push(
        new TableRow({
          children: [
            new TableCell({
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: `FLOW-${String(idx + 1).padStart(2, '0')}`,
                      bold: true,
                      color: '0D9488',
                      size: 18,
                      font: 'Arial',
                    }),
                  ],
                }),
              ],
            }),
            new TableCell({
              children: [
                new Paragraph({
                  children: [new TextRun({ text: srcTitle, bold: true, color: '0F172A', size: 18, font: 'Arial' })],
                }),
              ],
            }),
            new TableCell({
              children: [
                new Paragraph({
                  children: [new TextRun({ text: tgtTitle, bold: true, color: '0F172A', size: 18, font: 'Arial' })],
                }),
              ],
            }),
            new TableCell({
              children: [
                new Paragraph({
                  children: [new TextRun({ text: label, color: '334155', size: 18, font: 'Arial' })],
                }),
              ],
            }),
          ],
        })
      );
    });

    children.push(
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: edgeRows,
        borders: {
          top: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
          bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
          left: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
          right: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
          insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0' },
          insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0' },
        },
      })
    );
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  if (options?.returnBlob) {
    return blob;
  }

  const safeName = diagramName.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${safeName || 'architecture'}_editable_google_docs.docx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
