'use client';

import React, { useState } from 'react';
import {
  Share2,
  Copy,
  Check,
  Send,
  ExternalLink,
  CheckCircle2,
  FileText,
  Boxes,
  X,
  Code,
  Sparkles,
  Layers
} from 'lucide-react';

interface EnterpriseSyncModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectTitle: string;
  docArchetype: string;
  docMarkdown?: string;
  isLight: boolean;
}

export default function EnterpriseSyncModal({
  isOpen,
  onClose,
  projectTitle,
  docArchetype,
  docMarkdown = '',
  isLight,
}: EnterpriseSyncModalProps) {
  const [activeTab, setActiveTab] = useState<'jira' | 'confluence' | 'github' | 'webhook'>('jira');
  const [webhookUrl, setWebhookUrl] = useState<string>('https://hooks.slack.com/services/... or https://jira.enterprise.com/webhook');
  const [isSendingWebhook, setIsSendingWebhook] = useState<boolean>(false);
  const [webhookSuccess, setWebhookSuccess] = useState<boolean>(false);
  const [copiedSuccess, setCopiedSuccess] = useState<boolean>(false);

  if (!isOpen) return null;

  // Generate Jira Epics & User Stories payload
  const jiraPayload = `
h1. [EPIC] ${projectTitle} (${docArchetype.toUpperCase()} Implementation)
*Target Milestone:* Q4 Production Release
*Architecture Standard:* ${docArchetype.toUpperCase()} Certified Spec

h2. Core Epics & Stories
|| Issue Type || Summary || Priority || Story Points || Acceptance Criteria ||
| Story | Ingest & API Gateway Setup | High | 5 | Envoy Gateway routes configured with JWT validation |
| Story | Microservice Mesh & gRPC Orchestration | High | 8 | Stateless pods pass health checks & retry loops |
| Story | Spanner / PostgreSQL Schema & ACID Ledgers | Critical | 8 | DDL applied with multi-region replication |
| Story | Security & Zero-Trust VPC SC Perimeters | Critical | 5 | CMEK keys rotated & L7 WAF active |
| Story | Disaster Recovery & Failover Automation | High | 5 | RTO < 30s verified via Chaos injection |
| Story | GxP / SOC 2 Compliance Audit Trail | Medium | 3 | Immutable audit log verified by QA |
`;

  // Generate Confluence wiki format
  const confluencePayload = `
h1. ${projectTitle} - Architecture Specification
*Document Type:* ${docArchetype.toUpperCase()} Master Blueprint
*Status:* APPROVED BY ARCHITECTURE REVIEW BOARD (ARB)
*Generated by:* PromptCanvas Architecture Engine

----

h2. 1. Executive Summary & Problem Vision
This document defines the formal system architecture and operational topology for *${projectTitle}*.

h2. 2. Architectural Blueprint & C4 Components
{code:title=Architecture Specification|theme=Midnight}
${docMarkdown.slice(0, 1200)}...
{code}

h2. 3. Compliance & Sign-Off Matrix
|| Role || Name || Sign-off Date || Status ||
| Chief Architect | ARB Lead | Current | (/) APPROVED |
| Security Officer | CISO Team | Current | (/) APPROVED |
| SRE Lead | Ops Team | Current | (/) APPROVED |
`;

  // Generate GitHub PRD Issue template
  const githubPayload = `---
name: "${docArchetype.toUpperCase()}: ${projectTitle}"
about: Formal architecture and product implementation issue
title: "[ARCH] ${projectTitle}"
labels: ["architecture", "spec", "${docArchetype.toLowerCase()}"]
assignees: []
---

## 🎯 System Objective
Implementation of **${projectTitle}** conforming to the certified **${docArchetype.toUpperCase()}** specification.

## 📋 Implementation Checklist
- [ ] Deploy Terraform IaC foundation (\`main.tf\`, VPC SC, Subnets)
- [ ] Configure Ingress Envoy Gateway with Cloud Armor WAF
- [ ] Deploy Stateless Kubernetes Microservices
- [ ] Provision Multi-Region Cloud Spanner Database & Schema
- [ ] Implement OpenTelemetry distributed tracing & PagerDuty alerts
- [ ] Run Chaos Engineering Zone Evacuation drill (RTO < 30s)
- [ ] Obtain Final ARB & GRC compliance sign-off
`;

  const getActivePayload = () => {
    switch (activeTab) {
      case 'jira': return jiraPayload;
      case 'confluence': return confluencePayload;
      case 'github': return githubPayload;
      case 'webhook': return JSON.stringify({
        project: projectTitle,
        archetype: docArchetype,
        timestamp: new Date().toISOString(),
        status: 'READY_FOR_DEPLOYMENT',
        specMarkdownSummary: docMarkdown.slice(0, 500) + '...',
      }, null, 2);
      default: return jiraPayload;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActivePayload());
    setCopiedSuccess(true);
    setTimeout(() => setCopiedSuccess(false), 2000);
  };

  const handleDispatchWebhook = async () => {
    setIsSendingWebhook(true);
    // Simulate webhook POST dispatch
    setTimeout(() => {
      setIsSendingWebhook(false);
      setWebhookSuccess(true);
      setTimeout(() => setWebhookSuccess(false), 3000);
    }, 800);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 bg-slate-950/85 backdrop-blur-md animate-fadeIn">
      <div className={`relative w-full max-w-5xl max-h-[92vh] flex flex-col rounded-3xl border shadow-2xl overflow-hidden ${
        isLight ? 'bg-white border-slate-300 text-slate-900' : 'bg-[#070A13] border-slate-800 text-white'
      }`}>
        
        {/* HEADER */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-950/80 backdrop-blur-md">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-sky-600 via-indigo-600 to-cyan-500 text-white flex items-center justify-center shadow-md">
              <Share2 className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-black truncate max-w-md">
                  Enterprise Webhook &amp; Toolchain Sync
                </h3>
                <span className="text-[10px] font-mono font-bold uppercase px-2 py-0.5 rounded-full bg-sky-500/15 text-sky-600 dark:text-sky-400 border border-sky-500/30">
                  Jira &bull; Confluence &bull; GitHub
                </span>
              </div>
              <p className="text-xs text-slate-400">
                1-Click Export to Jira Backlogs, Confluence Spaces, and GitHub PRD Issue Templates
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl text-xs font-bold bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 transition-colors"
            >
              {copiedSuccess ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedSuccess ? 'Copied' : 'Copy'}</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-rose-500/20 hover:text-rose-500 text-slate-600 dark:text-slate-300 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* TABS */}
        <div className="flex items-center gap-1 px-6 py-2.5 border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/60 overflow-x-auto text-xs font-bold">
          {[
            { id: 'jira', label: 'Jira Epics & Stories', icon: Boxes },
            { id: 'confluence', label: 'Confluence Wiki Page', icon: FileText },
            { id: 'github', label: 'GitHub PRD Issues', icon: Code },
            { id: 'webhook', label: 'Custom Webhook Dispatcher', icon: Send },
          ].map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl transition-all ${
                  isActive
                    ? 'bg-sky-600 text-white shadow-sm'
                    : 'text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* BODY */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          {activeTab === 'webhook' ? (
            <div className="space-y-4">
              <div className="p-4 rounded-2xl bg-sky-500/10 border border-sky-500/20 text-xs text-sky-600 dark:text-sky-400 space-y-1">
                <div className="font-bold flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4" /> Real-Time Enterprise Webhook Dispatcher
                </div>
                <p>
                  Dispatch structured JSON architecture payloads directly to Slack, Jira Automation, Microsoft Teams, or custom internal deployment pipelines.
                </p>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-400 block mb-1.5">
                  Destination Webhook URL:
                </label>
                <input
                  type="text"
                  value={webhookUrl}
                  onChange={(e) => setWebhookUrl(e.target.value)}
                  className={`w-full px-3 py-2 rounded-xl border text-xs font-mono outline-none ${
                    isLight ? 'bg-white border-slate-300 text-slate-900' : 'bg-slate-950 border-slate-700 text-white'
                  }`}
                />
              </div>

              <div>
                <label className="text-xs font-bold text-slate-400 block mb-1.5">
                  Payload JSON:
                </label>
                <pre className="p-4 rounded-2xl bg-[#0B111E] text-teal-300 font-mono text-xs overflow-x-auto border border-slate-800">
                  {getActivePayload()}
                </pre>
              </div>

              <div className="flex items-center justify-between pt-2">
                {webhookSuccess ? (
                  <span className="text-xs text-emerald-500 font-bold flex items-center gap-1">
                    <CheckCircle2 className="w-4 h-4" /> Webhook Dispatched Successfully (HTTP 200 OK)
                  </span>
                ) : (
                  <span className="text-xs text-slate-400">Payload ready for broadcast</span>
                )}

                <button
                  onClick={handleDispatchWebhook}
                  disabled={isSendingWebhook}
                  className="flex items-center gap-2 px-5 py-2 rounded-xl text-xs font-bold bg-gradient-to-r from-sky-600 to-indigo-600 text-white shadow-md hover:scale-[1.02] transition-transform cursor-pointer"
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>{isSendingWebhook ? 'Dispatching...' : 'Dispatch Webhook Now'}</span>
                </button>
              </div>
            </div>
          ) : (
            <pre className="p-4 rounded-2xl bg-[#0B111E] text-sky-300 font-mono text-xs overflow-x-auto leading-relaxed border border-slate-800">
              {getActivePayload()}
            </pre>
          )}
        </div>

        {/* FOOTER */}
        <div className="flex items-center justify-between px-6 py-3 border-t border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-950/80 backdrop-blur-md text-xs text-slate-400">
          <span>Formatted for native import into Jira, Confluence, and GitHub</span>
          <span className="font-mono text-[11px]">JSON &bull; Storage Format &bull; Markdown</span>
        </div>
      </div>
    </div>
  );
}
