export function buildServerlessEdaXml(): string {
  return `<mxfile host="embed.diagrams.net" modified="2026-08-19T16:20:00.000Z" agent="PromptCanvas" version="24.7.17">
  <diagram id="serverless_eda_architecture" name="Blueprint 26 - GCP Serverless EDA Architecture">
    <mxGraphModel dx="1600" dy="1000" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1600" pageHeight="1000" background="#FFFFFF" math="0" shadow="0">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <mxCell id="bp26" value="26" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B3B75;strokeColor=#0B3B75;fontColor=#FFFFFF;fontSize=28;fontStyle=1;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="18" y="18" width="62" height="62" as="geometry"/></mxCell>
        <mxCell id="title" value="&lt;b&gt;GCP SERVERLESS EDA ARCHITECTURE&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:16px;color:#2563EB;&quot;&gt;Real-time Event-Driven Architecture on Google Cloud with Gemini AI&lt;/span&gt;" style="text;html=1;align=left;verticalAlign=middle;fontSize=24;fontColor=#0F2747;" vertex="1" parent="1"><mxGeometry x="92" y="14" width="680" height="70" as="geometry"/></mxCell>
        <mxCell id="traits" value="☁ Serverless   ⚡ Real-time   ✦ Gemini AI-powered   🛡 Secure   $ Cost-optimized" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#AFC3DB;fontColor=#24364B;fontSize=12;fontStyle=1;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="790" y="18" width="785" height="54" as="geometry"/></mxCell>
        <mxCell id="sources_bg" value="EVENT SOURCES" style="swimlane;html=1;rounded=1;startSize=34;horizontal=1;fillColor=#F7FAFE;swimlaneFillColor=#F7FAFE;strokeColor=#B9CBE0;fontColor=#17365D;fontStyle=1;fontSize=12;align=center;" vertex="1" parent="1"><mxGeometry x="18" y="100" width="190" height="565" as="geometry"/></mxCell>
        <mxCell id="ingest_bg" value="①  INGESTION" style="swimlane;html=1;rounded=1;startSize=34;horizontal=1;swimlaneFillColor=#EAF1FF;strokeColor=#7AA6E6;fontColor=#FFFFFF;fontStyle=1;fontSize=13;align=center;gradientColor=#2563EB;fillColor=#3B82F6;" vertex="1" parent="1"><mxGeometry x="225" y="100" width="220" height="565" as="geometry"/></mxCell>
        <mxCell id="process_bg" value="②  PROCESSING (SERVERLESS)" style="swimlane;html=1;rounded=1;startSize=34;horizontal=1;swimlaneFillColor=#EDF3FF;strokeColor=#7AA6E6;fontColor=#FFFFFF;fontStyle=1;fontSize=13;align=center;gradientColor=#2563EB;fillColor=#4F86E8;" vertex="1" parent="1"><mxGeometry x="455" y="100" width="300" height="565" as="geometry"/></mxCell>
        <mxCell id="data_bg" value="③  DATA STORES" style="swimlane;html=1;rounded=1;startSize=34;horizontal=1;swimlaneFillColor=#F4FBF5;strokeColor=#88B98D;fontColor=#FFFFFF;fontStyle=1;fontSize=13;align=center;fillColor=#78B67B;" vertex="1" parent="1"><mxGeometry x="765" y="100" width="245" height="565" as="geometry"/></mxCell>
        <mxCell id="ai_bg" value="④  AI / ANALYTICS" style="swimlane;html=1;rounded=1;startSize=34;horizontal=1;swimlaneFillColor=#FBF7FF;strokeColor=#A98AD9;fontColor=#FFFFFF;fontStyle=1;fontSize=13;align=center;fillColor=#8E61C7;" vertex="1" parent="1"><mxGeometry x="1020" y="100" width="255" height="565" as="geometry"/></mxCell>
        <mxCell id="action_bg" value="⑤  ACTIONS &amp; NOTIFICATIONS" style="swimlane;html=1;rounded=1;startSize=34;horizontal=1;swimlaneFillColor=#FFF9F2;strokeColor=#E5A34C;fontColor=#FFFFFF;fontStyle=1;fontSize=13;align=center;fillColor=#F59E0B;" vertex="1" parent="1"><mxGeometry x="1285" y="100" width="290" height="565" as="geometry"/></mxCell>
        <mxCell id="src_apps" value="&lt;b&gt;Applications&lt;/b&gt;&lt;br&gt;▣ Web Apps&lt;br&gt;▣ Mobile Apps&lt;br&gt;☁ SaaS Applications" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;verticalAlign=top;spacing=8;" vertex="1" parent="1"><mxGeometry x="30" y="148" width="166" height="105" as="geometry"/></mxCell>
        <mxCell id="src_iot" value="&lt;b&gt;IoT &amp; Devices&lt;/b&gt;&lt;br&gt;◉ IoT Devices&lt;br&gt;⌁ Sensors&lt;br&gt;◈ Edge Gateways" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;verticalAlign=top;spacing=8;" vertex="1" parent="1"><mxGeometry x="30" y="268" width="166" height="105" as="geometry"/></mxCell>
        <mxCell id="src_ent" value="&lt;b&gt;Enterprise Systems&lt;/b&gt;&lt;br&gt;▦ CRM / ERP&lt;br&gt;◫ Databases&lt;br&gt;▥ Mainframe" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;verticalAlign=top;spacing=8;" vertex="1" parent="1"><mxGeometry x="30" y="388" width="166" height="105" as="geometry"/></mxCell>
        <mxCell id="src_ext" value="&lt;b&gt;External / 3rd Party&lt;/b&gt;&lt;br&gt;⚙ APIs&lt;br&gt;◌ Partners&lt;br&gt;⌁ Market Feeds" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;verticalAlign=top;spacing=8;" vertex="1" parent="1"><mxGeometry x="30" y="508" width="166" height="105" as="geometry"/></mxCell>
        <mxCell id="eventarc" value="&lt;b&gt;Eventarc&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;color:#556579;&quot;&gt;Event routing&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8AB0E8;fontColor=#1E5DA8;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="258" y="182" width="154" height="86" as="geometry"/></mxCell>
        <mxCell id="pubsub" value="&lt;b&gt;Cloud Pub/Sub&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;color:#556579;&quot;&gt;Event bus&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FBFF;strokeColor=#5D95E5;strokeWidth=1.5;fontColor=#1E5DA8;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="248" y="334" width="174" height="92" as="geometry"/></mxCell>
        <mxCell id="dlq" value="&lt;b&gt;Dead Letter Topic&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;color:#A14545;&quot;&gt;Pub/Sub DLQ / poison-pill isolation&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF8F8;strokeColor=#E7A5A5;fontColor=#9B2C2C;fontSize=11;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="248" y="508" width="174" height="74" as="geometry"/></mxCell>
        <mxCell id="proc_group" value="Serverless Processing Services" style="swimlane;html=1;rounded=1;startSize=28;horizontal=1;fillColor=#F9FBFE;swimlaneFillColor=#F9FBFE;strokeColor=#B8C8DA;fontColor=#26384E;fontStyle=1;fontSize=12;align=center;" vertex="1" parent="1"><mxGeometry x="482" y="154" width="246" height="322" as="geometry"/></mxCell>
        <mxCell id="run_ingest" value="&lt;b&gt;Cloud Run&lt;/b&gt;&lt;br&gt;Ingestion Service&lt;br&gt;&lt;span style=&quot;color:#69788A;&quot;&gt;Stateless • autoscaling&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8AB0E8;fontColor=#1E5DA8;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="500" y="200" width="210" height="72" as="geometry"/></mxCell>
        <mxCell id="run_business" value="&lt;b&gt;Cloud Run&lt;/b&gt;&lt;br&gt;Business Processing Service" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8AB0E8;fontColor=#1E5DA8;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="500" y="290" width="210" height="72" as="geometry"/></mxCell>
        <mxCell id="run_enrich" value="&lt;b&gt;Cloud Run&lt;/b&gt;&lt;br&gt;Enrichment Service" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8AB0E8;fontColor=#1E5DA8;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="500" y="380" width="210" height="72" as="geometry"/></mxCell>
        <mxCell id="tasks_retry" value="&lt;b&gt;Cloud Tasks&lt;/b&gt;&lt;br&gt;Background jobs / retry" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#9CB5D4;fontColor=#355A86;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="500" y="508" width="210" height="78" as="geometry"/></mxCell>
        <mxCell id="ops_store_group" value="Operational Data Stores" style="swimlane;html=1;rounded=1;startSize=28;horizontal=1;fillColor=#FAFEFA;swimlaneFillColor=#FAFEFA;strokeColor=#B8D3BB;fontColor=#315C35;fontStyle=1;fontSize=12;align=center;" vertex="1" parent="1"><mxGeometry x="790" y="154" width="195" height="300" as="geometry"/></mxCell>
        <mxCell id="bigtable" value="&lt;b&gt;Cloud Bigtable&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;color:#5C6B5E;&quot;&gt;Low-latency NoSQL&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8FBF94;fontColor=#2C6D34;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="808" y="204" width="158" height="80" as="geometry"/></mxCell>
        <mxCell id="gcs" value="&lt;b&gt;Cloud Storage&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;color:#5C6B5E;&quot;&gt;Raw / Archive&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8FBF94;fontColor=#2C6D34;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="808" y="318" width="158" height="80" as="geometry"/></mxCell>
        <mxCell id="analytic_store_group" value="Analytical Data Store" style="swimlane;html=1;rounded=1;startSize=28;horizontal=1;fillColor=#FAFEFA;swimlaneFillColor=#FAFEFA;strokeColor=#B8D3BB;fontColor=#315C35;fontStyle=1;fontSize=12;align=center;" vertex="1" parent="1"><mxGeometry x="790" y="482" width="195" height="140" as="geometry"/></mxCell>
        <mxCell id="bigquery" value="&lt;b&gt;BigQuery&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;color:#5C6B5E;&quot;&gt;Analytics warehouse&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8FBF94;fontColor=#2C6D34;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="808" y="526" width="158" height="72" as="geometry"/></mxCell>
        <mxCell id="gemini_group" value="Gemini AI Services" style="swimlane;html=1;rounded=1;startSize=28;horizontal=1;fillColor=#FCFAFF;swimlaneFillColor=#FCFAFF;strokeColor=#C0A7E3;fontColor=#5E3A8E;fontStyle=1;fontSize=12;align=center;" vertex="1" parent="1"><mxGeometry x="1044" y="154" width="207" height="234" as="geometry"/></mxCell>
        <mxCell id="gemini" value="✦  &lt;b&gt;Gemini&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;color:#5E3A8E;&quot;&gt;Predictive insights&lt;br&gt;Anomaly detection&lt;br&gt;Natural-language Q&amp;A&lt;br&gt;Summarization&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B79BDC;fontColor=#6339A1;fontSize=12;align=left;verticalAlign=middle;spacingLeft=10;" vertex="1" parent="1"><mxGeometry x="1060" y="200" width="175" height="150" as="geometry"/></mxCell>
        <mxCell id="vertexai" value="&lt;b&gt;Vertex AI&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;color:#6A5A7A;&quot;&gt;Model platform • pipelines • feature services&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B79BDC;fontColor=#6339A1;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1044" y="420" width="207" height="86" as="geometry"/></mxCell>
        <mxCell id="looker" value="&lt;b&gt;Looker&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;color:#6A5A7A;&quot;&gt;BI &amp; dashboards&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B79BDC;fontColor=#6339A1;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1044" y="530" width="207" height="72" as="geometry"/></mxCell>
        <mxCell id="downstream_group" value="Downstream Actions" style="swimlane;html=1;rounded=1;startSize=28;horizontal=1;fillColor=#FFFCF7;swimlaneFillColor=#FFFCF7;strokeColor=#E9BE82;fontColor=#8C570E;fontStyle=1;fontSize=12;align=center;" vertex="1" parent="1"><mxGeometry x="1310" y="154" width="240" height="282" as="geometry"/></mxCell>
        <mxCell id="action_tasks" value="&lt;b&gt;Cloud Tasks&lt;/b&gt;&lt;br&gt;Workflow trigger" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E6B86F;fontColor=#A45D00;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1330" y="200" width="200" height="68" as="geometry"/></mxCell>
        <mxCell id="functions" value="&lt;b&gt;Cloud Functions&lt;/b&gt;&lt;br&gt;Event-driven actions" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E6B86F;fontColor=#A45D00;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1330" y="286" width="200" height="68" as="geometry"/></mxCell>
        <mxCell id="run_api" value="&lt;b&gt;Cloud Run&lt;/b&gt;&lt;br&gt;Webhooks / APIs" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E6B86F;fontColor=#A45D00;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1330" y="372" width="200" height="48" as="geometry"/></mxCell>
        <mxCell id="notify_group" value="Notifications &amp; Alerts" style="swimlane;html=1;rounded=1;startSize=28;horizontal=1;fillColor=#FFFCF7;swimlaneFillColor=#FFFCF7;strokeColor=#E9BE82;fontColor=#B96A00;fontStyle=1;fontSize=12;align=center;" vertex="1" parent="1"><mxGeometry x="1310" y="468" width="240" height="154" as="geometry"/></mxCell>
        <mxCell id="notify" value="🔔 Cloud Monitoring Alerts&lt;br&gt;✉ Email / SMS / Slack&lt;br&gt;● PagerDuty / Opsgenie" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E6B86F;fontColor=#6A4A22;fontSize=11;align=left;verticalAlign=middle;spacingLeft=12;" vertex="1" parent="1"><mxGeometry x="1330" y="510" width="200" height="90" as="geometry"/></mxCell>
        <mxCell id="e1" value="1" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;endArrow=block;endFill=1;strokeWidth=1.8;strokeColor=#202020;fontStyle=1;fontSize=11;labelBackgroundColor=#FFFFFF;" edge="1" parent="1" source="src_iot" target="eventarc"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e1b" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="src_apps" target="eventarc"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e1c" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="src_ent" target="eventarc"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e1d" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="src_ext" target="eventarc"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e2" value="2" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.8;strokeColor=#202020;fontStyle=1;fontSize=11;labelBackgroundColor=#FFFFFF;" edge="1" parent="1" source="eventarc" target="pubsub"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e2a" value="2a" style="edgeStyle=orthogonalEdgeStyle;rounded=0;dashed=1;html=1;endArrow=block;endFill=1;strokeWidth=1.5;strokeColor=#6C63C7;fontStyle=1;fontSize=10;labelBackgroundColor=#FFFFFF;" edge="1" parent="1" source="pubsub" target="dlq"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e3" value="3" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.8;strokeColor=#202020;fontStyle=1;fontSize=11;labelBackgroundColor=#FFFFFF;" edge="1" parent="1" source="pubsub" target="run_business"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e3a" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="pubsub" target="run_ingest"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e3b" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="pubsub" target="run_enrich"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e4" value="4" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.8;strokeColor=#202020;fontStyle=1;fontSize=11;labelBackgroundColor=#FFFFFF;" edge="1" parent="1" source="run_business" target="bigtable"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e4a" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="run_enrich" target="gcs"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e4b" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="run_business" target="bigquery"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e5" value="5" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.8;strokeColor=#202020;fontStyle=1;fontSize=11;labelBackgroundColor=#FFFFFF;" edge="1" parent="1" source="bigquery" target="gemini"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e5a" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="bigtable" target="gemini"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e5b" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="gemini" target="looker"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e6" value="6" style="edgeStyle=orthogonalEdgeStyle;rounded=0;dashed=1;html=1;endArrow=block;endFill=1;strokeWidth=1.6;strokeColor=#4B6CB7;fontStyle=1;fontSize=11;labelBackgroundColor=#FFFFFF;" edge="1" parent="1" source="gemini" target="tasks_retry"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e7" value="7" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.8;strokeColor=#202020;fontStyle=1;fontSize=11;labelBackgroundColor=#FFFFFF;" edge="1" parent="1" source="gemini" target="action_tasks"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e7a" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="action_tasks" target="functions"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e7b" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="functions" target="run_api"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e7c" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;endArrow=block;endFill=1;strokeWidth=1.4;strokeColor=#202020;" edge="1" parent="1" source="functions" target="notify"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="flow_summary" value="&lt;b&gt;DATA FLOW (End-to-End)&lt;/b&gt;&lt;br&gt;① Events routed by Eventarc → ② Published to Pub/Sub → ③ Cloud Run consumes &amp; processes → ④ Persist to Bigtable / BigQuery → ⑤ Gemini + Vertex AI analyze → ⑥ Long-running work via Cloud Tasks → ⑦ Actions executed &amp; notifications sent" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="140" y="685" width="1050" height="66" as="geometry"/></mxCell>
        <mxCell id="cross_title" value="CROSS-CUTTING CAPABILITIES" style="text;html=1;align=center;verticalAlign=middle;fontStyle=1;fontSize=12;fontColor=#17365D;" vertex="1" parent="1"><mxGeometry x="140" y="760" width="1050" height="24" as="geometry"/></mxCell>
        <mxCell id="security" value="&lt;b&gt;Security &amp; Identity&lt;/b&gt;&lt;br&gt;Cloud IAM • Workload Identity&lt;br&gt;VPC Service Controls • CMEK" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=10;align=left;verticalAlign=middle;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="140" y="792" width="196" height="88" as="geometry"/></mxCell>
        <mxCell id="resilience" value="&lt;b&gt;Reliability &amp; Resilience&lt;/b&gt;&lt;br&gt;Multi-zone • autoscaling&lt;br&gt;Retries • DLQs" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=10;align=left;verticalAlign=middle;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="348" y="792" width="196" height="88" as="geometry"/></mxCell>
        <mxCell id="observability" value="&lt;b&gt;Observability&lt;/b&gt;&lt;br&gt;Cloud Monitoring • Logging&lt;br&gt;Trace • Error Reporting" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=10;align=left;verticalAlign=middle;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="556" y="792" width="196" height="88" as="geometry"/></mxCell>
        <mxCell id="governance" value="&lt;b&gt;Event Governance&lt;/b&gt;&lt;br&gt;Avro / Proto schemas&lt;br&gt;Catalog • quality rules" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=10;align=left;verticalAlign=middle;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="764" y="792" width="196" height="88" as="geometry"/></mxCell>
        <mxCell id="cost" value="&lt;b&gt;Cost Optimization&lt;/b&gt;&lt;br&gt;Pay-per-use • autoscale-to-zero&lt;br&gt;Right-size resources" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=10;align=left;verticalAlign=middle;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="972" y="792" width="218" height="88" as="geometry"/></mxCell>
        <mxCell id="foundation" value="&lt;b&gt;FOUNDATION (GOOGLE CLOUD)&lt;/b&gt;&lt;br&gt;Google Cloud  |  VPC  |  Cloud DNS  |  Cloud Armor  |  Cloud KMS  |  Cloud Audit Logs  |  Organization Policy  |  Cloud Billing" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FAFD;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="18" y="898" width="1180" height="74" as="geometry"/></mxCell>
        <mxCell id="legend" value="&lt;b&gt;LEGEND&lt;/b&gt;&lt;br&gt;━━ Data flow&lt;br&gt;┅┅ Control / trigger&lt;br&gt;┅┅ Retry / DLQ" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=10;align=left;verticalAlign=middle;spacingLeft=10;" vertex="1" parent="1"><mxGeometry x="1220" y="700" width="170" height="120" as="geometry"/></mxCell>
        <mxCell id="benefits" value="&lt;b&gt;KEY BENEFITS&lt;/b&gt;&lt;br&gt;✓ Real-time event processing at scale&lt;br&gt;✓ Fully serverless / autoscale-to-zero&lt;br&gt;✓ Low latency &amp; high throughput&lt;br&gt;✓ Fault-tolerant with DLQ / retries&lt;br&gt;✓ Secure by default&lt;br&gt;✓ Gemini AI for intelligent insights&lt;br&gt;✓ Pay only for usage" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=10;align=left;verticalAlign=top;spacing=10;" vertex="1" parent="1"><mxGeometry x="1410" y="700" width="165" height="220" as="geometry"/></mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>`;
}
