/** Blueprint 39 — Equipment Predictive Maintenance Architecture. */
const BASE='https://cdn.jsdelivr.net/npm/gcp-icons@1.0.6/dist/icons/';
const ICON={bigquery:`${BASE}bigquery-512-color.svg`,storage:`${BASE}cloud-storage-512-color.svg`,vertex:`${BASE}vertexai-512-color.svg`,sap:'https://cdn.simpleicons.org/sap'};
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const v=(id:string,value:string,style:string,x:number,y:number,w:number,h:number)=>`<mxCell id="${id}" value="${esc(value)}" style="${style}" vertex="1" parent="1"><mxGeometry x="${x}" y="${y}" width="${w}" height="${h}" as="geometry"/></mxCell>`;
const img=(id:string,url:string,x:number,y:number,w:number,h:number)=>v(id,'',`shape=image;imageAspect=0;aspect=fixed;image=${url};align=center;verticalAlign=middle;`,x,y,w,h);
const zone=(id:string,n:number,title:string,sub:string,x:number,w:number,accent:string,fill:string)=>[v(id,'',`rounded=1;arcSize=8;whiteSpace=wrap;html=1;fillColor=${fill};strokeColor=${accent};strokeWidth=1.4;`,x,70,w,600),v(`${id}_n`,String(n),`ellipse;whiteSpace=wrap;html=1;fillColor=${accent};strokeColor=${accent};fontColor=#FFFFFF;fontStyle=1;fontSize=12;align=center;verticalAlign=middle;`,x+14,84,30,30),v(`${id}_h`,`<b>${title}</b><br><span style="font-size:9.7px;color:#64748B">${sub}</span>`,'text;html=1;whiteSpace=wrap;overflow=hidden;spacing=3;align=left;verticalAlign=middle;fontColor=#0F172A;fontSize=12.3;',x+55,78,w-68,46)].join('\n');
const card=(id:string,title:string,body:string,x:number,y:number,w:number,h:number,accent:string,icon?:string,fill='#FFFFFF')=>{const i=icon?img(`${id}_icon`,icon,x+13,y+Math.max(10,(h-34)/2),34,34):'';const tx=icon?x+57:x+14,tw=icon?w-69:w-28;return[v(id,'',`rounded=1;arcSize=7;whiteSpace=wrap;html=1;overflow=hidden;fillColor=${fill};strokeColor=${accent};strokeWidth=1.05;`,x,y,w,h),i,v(`${id}_label`,`<b>${title}</b><br><span style="font-size:9.7px;color:#64748B">${body}</span>`,'text;html=1;whiteSpace=wrap;overflow=hidden;spacing=4;align=left;verticalAlign=middle;fontColor=#0F172A;fontSize=10.9;',tx,y+6,tw,h-12)].filter(Boolean).join('\n');};
const edge=(id:string,s:string,t:string,label:string,color='#2563EB',dashed=false,exitX=1,exitY=.5,entryX=0,entryY=.5)=>`<mxCell id="${id}" value="${esc(label)}" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;strokeColor=${color};strokeWidth=1.8;${dashed?'dashed=1;dashPattern=6 4;':''}endArrow=block;endFill=1;fontSize=9.7;fontColor=#334155;labelBackgroundColor=#FFFFFF;exitX=${exitX};exitY=${exitY};entryX=${entryX};entryY=${entryY};" edge="1" parent="1" source="${s}" target="${t}"><mxGeometry relative="1" as="geometry"/></mxCell>`;
const corridor=(id:string,s:string,t:string,label:string,points:Array<[number,number]>,exitX:number,entryX:number,entryY:number)=>`<mxCell id="${id}" value="${esc(label)}" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;strokeColor=#0F8B82;strokeWidth=1.8;dashed=1;dashPattern=6 4;endArrow=block;endFill=1;fontSize=9.7;fontColor=#0F766E;labelBackgroundColor=#FFFFFF;exitX=${exitX};exitY=1;entryX=${entryX};entryY=${entryY};" edge="1" parent="1" source="${s}" target="${t}"><mxGeometry relative="1" as="geometry"><Array as="points">${points.map(([x,y])=>`<mxPoint x="${x}" y="${y}"/>`).join('')}</Array></mxGeometry></mxCell>`;

export function buildPredictiveMaintenancePhase1Xml():string{
 const c:string[]=['<mxCell id="0"/>','<mxCell id="1" parent="0"/>'];
 c.push(v('purpose','<b>EQUIPMENT PREDICTIVE MAINTENANCE</b>   Asset signals → contextualized manufacturing data → reliability features → anomaly/RUL evidence → human maintenance decision → CMMS/ERP execution → outcome learning.','rounded=1;arcSize=7;whiteSpace=wrap;html=1;overflow=hidden;spacing=7;fillColor=#F8FAFC;strokeColor=#CBD5E1;strokeWidth=1.2;fontColor=#334155;fontSize=11.4;align=center;verticalAlign=middle;',30,20,1700,36));
 c.push(zone('signals',1,'EQUIPMENT & CONDITION SIGNALS','Asset-centric telemetry and inspection evidence',30,240,'#1A73E8','#EFF6FF'));
 c.push(card('assets','Critical equipment','Rotating assets • pumps • compressors • motors • CNC/robotics • production equipment',50,142,200,82,'#1A73E8'));c.push(card('telemetry','Condition telemetry','Vibration • temperature • pressure • current • acoustic • runtime counters',50,246,200,84,'#1A73E8'));c.push(card('inspection','Inspection evidence','Images/video • thermal inspection • technician observations • maintenance history',50,352,200,88,'#1A73E8'));c.push(card('ot','OT systems','PLC / SCADA / historian / MES remain operational control systems; AI does not directly control safety loops.',50,462,200,94,'#1A73E8'));c.push(card('safety','Safety boundary','SIS/PLC interlocks remain deterministic. Generative AI may explain/recommend, never replace certified protection logic.',50,578,200,68,'#D93025',undefined,'#FFF7F7'));
 c.push(zone('factory',2,'FACTORY-TO-CLOUD DATA','Industrial connectivity and contextualization',290,280,'#0F8B82','#ECFDF5'));
 c.push(card('connect','Manufacturing Connect','Factory/edge connectivity across supported industrial protocols and automation sources',310,142,240,84,'#0F8B82'));c.push(card('mde','Manufacturing Data Engine','Ingest, contextualize and model factory data with the configured common model.',310,248,240,88,'#0F8B82'));c.push(card('stream','Pub/Sub + Dataflow','Event distribution and streaming transformation when selected MDE/downstream design requires it.',310,358,240,90,'#0F8B82'));c.push(card('context','Asset context & quality','Asset identity • timestamps • unit/operating mode • sensor quality • maintenance context',310,470,240,88,'#0F8B82'));c.push(card('edge','Optional edge processing','Filtering/inference/preprocessing only where latency, bandwidth or resilience requires it.',310,580,240,66,'#0F8B82'));
 c.push(zone('reliability',3,'RELIABILITY DATA FOUNDATION','Time-series, history and governed analytical context',590,300,'#6554C0','#F5F3FF'));
 c.push(card('bq','BigQuery','Fleet history • maintenance outcomes • reliability features • analytical marts',610,142,260,84,'#6554C0',ICON.bigquery));c.push(card('gcs','Cloud Storage','Inspection media • raw files • model/evaluation artifacts as appropriate',610,248,260,84,'#6554C0',ICON.storage));c.push(card('timeseries','Operational/time-series serving','Bigtable or workload-appropriate low-latency serving only when required by access pattern.',610,354,260,88,'#6554C0'));c.push(card('cmms','CMMS / ERP history','Work orders • failure codes • parts • technician notes • asset hierarchy',610,464,260,88,'#6554C0'));c.push(card('features','Governed features & provenance','Training/serving feature definitions • source lineage • versioned labels • access controls',610,574,260,72,'#6554C0'));
 c.push(zone('predict',4,'PREDICTIVE & DIAGNOSTIC AI','Detect, predict and explain with evidence',910,300,'#B83280','#FDF2F8'));
 c.push(card('vertex','Vertex AI / approved models','Train/evaluate/deploy anomaly classification or RUL models where predictive value is demonstrated.',930,142,260,90,'#B83280',ICON.vertex));c.push(card('score','Condition & anomaly scoring','Combine engineered telemetry features and optional visual signals; emit score + confidence + evidence.',930,254,260,92,'#B83280'));c.push(card('rul','Failure-risk / RUL estimate','Use only where label-validated outcome data supports predictive targets; preserve uncertainty.',930,368,260,90,'#B83280'));c.push(card('assistant','Gemini maintenance assistant','Grounded explanation, troubleshooting summary and recommended next checks from approved maintenance data.',930,480,260,90,'#B83280'));c.push(card('eval','Evaluation & drift','Backtest • false-positive/negative rate • calibration • drift • threshold review • rollback criteria',930,592,260,54,'#B83280'));
 c.push(zone('action',5,'MAINTENANCE DECISION & EXECUTION','Human-authorized action with measurable feedback',1230,300,'#E87900','#FFF7ED'));
 c.push(card('priority','Prioritize maintenance','Risk × criticality × confidence × operating window → inspect / plan / monitor',1250,142,260,88,'#E87900'));c.push(card('review','Reliability / technician review','Validate evidence, safety implications and action recommendation before consequential work.',1250,252,260,92,'#D93025',undefined,'#FFF7F7'));c.push(card('erp','CMMS / ERP execution','SAP / CMMS / ServiceNow or approved maintenance system receives structured approved work.',1250,366,260,90,'#E87900',ICON.sap));c.push(card('work','Work order / inspection task','Create/revise authorized maintenance task; never treat an LLM recommendation as a safety command.',1250,478,260,94,'#E87900'));c.push(card('outcome','Outcome feedback','Failure confirmed? action taken? downtime avoided? parts replaced? feed labeled outcomes back to analytics/evaluation.',1250,594,260,52,'#0F8B82','#ECFDF5'));
 c.push(zone('ops',6,'RELIABILITY, SECURITY & OPERATIONS','Cross-cutting controls beside the workflow',1550,180,'#334155','#F8FAFC'));
 c.push(card('security','Security & identity','IAM • workload identity • encryption/KMS • network segmentation • VPC Service Controls only for supported services',1570,142,140,106,'#334155'));c.push(card('observe','Observability','Cloud Monitoring/Logging • pipeline health • model endpoint health • freshness • alert routing',1570,270,140,106,'#334155'));c.push(card('govern','Model governance','Versioned data/model/evaluation • approval evidence • rollback • retraining triggers • owner',1570,398,140,106,'#334155'));c.push(card('otboundary','OT/IT boundary','Industrial DMZ / approved routes • no implicit cloud-to-PLC write path • plant safety policy dominates',1570,526,140,120,'#D93025',undefined,'#FFF7F7'));
 c.push(edge('e1','telemetry','connect','industrial data'));c.push(edge('e2','mde','bq','contextualized history','#0F8B82'));c.push(edge('e3','features','vertex','training/serving features','#6554C0'));c.push(edge('e4','rul','priority','risk evidence','#B83280'));c.push(edge('e5','priority','review','recommendation','#E87900',false,.5,1,.5,0));c.push(edge('e6','review','erp','approved work','#E87900',false,.5,1,.5,0));
 // Learning loops deliberately use the bottom whitespace + the 20px gutter between reliability and AI.
 c.push(corridor('e7','outcome','bq','labeled outcome',[[1420,692],[900,692],[900,210]],.65,1,.82));
 c.push(corridor('e8','outcome','eval','evaluation signal',[[1340,678],[900,678],[900,619]],.35,0,.5));
 c.push(v('footer','<b>SUCCESS MEASURES — WORKLOAD-DEFINED:</b> precision/recall at useful horizon • false-positive burden • lead time • planned-vs-unplanned work • downtime/quality impact • technician acceptance • cost/value evidence.','rounded=1;arcSize=7;whiteSpace=wrap;html=1;overflow=hidden;spacing=7;fillColor=#FFFFFF;strokeColor=#CBD5E1;strokeWidth=1.1;fontColor=#475569;fontSize=10.5;align=center;verticalAlign=middle;',30,705,1700,52));
 return `<mxfile host="app.diagrams.net" modified="2026-08-20T00:00:00.000Z" agent="PromptCanvas" version="24.0.0" type="device"><diagram id="predictive_maintenance_phase1" name="Equipment Predictive Maintenance Architecture"><mxGraphModel dx="1760" dy="800" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1760" pageHeight="790" background="#FFFFFF"><root>${c.join('\n')}</root></mxGraphModel></diagram></mxfile>`;
}
