export function buildServerlessEdaXml(): string {
  return `<mxfile host="embed.diagrams.net" modified="2026-08-19T16:33:00.000Z" agent="PromptCanvas" version="24.7.17">
  <diagram id="serverless_eda_architecture" name="Blueprint 26 - GCP Serverless EDA Architecture">
    <mxGraphModel dx="1780" dy="900" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1780" pageHeight="900" background="#FFFFFF" math="0" shadow="0">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>
        <mxCell id="bp26" value="26" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B3B75;strokeColor=#0B3B75;fontColor=#FFFFFF;fontSize=30;fontStyle=1;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="20" y="18" width="64" height="64" as="geometry"/></mxCell>
        <mxCell id="title" value="&lt;b&gt;GCP SERVERLESS EDA ARCHITECTURE&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:17px;color:#2563EB;font-weight:600;&quot;&gt;Real-time Event-Driven Architecture on Google Cloud with Gemini AI&lt;/span&gt;" style="text;html=1;align=left;verticalAlign=middle;fontSize=27;fontColor=#0F2747;" vertex="1" parent="1"><mxGeometry x="100" y="12" width="720" height="76" as="geometry"/></mxCell>
        <mxCell id="traits" value="☁ &lt;b&gt;Serverless&lt;/b&gt;     ⚡ &lt;b&gt;Real-time&lt;/b&gt;     ✦ &lt;b&gt;Gemini AI-powered&lt;/b&gt;     🛡 &lt;b&gt;Secure&lt;/b&gt;     $ &lt;b&gt;Cost-optimized&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#9FB6D2;strokeWidth=1.4;fontColor=#22354C;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="845" y="22" width="900" height="54" as="geometry"/></mxCell>
        <mxCell id="sources_bg" value="EVENT SOURCES" style="swimlane;html=1;rounded=1;startSize=38;horizontal=1;fillColor=#F7FAFE;swimlaneFillColor=#F7FAFE;strokeColor=#B9CBE0;fontColor=#17365D;fontStyle=1;fontSize=14;align=center;" vertex="1" parent="1"><mxGeometry x="20" y="105" width="190" height="520" as="geometry"/></mxCell>
        <mxCell id="ingest_bg" value="①  INGESTION" style="swimlane;html=1;rounded=1;startSize=38;horizontal=1;swimlaneFillColor=#EAF1FF;strokeColor=#6E9EE2;fontColor=#FFFFFF;fontStyle=1;fontSize=15;align=center;fillColor=#3B82F6;" vertex="1" parent="1"><mxGeometry x="225" y="105" width="230" height="520" as="geometry"/></mxCell>
        <mxCell id="process_bg" value="②  PROCESSING (SERVERLESS)" style="swimlane;html=1;rounded=1;startSize=38;horizontal=1;swimlaneFillColor=#EDF3FF;strokeColor=#6E9EE2;fontColor=#FFFFFF;fontStyle=1;fontSize=15;align=center;fillColor=#4F86E8;" vertex="1" parent="1"><mxGeometry x="470" y="105" width="325" height="520" as="geometry"/></mxCell>
        <mxCell id="data_bg" value="③  DATA STORES" style="swimlane;html=1;rounded=1;startSize=38;horizontal=1;swimlaneFillColor=#F4FBF5;strokeColor=#7DAE83;fontColor=#FFFFFF;fontStyle=1;fontSize=15;align=center;fillColor=#6EAE73;" vertex="1" parent="1"><mxGeometry x="810" y="105" width="250" height="520" as="geometry"/></mxCell>
        <mxCell id="ai_bg" value="④  GEMINI AI / ANALYTICS" style="swimlane;html=1;rounded=1;startSize=38;horizontal=1;swimlaneFillColor=#FBF7FF;strokeColor=#9B78CC;fontColor=#FFFFFF;fontStyle=1;fontSize=15;align=center;fillColor=#8054BD;" vertex="1" parent="1"><mxGeometry x="1075" y="105" width="295" height="520" as="geometry"/></mxCell>
        <mxCell id="action_bg" value="⑤  ACTIONS &amp; NOTIFICATIONS" style="swimlane;html=1;rounded=1;startSize=38;horizontal=1;swimlaneFillColor=#FFF9F2;strokeColor=#E19C3F;fontColor=#FFFFFF;fontStyle=1;fontSize=15;align=center;fillColor=#F59E0B;" vertex="1" parent="1"><mxGeometry x="1385" y="105" width="360" height="520" as="geometry"/></mxCell>
        <mxCell id="src_apps" value="&lt;b&gt;Applications&lt;/b&gt;&lt;br&gt;Web • Mobile • SaaS" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="38" y="165" width="154" height="76" as="geometry"/></mxCell>
        <mxCell id="src_iot" value="&lt;b&gt;IoT &amp; Devices&lt;/b&gt;&lt;br&gt;Sensors • Edge gateways" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="38" y="262" width="154" height="76" as="geometry"/></mxCell>
        <mxCell id="src_ent" value="&lt;b&gt;Enterprise Systems&lt;/b&gt;&lt;br&gt;CRM / ERP • Databases" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="38" y="359" width="154" height="76" as="geometry"/></mxCell>
        <mxCell id="src_ext" value="&lt;b&gt;External / 3rd Party&lt;/b&gt;&lt;br&gt;APIs • Partners • Feeds" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="38" y="456" width="154" height="76" as="geometry"/></mxCell>
        <mxCell id="eventarc_icon" value="" style="shape=mxgraph.gcp2.eventarc;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="250" y="166" width="48" height="48" as="geometry"/></mxCell>
        <mxCell id="eventarc" value="&lt;b&gt;Eventarc&lt;/b&gt;&lt;br&gt;Event routing" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8AB0E8;fontColor=#1E5DA8;fontSize=14;align=center;verticalAlign=middle;spacingLeft=42;" vertex="1" parent="1"><mxGeometry x="248" y="155" width="184" height="78" as="geometry"/></mxCell>
        <mxCell id="pubsub_icon" value="" style="shape=mxgraph.gcp2.pubsub;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="250" y="303" width="48" height="48" as="geometry"/></mxCell>
        <mxCell id="pubsub" value="&lt;b&gt;Cloud Pub/Sub&lt;/b&gt;&lt;br&gt;Event bus" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FBFF;strokeColor=#5D95E5;strokeWidth=1.5;fontColor=#1E5DA8;fontSize=14;align=center;verticalAlign=middle;spacingLeft=42;" vertex="1" parent="1"><mxGeometry x="248" y="292" width="184" height="82" as="geometry"/></mxCell>
        <mxCell id="dlq" value="&lt;b&gt;Dead Letter Topic&lt;/b&gt;&lt;br&gt;Pub/Sub DLQ • poison-pill isolation" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF8F8;strokeColor=#E7A5A5;fontColor=#9B2C2C;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="248" y="456" width="184" height="78" as="geometry"/></mxCell>
        <mxCell id="proc_group" value="Serverless Processing Services" style="swimlane;html=1;rounded=1;startSize=30;horizontal=1;fillColor=#F9FBFE;swimlaneFillColor=#F9FBFE;strokeColor=#B8C8DA;fontColor=#26384E;fontStyle=1;fontSize=13;align=center;" vertex="1" parent="1"><mxGeometry x="492" y="150" width="280" height="308" as="geometry"/></mxCell>
        <mxCell id="run_ingest_icon" value="" style="shape=mxgraph.gcp2.cloud_run;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="512" y="200" width="46" height="46" as="geometry"/></mxCell>
        <mxCell id="run_ingest" value="&lt;b&gt;Cloud Run&lt;/b&gt;&lt;br&gt;Ingestion Service&lt;br&gt;&lt;span style=&quot;color:#69788A;&quot;&gt;Stateless • autoscaling&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8AB0E8;fontColor=#1E5DA8;fontSize=13;align=center;verticalAlign=middle;spacingLeft=38;" vertex="1" parent="1"><mxGeometry x="508" y="187" width="238" height="72" as="geometry"/></mxCell>
        <mxCell id="run_business_icon" value="" style="shape=mxgraph.gcp2.cloud_run;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="512" y="288" width="46" height="46" as="geometry"/></mxCell>
        <mxCell id="run_business" value="&lt;b&gt;Cloud Run&lt;/b&gt;&lt;br&gt;Business Processing Service" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8AB0E8;fontColor=#1E5DA8;fontSize=13;align=center;verticalAlign=middle;spacingLeft=38;" vertex="1" parent="1"><mxGeometry x="508" y="275" width="238" height="72" as="geometry"/></mxCell>
        <mxCell id="run_enrich_icon" value="" style="shape=mxgraph.gcp2.cloud_run;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="512" y="376" width="46" height="46" as="geometry"/></mxCell>
        <mxCell id="run_enrich" value="&lt;b&gt;Cloud Run&lt;/b&gt;&lt;br&gt;Enrichment Service" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8AB0E8;fontColor=#1E5DA8;fontSize=13;align=center;verticalAlign=middle;spacingLeft=38;" vertex="1" parent="1"><mxGeometry x="508" y="363" width="238" height="72" as="geometry"/></mxCell>
        <mxCell id="tasks_retry_icon" value="" style="shape=mxgraph.gcp2.cloud_tasks;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="523" y="494" width="44" height="44" as="geometry"/></mxCell>
        <mxCell id="tasks_retry" value="&lt;b&gt;Cloud Tasks&lt;/b&gt;&lt;br&gt;Background jobs • retries" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#9CB5D4;fontColor=#355A86;fontSize=13;align=center;verticalAlign=middle;spacingLeft=38;" vertex="1" parent="1"><mxGeometry x="508" y="478" width="238" height="76" as="geometry"/></mxCell>
        <mxCell id="bigtable_icon" value="" style="shape=mxgraph.gcp2.cloud_bigtable;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="840" y="186" width="48" height="48" as="geometry"/></mxCell>
        <mxCell id="bigtable" value="&lt;b&gt;Cloud Bigtable&lt;/b&gt;&lt;br&gt;Low-latency NoSQL" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8FBF94;fontColor=#2C6D34;fontSize=13;align=center;verticalAlign=middle;spacingLeft=42;" vertex="1" parent="1"><mxGeometry x="832" y="170" width="206" height="80" as="geometry"/></mxCell>
        <mxCell id="gcs_icon" value="" style="shape=mxgraph.gcp2.cloud_storage;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="840" y="306" width="48" height="48" as="geometry"/></mxCell>
        <mxCell id="gcs" value="&lt;b&gt;Cloud Storage&lt;/b&gt;&lt;br&gt;Raw / archive" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8FBF94;fontColor=#2C6D34;fontSize=13;align=center;verticalAlign=middle;spacingLeft=42;" vertex="1" parent="1"><mxGeometry x="832" y="290" width="206" height="80" as="geometry"/></mxCell>
        <mxCell id="bigquery_icon" value="" style="shape=mxgraph.gcp2.bigquery;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="840" y="455" width="48" height="48" as="geometry"/></mxCell>
        <mxCell id="bigquery" value="&lt;b&gt;BigQuery&lt;/b&gt;&lt;br&gt;Analytics warehouse" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8FBF94;fontColor=#2C6D34;fontSize=13;align=center;verticalAlign=middle;spacingLeft=42;" vertex="1" parent="1"><mxGeometry x="832" y="439" width="206" height="80" as="geometry"/></mxCell>
        <mxCell id="gemini" value="✦  &lt;b style=&quot;font-size:18px;&quot;&gt;Gemini&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:13px;color:#5E3A8E;&quot;&gt;Predictive insights • anomaly detection&lt;br&gt;Natural-language Q&amp;A • summarization&lt;br&gt;Grounded decision intelligence&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#9D78D1;strokeWidth=2.2;fontColor=#6339A1;fontSize=15;align=left;verticalAlign=middle;spacingLeft=14;" vertex="1" parent="1"><mxGeometry x="1100" y="158" width="245" height="165" as="geometry"/></mxCell>
        <mxCell id="vertex_icon" value="" style="shape=mxgraph.gcp2.vertex_ai;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="1112" y="368" width="46" height="46" as="geometry"/></mxCell>
        <mxCell id="vertexai" value="&lt;b&gt;Vertex AI&lt;/b&gt;&lt;br&gt;Models • pipelines • feature services" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B79BDC;fontColor=#6339A1;fontSize=13;align=center;verticalAlign=middle;spacingLeft=40;" vertex="1" parent="1"><mxGeometry x="1100" y="352" width="245" height="78" as="geometry"/></mxCell>
        <mxCell id="looker_icon" value="" style="shape=mxgraph.gcp2.looker;html=1;aspect=fixed;" vertex="1" parent="1"><mxGeometry x="1112" y="479" width="46" height="46" as="geometry"/></mxCell>
        <mxCell id="looker" value="&lt;b&gt;Looker&lt;/b&gt;&lt;br&gt;BI &amp; operational dashboards" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B79BDC;fontColor=#6339A1;fontSize=13;align=center;verticalAlign=middle;spacingLeft=40;" vertex="1" parent="1"><mxGeometry x="1100" y="463" width="245" height="78" as="geometry"/></mxCell>
        <mxCell id="action_tasks" value="&lt;b&gt;Cloud Tasks&lt;/b&gt;&lt;br&gt;Workflow trigger" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E3B46E;fontColor=#9A5A00;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1410" y="164" width="310" height="72" as="geometry"/></mxCell>
        <mxCell id="action_fn" value="&lt;b&gt;Cloud Run functions&lt;/b&gt;&lt;br&gt;Event-driven actions" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E3B46E;fontColor=#9A5A00;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1410" y="258" width="310" height="72" as="geometry"/></mxCell>
        <mxCell id="action_api" value="&lt;b&gt;Cloud Run&lt;/b&gt;&lt;br&gt;Webhooks / APIs" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E3B46E;fontColor=#9A5A00;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1410" y="352" width="310" height="72" as="geometry"/></mxCell>
        <mxCell id="alerts" value="&lt;b&gt;Notifications &amp; Alerts&lt;/b&gt;&lt;br&gt;Cloud Monitoring • Email / SMS / Slack&lt;br&gt;PagerDuty / Opsgenie" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFDF8;strokeColor=#E6C794;fontColor=#82541B;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1410" y="465" width="310" height="92" as="geometry"/></mxCell>
        <mxCell id="e_src_eventarc" value="1" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2;strokeColor=#1F2937;fontSize=12;fontStyle=1;labelBackgroundColor=#FFFFFF;exitX=1;exitY=0.5;entryX=0;entryY=0.5;" edge="1" parent="1" source="src_apps" target="eventarc"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_event_pub" value="2" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2;strokeColor=#1F2937;fontSize=12;fontStyle=1;labelBackgroundColor=#FFFFFF;exitX=0.5;exitY=1;entryX=0.5;entryY=0;" edge="1" parent="1" source="eventarc" target="pubsub"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_pub_run" value="3" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2.2;strokeColor=#2563EB;fontSize=12;fontStyle=1;labelBackgroundColor=#FFFFFF;exitX=1;exitY=0.5;entryX=0;entryY=0.5;" edge="1" parent="1" source="pubsub" target="run_business"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_pub_dlq" value="2a" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;dashed=1;strokeWidth=1.8;strokeColor=#DC2626;fontSize=11;fontStyle=1;labelBackgroundColor=#FFFFFF;exitX=0.5;exitY=1;entryX=0.5;entryY=0;" edge="1" parent="1" source="pubsub" target="dlq"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_run_bt" value="4" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2.2;strokeColor=#2563EB;fontSize=12;fontStyle=1;labelBackgroundColor=#FFFFFF;exitX=1;exitY=0.35;entryX=0;entryY=0.5;" edge="1" parent="1" source="run_business" target="bigtable"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="780" y="300"/><mxPoint x="780" y="210"/></Array></mxGeometry></mxCell>
        <mxCell id="e_run_gcs" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=1.8;strokeColor=#2563EB;exitX=1;exitY=0.65;entryX=0;entryY=0.5;" edge="1" parent="1" source="run_enrich" target="gcs"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_run_bq" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=1.8;strokeColor=#2563EB;exitX=1;exitY=0.8;entryX=0;entryY=0.5;" edge="1" parent="1" source="run_enrich" target="bigquery"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="780" y="420"/><mxPoint x="780" y="479"/></Array></mxGeometry></mxCell>
        <mxCell id="e_bt_gemini" value="5" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2.4;strokeColor=#7C3AED;fontSize=12;fontStyle=1;labelBackgroundColor=#FFFFFF;exitX=1;exitY=0.5;entryX=0;entryY=0.45;" edge="1" parent="1" source="bigtable" target="gemini"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_bq_gemini" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=1.8;strokeColor=#7C3AED;exitX=1;exitY=0.5;entryX=0;entryY=0.75;" edge="1" parent="1" source="bigquery" target="gemini"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="1068" y="479"/><mxPoint x="1068" y="280"/></Array></mxGeometry></mxCell>
        <mxCell id="e_gemini_action" value="7" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2.4;strokeColor=#7C3AED;fontSize=12;fontStyle=1;labelBackgroundColor=#FFFFFF;exitX=1;exitY=0.45;entryX=0;entryY=0.5;" edge="1" parent="1" source="gemini" target="action_tasks"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_tasks_fn" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=1.8;strokeColor=#D97706;exitX=0.5;exitY=1;entryX=0.5;entryY=0;" edge="1" parent="1" source="action_tasks" target="action_fn"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_fn_api" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=1.8;strokeColor=#D97706;exitX=0.5;exitY=1;entryX=0.5;entryY=0;" edge="1" parent="1" source="action_fn" target="action_api"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_api_alerts" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=1.8;strokeColor=#D97706;exitX=0.5;exitY=1;entryX=0.5;entryY=0;" edge="1" parent="1" source="action_api" target="alerts"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e_retry" value="6  retry / async" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;dashed=1;strokeWidth=1.8;strokeColor=#6366F1;fontSize=11;fontStyle=1;labelBackgroundColor=#FFFFFF;exitX=1;exitY=0.5;entryX=0;entryY=0.5;" edge="1" parent="1" source="tasks_retry" target="run_enrich"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="770" y="516"/><mxPoint x="770" y="399"/></Array></mxGeometry></mxCell>
        <mxCell id="e_iot" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=1.3;strokeColor=#64748B;exitX=1;exitY=0.5;entryX=0;entryY=0.7;" edge="1" parent="1" source="src_iot" target="eventarc"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="215" y="300"/><mxPoint x="215" y="218"/></Array></mxGeometry></mxCell>
        <mxCell id="e_ent" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=1.3;strokeColor=#64748B;exitX=1;exitY=0.5;entryX=0;entryY=0.75;" edge="1" parent="1" source="src_ent" target="pubsub"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="216" y="397"/><mxPoint x="216" y="354"/></Array></mxGeometry></mxCell>
        <mxCell id="e_ext" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=1.3;strokeColor=#64748B;exitX=1;exitY=0.5;entryX=0;entryY=0.9;" edge="1" parent="1" source="src_ext" target="pubsub"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="218" y="494"/><mxPoint x="218" y="370"/></Array></mxGeometry></mxCell>
        <mxCell id="flow_band" value="&lt;b&gt;DATA FLOW (END-TO-END)&lt;/b&gt;&lt;br&gt;① Sources routed by Eventarc  →  ② events published to Pub/Sub  →  ③ Cloud Run services process  →  ④ persist to Bigtable / Storage / BigQuery  →  ⑤ Gemini + Vertex AI analyze  →  ⑥ long-running work via Cloud Tasks  →  ⑦ actions executed &amp; notifications sent" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#24364B;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="185" y="648" width="1420" height="54" as="geometry"/></mxCell>
        <mxCell id="security" value="&lt;b&gt;Security &amp; Identity&lt;/b&gt;&lt;br&gt;Cloud IAM • Workload Identity&lt;br&gt;VPC-SC • CMEK" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FBFCFE;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="185" y="720" width="250" height="76" as="geometry"/></mxCell>
        <mxCell id="reliability" value="&lt;b&gt;Reliability &amp; Resilience&lt;/b&gt;&lt;br&gt;Multi-zone • autoscaling&lt;br&gt;DLQ • retries" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FBFCFE;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="447" y="720" width="250" height="76" as="geometry"/></mxCell>
        <mxCell id="observability" value="&lt;b&gt;Observability&lt;/b&gt;&lt;br&gt;Cloud Monitoring • Logging&lt;br&gt;Trace • Error Reporting" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FBFCFE;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="709" y="720" width="250" height="76" as="geometry"/></mxCell>
        <mxCell id="governance" value="&lt;b&gt;Event Governance&lt;/b&gt;&lt;br&gt;Avro / Protobuf schemas&lt;br&gt;Catalog • quality rules" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FBFCFE;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="971" y="720" width="250" height="76" as="geometry"/></mxCell>
        <mxCell id="cost" value="&lt;b&gt;Cost Optimization&lt;/b&gt;&lt;br&gt;Pay-per-use • scale-to-zero&lt;br&gt;rightsizing • budgets" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FBFCFE;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="1233" y="720" width="250" height="76" as="geometry"/></mxCell>
        <mxCell id="legend" value="&lt;b&gt;LEGEND&lt;/b&gt;&lt;br&gt;━━ Data flow&lt;br&gt;┄┄ Retry / DLQ flow" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="1495" y="720" width="110" height="76" as="geometry"/></mxCell>
        <mxCell id="foundation" value="&lt;b&gt;FOUNDATION (GOOGLE CLOUD)&lt;/b&gt;&lt;br&gt;Google Cloud  |  VPC  |  Cloud DNS  |  Cloud Armor  |  Cloud KMS  |  Cloud Audit Logs  |  Organization Policy  |  Cloud Billing" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FAFC;strokeColor=#AFC3DB;fontColor=#26384E;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="185" y="814" width="1420" height="52" as="geometry"/></mxCell>
        <mxCell id="benefits" value="&lt;b&gt;KEY BENEFITS&lt;/b&gt;&lt;br&gt;✓ Real-time event processing at scale&lt;br&gt;✓ Fully serverless &amp; fault-tolerant&lt;br&gt;✓ Gemini-powered intelligent actions" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B8C8DA;fontColor=#26384E;fontSize=11;align=left;spacingLeft=8;" vertex="1" parent="1"><mxGeometry x="1618" y="648" width="127" height="218" as="geometry"/></mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>`;
}
