/**
 * BLUEPRINT 50: ENTERPRISE MCP GATEWAY ON GOOGLE CLOUD
 * Editable mxGraph master aligned to current remote MCP / Streamable HTTP patterns.
 */
export function buildMcpContextGatewayXml(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="app.diagrams.net" modified="2026-08-19T18:03:00.000Z" agent="PromptCanvas" version="24.7.17" type="device">
  <diagram id="mcp_context_gateway" name="Blueprint 50 - Enterprise MCP Gateway on Google Cloud">
    <mxGraphModel dx="1780" dy="1000" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1780" pageHeight="1000" background="#FFFFFF" math="0" shadow="0">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>

        <mxCell id="bp50" value="50" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B3B75;strokeColor=#0B3B75;fontColor=#FFFFFF;fontSize=30;fontStyle=1;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="18" y="18" width="72" height="72" as="geometry"/></mxCell>
        <mxCell id="title" value="&lt;b&gt;ENTERPRISE MCP GATEWAY ON GOOGLE CLOUD&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:17px;color:#334155;font-weight:600;&quot;&gt;Secure, Stateless Remote MCP Access for AI Hosts, Agents, and Enterprise Tools&lt;/span&gt;" style="text;html=1;align=left;verticalAlign=middle;fontSize=29;fontColor=#102A43;" vertex="1" parent="1"><mxGeometry x="105" y="10" width="850" height="82" as="geometry"/></mxCell>
        <mxCell id="traits" value="&lt;b&gt;Serverless&lt;/b&gt;   |   &lt;b&gt;Streamable HTTP&lt;/b&gt;   |   &lt;b&gt;Stateless&lt;/b&gt;   |   &lt;b&gt;Agentic AI&lt;/b&gt;   |   &lt;b&gt;Secure&lt;/b&gt;   |   &lt;b&gt;Auditable&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B5C8DE;strokeWidth=1.4;fontColor=#334155;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="980" y="25" width="770" height="48" as="geometry"/></mxCell>

        <mxCell id="hosts_bg" value="①  AI HOSTS &amp; AGENTS" style="swimlane;html=1;rounded=1;startSize=40;horizontal=1;fillColor=#2F74D0;swimlaneFillColor=#F5F9FF;strokeColor=#77A6E8;fontColor=#FFFFFF;fontStyle=1;fontSize=15;align=center;" vertex="1" parent="1"><mxGeometry x="20" y="110" width="230" height="500" as="geometry"/></mxCell>
        <mxCell id="client_bg" value="②  MCP CLIENT LAYER" style="swimlane;html=1;rounded=1;startSize=40;horizontal=1;fillColor=#5795E6;swimlaneFillColor=#F5F9FF;strokeColor=#8CB3E8;fontColor=#FFFFFF;fontStyle=1;fontSize=15;align=center;" vertex="1" parent="1"><mxGeometry x="270" y="110" width="285" height="500" as="geometry"/></mxCell>
        <mxCell id="gateway_bg" value="③  ENTERPRISE MCP GATEWAY" style="swimlane;html=1;rounded=1;startSize=40;horizontal=1;fillColor=#159447;swimlaneFillColor=#F4FBF6;strokeColor=#5BAE78;fontColor=#FFFFFF;fontStyle=1;fontSize=15;align=center;" vertex="1" parent="1"><mxGeometry x="575" y="110" width="440" height="500" as="geometry"/></mxCell>
        <mxCell id="servers_bg" value="④  REMOTE MCP SERVERS ON CLOUD RUN" style="swimlane;html=1;rounded=1;startSize=40;horizontal=1;fillColor=#7456C2;swimlaneFillColor=#FAF8FF;strokeColor=#9C88D1;fontColor=#FFFFFF;fontStyle=1;fontSize=14;align=center;" vertex="1" parent="1"><mxGeometry x="1035" y="110" width="335" height="500" as="geometry"/></mxCell>
        <mxCell id="tools_bg" value="⑤  ENTERPRISE TOOLS &amp; DATA" style="swimlane;html=1;rounded=1;startSize=40;horizontal=1;fillColor=#F59E0B;swimlaneFillColor=#FFFBF4;strokeColor=#E7B460;fontColor=#FFFFFF;fontStyle=1;fontSize=15;align=center;" vertex="1" parent="1"><mxGeometry x="1390" y="110" width="360" height="500" as="geometry"/></mxCell>

        <mxCell id="host_gemini" value="&lt;b&gt;Gemini Enterprise&lt;/b&gt;&lt;br&gt;Gemini app / enterprise copilot" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#86AEE4;fontColor=#214A7A;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="42" y="170" width="186" height="74" as="geometry"/></mxCell>
        <mxCell id="host_vertex" value="&lt;b&gt;Vertex AI Agent Engine&lt;/b&gt;&lt;br&gt;Managed agent runtime" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#86AEE4;fontColor=#214A7A;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="42" y="262" width="186" height="74" as="geometry"/></mxCell>
        <mxCell id="host_adk" value="&lt;b&gt;ADK-based Copilot&lt;/b&gt;&lt;br&gt;Internal / domain agent" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#86AEE4;fontColor=#214A7A;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="42" y="354" width="186" height="74" as="geometry"/></mxCell>
        <mxCell id="host_ide" value="&lt;b&gt;IDE / CLI Agent&lt;/b&gt;&lt;br&gt;Developer or operations agent" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#86AEE4;fontColor=#214A7A;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="42" y="446" width="186" height="74" as="geometry"/></mxCell>
        <mxCell id="host_note" value="Hosts embed MCP clients; the gateway is not the model runtime." style="text;html=1;align=center;verticalAlign=middle;fontSize=11;fontColor=#64748B;fontStyle=2;" vertex="1" parent="1"><mxGeometry x="36" y="548" width="198" height="40" as="geometry"/></mxCell>

        <mxCell id="client_discovery" value="&lt;b&gt;Tool Discovery&lt;/b&gt;&lt;br&gt;List tools, prompts, resources" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8EB4E7;fontColor=#214A7A;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="292" y="170" width="240" height="74" as="geometry"/></mxCell>
        <mxCell id="client_cache" value="&lt;b&gt;Capability Cache&lt;/b&gt;&lt;br&gt;Fast local catalog / metadata" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8EB4E7;fontColor=#214A7A;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="292" y="262" width="240" height="74" as="geometry"/></mxCell>
        <mxCell id="client_request" value="&lt;b&gt;Request Builder&lt;/b&gt;&lt;br&gt;JSON-RPC / MCP envelopes" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8EB4E7;fontColor=#214A7A;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="292" y="354" width="240" height="74" as="geometry"/></mxCell>
        <mxCell id="client_response" value="&lt;b&gt;Response Normalizer&lt;/b&gt;&lt;br&gt;Tool results → host-friendly output" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8EB4E7;fontColor=#214A7A;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="292" y="446" width="240" height="74" as="geometry"/></mxCell>

        <mxCell id="gateway_subtitle" value="Cloud Run / API gateway front door • stateless, horizontally scalable routing" style="text;html=1;align=center;verticalAlign=middle;fontSize=12;fontColor=#176A39;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="596" y="154" width="398" height="28" as="geometry"/></mxCell>
        <mxCell id="gw_auth" value="&lt;b&gt;OAuth 2.1 / OIDC&lt;/b&gt;&lt;br&gt;Authentication &amp; token validation" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#69AD7C;fontColor=#155A31;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="600" y="195" width="185" height="72" as="geometry"/></mxCell>
        <mxCell id="gw_iam" value="&lt;b&gt;Cloud IAM / WIF&lt;/b&gt;&lt;br&gt;Workload identity &amp; service auth" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#69AD7C;fontColor=#155A31;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="805" y="195" width="185" height="72" as="geometry"/></mxCell>
        <mxCell id="gw_policy" value="&lt;b&gt;Policy &amp; Allowlist Engine&lt;/b&gt;&lt;br&gt;Tool / tenant / method authorization" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#69AD7C;fontColor=#155A31;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="600" y="284" width="185" height="72" as="geometry"/></mxCell>
        <mxCell id="gw_rate" value="&lt;b&gt;Rate Limiting / Quotas&lt;/b&gt;&lt;br&gt;Per client, tenant, tool &amp; method" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#69AD7C;fontColor=#155A31;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="805" y="284" width="185" height="72" as="geometry"/></mxCell>
        <mxCell id="gw_armor" value="&lt;b&gt;Model Armor / Inspection&lt;/b&gt;&lt;br&gt;Prompt, content &amp; tool-input checks" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#69AD7C;fontColor=#155A31;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="600" y="373" width="185" height="72" as="geometry"/></mxCell>
        <mxCell id="gw_routing" value="&lt;b&gt;Header Routing&lt;/b&gt;&lt;br&gt;Mcp-Method • Mcp-Name • session/version metadata" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#69AD7C;fontColor=#155A31;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="805" y="373" width="185" height="72" as="geometry"/></mxCell>
        <mxCell id="gw_audit" value="&lt;b&gt;Audit &amp; Request Logging&lt;/b&gt;&lt;br&gt;Principal • method • tool • result • latency" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#69AD7C;fontColor=#155A31;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="600" y="462" width="185" height="72" as="geometry"/></mxCell>
        <mxCell id="gw_session" value="&lt;b&gt;Session Context&lt;/b&gt;&lt;br&gt;Routing metadata only; no model state" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#69AD7C;fontColor=#155A31;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="805" y="462" width="185" height="72" as="geometry"/></mxCell>
        <mxCell id="gw_stateless" value="Stateless load-balanced routing • idempotent request handling • no sticky host dependency" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#ECF9F0;strokeColor=#70B989;fontColor=#176A39;fontSize=11;fontStyle=1;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="600" y="550" width="390" height="38" as="geometry"/></mxCell>

        <mxCell id="srv_db" value="&lt;b&gt;Database MCP Server&lt;/b&gt;&lt;br&gt;BigQuery • AlloyDB • Cloud SQL" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#A48FD2;fontColor=#5B3D99;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1058" y="175" width="288" height="76" as="geometry"/></mxCell>
        <mxCell id="srv_gcp" value="&lt;b&gt;Google Cloud MCP Server&lt;/b&gt;&lt;br&gt;GCS • BigQuery • Pub/Sub • Vertex AI APIs" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#A48FD2;fontColor=#5B3D99;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1058" y="276" width="288" height="76" as="geometry"/></mxCell>
        <mxCell id="srv_git" value="&lt;b&gt;GitHub / DevOps MCP Server&lt;/b&gt;&lt;br&gt;Repos • Issues • Pull Requests • CI/CD" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#A48FD2;fontColor=#5B3D99;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1058" y="377" width="288" height="76" as="geometry"/></mxCell>
        <mxCell id="srv_saas" value="&lt;b&gt;Enterprise SaaS MCP Server&lt;/b&gt;&lt;br&gt;Salesforce • ServiceNow • SAP" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#A48FD2;fontColor=#5B3D99;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1058" y="478" width="288" height="76" as="geometry"/></mxCell>
        <mxCell id="srv_note" value="Cloud Run autoscaling • independent deployment • least-privilege service identities" style="text;html=1;align=center;verticalAlign=middle;fontSize=11;fontColor=#7158AA;fontStyle=2;" vertex="1" parent="1"><mxGeometry x="1060" y="565" width="284" height="28" as="geometry"/></mxCell>

        <mxCell id="tool_bq" value="&lt;b&gt;BigQuery&lt;/b&gt;&lt;br&gt;Analytics &amp; governed data" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E8B15C;fontColor=#8A5600;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1415" y="165" width="310" height="62" as="geometry"/></mxCell>
        <mxCell id="tool_db" value="&lt;b&gt;AlloyDB / Cloud SQL&lt;/b&gt;&lt;br&gt;Transactional data" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E8B15C;fontColor=#8A5600;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1415" y="239" width="310" height="62" as="geometry"/></mxCell>
        <mxCell id="tool_gcs" value="&lt;b&gt;Cloud Storage&lt;/b&gt;&lt;br&gt;Documents, objects, artifacts" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E8B15C;fontColor=#8A5600;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1415" y="313" width="310" height="62" as="geometry"/></mxCell>
        <mxCell id="tool_git" value="&lt;b&gt;GitHub / DevOps&lt;/b&gt;&lt;br&gt;Repos, issues, PRs, actions" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E8B15C;fontColor=#8A5600;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1415" y="387" width="310" height="62" as="geometry"/></mxCell>
        <mxCell id="tool_saas" value="&lt;b&gt;Salesforce / ServiceNow / SAP&lt;/b&gt;&lt;br&gt;Enterprise systems of record" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E8B15C;fontColor=#8A5600;fontSize=13;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1415" y="461" width="310" height="62" as="geometry"/></mxCell>
        <mxCell id="tool_api" value="&lt;b&gt;Google Cloud APIs&lt;/b&gt;&lt;br&gt;Managed service operations" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#E8B15C;fontColor=#8A5600;fontSize=14;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1415" y="535" width="310" height="62" as="geometry"/></mxCell>

        <mxCell id="req1" value="1" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2.5;strokeColor=#2563EB;fontSize=12;fontStyle=1;labelBackgroundColor=#FFFFFF;endArrow=block;endFill=1;exitX=1;exitY=0.5;entryX=0;entryY=0.5;" edge="1" parent="1" source="host_vertex" target="client_request"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="req2" value="2  Streamable HTTP request" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2.5;strokeColor=#2563EB;fontSize=11;fontStyle=1;labelBackgroundColor=#FFFFFF;endArrow=block;endFill=1;exitX=1;exitY=0.5;entryX=0;entryY=0.5;" edge="1" parent="1" source="client_request" target="gw_policy"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="req3" value="3  authorized invoke" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2.5;strokeColor=#2563EB;fontSize=11;fontStyle=1;labelBackgroundColor=#FFFFFF;endArrow=block;endFill=1;exitX=1;exitY=0.5;entryX=0;entryY=0.5;" edge="1" parent="1" source="gw_routing" target="srv_db"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="req4" value="4  tool/API call" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;strokeWidth=2.5;strokeColor=#2563EB;fontSize=11;fontStyle=1;labelBackgroundColor=#FFFFFF;endArrow=block;endFill=1;exitX=1;exitY=0.5;entryX=0;entryY=0.5;" edge="1" parent="1" source="srv_db" target="tool_bq"><mxGeometry relative="1" as="geometry"/></mxCell>

        <mxCell id="resp5" value="5  tool result / MCP response" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;dashed=1;strokeWidth=2.2;strokeColor=#2563EB;fontSize=11;fontStyle=1;labelBackgroundColor=#FFFFFF;endArrow=block;endFill=1;exitX=0;exitY=0.72;entryX=1;entryY=0.72;" edge="1" parent="1" source="srv_saas" target="client_response"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="1024" y="575"/><mxPoint x="564" y="575"/></Array></mxGeometry></mxCell>
        <mxCell id="resp6" value="6  normalized result" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;dashed=1;strokeWidth=2.2;strokeColor=#2563EB;fontSize=11;fontStyle=1;labelBackgroundColor=#FFFFFF;endArrow=block;endFill=1;exitX=0;exitY=0.5;entryX=1;entryY=0.5;" edge="1" parent="1" source="client_response" target="host_gemini"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="260" y="484"/><mxPoint x="260" y="207"/></Array></mxGeometry></mxCell>

        <mxCell id="ctrl_line" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;dashed=1;dashPattern=2 4;strokeWidth=2;strokeColor=#16A34A;endArrow=none;" edge="1" parent="1"><mxGeometry relative="1" as="geometry"><mxPoint x="90" y="635" as="sourcePoint"/><mxPoint x="1690" y="635" as="targetPoint"/></mxGeometry></mxCell>

        <mxCell id="cross_hdr" value="CROSS-CUTTING CAPABILITIES" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B3B75;strokeColor=#0B3B75;fontColor=#FFFFFF;fontSize=14;fontStyle=1;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="20" y="655" width="180" height="104" as="geometry"/></mxCell>
        <mxCell id="cross_sec" value="&lt;b&gt;Security &amp; Identity&lt;/b&gt;&lt;br&gt;Secret Manager • Cloud KMS • IAM • VPC-SC" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#AFC6E0;fontColor=#274C77;fontSize=12;align=left;spacingLeft=10;" vertex="1" parent="1"><mxGeometry x="215" y="667" width="300" height="80" as="geometry"/></mxCell>
        <mxCell id="cross_obs" value="&lt;b&gt;Observability&lt;/b&gt;&lt;br&gt;Cloud Logging • Cloud Monitoring • Error Reporting • Trace" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#AFC6E0;fontColor=#274C77;fontSize=12;align=left;spacingLeft=10;" vertex="1" parent="1"><mxGeometry x="530" y="667" width="300" height="80" as="geometry"/></mxCell>
        <mxCell id="cross_gov" value="&lt;b&gt;Governance &amp; Audit&lt;/b&gt;&lt;br&gt;Cloud Audit Logs • approvals • DLP / retention • policy evidence" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#8FC39F;fontColor=#176A39;fontSize=12;align=left;spacingLeft=10;" vertex="1" parent="1"><mxGeometry x="845" y="667" width="300" height="80" as="geometry"/></mxCell>
        <mxCell id="cross_rel" value="&lt;b&gt;Reliability&lt;/b&gt;&lt;br&gt;Cloud Run autoscaling • retries • multi-region option • idempotency" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#B3A5D8;fontColor=#5B3D99;fontSize=12;align=left;spacingLeft=10;" vertex="1" parent="1"><mxGeometry x="1160" y="667" width="300" height="80" as="geometry"/></mxCell>
        <mxCell id="legend" value="&lt;b&gt;LEGEND&lt;/b&gt;&lt;br&gt;━━ Request / invoke&lt;br&gt;┄┄ Response / result&lt;br&gt;···· Control / audit / policy" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#AFC6E0;fontColor=#334155;fontSize=11;align=left;spacingLeft=10;" vertex="1" parent="1"><mxGeometry x="1475" y="667" width="255" height="80" as="geometry"/></mxCell>

        <mxCell id="flow_hdr" value="REQUEST FLOW&lt;br&gt;(END-TO-END)" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B3B75;strokeColor=#0B3B75;fontColor=#FFFFFF;fontSize=14;fontStyle=1;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="20" y="775" width="180" height="110" as="geometry"/></mxCell>
        <mxCell id="flow1" value="&lt;b&gt;1&lt;/b&gt;&lt;br&gt;Host selects tool and discovers capabilities" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#BCD0E5;fontColor=#334155;fontSize=11;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="215" y="790" width="235" height="80" as="geometry"/></mxCell>
        <mxCell id="flow2" value="&lt;b&gt;2&lt;/b&gt;&lt;br&gt;MCP client builds a Streamable HTTP request" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#BCD0E5;fontColor=#334155;fontSize=11;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="462" y="790" width="235" height="80" as="geometry"/></mxCell>
        <mxCell id="flow3" value="&lt;b&gt;3&lt;/b&gt;&lt;br&gt;Gateway authenticates, authorizes, inspects and routes" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F4FBF6;strokeColor=#8FC39F;fontColor=#176A39;fontSize=11;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="709" y="790" width="235" height="80" as="geometry"/></mxCell>
        <mxCell id="flow4" value="&lt;b&gt;4&lt;/b&gt;&lt;br&gt;Remote MCP server invokes the target enterprise system" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FAF8FF;strokeColor=#B3A5D8;fontColor=#5B3D99;fontSize=11;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="956" y="790" width="235" height="80" as="geometry"/></mxCell>
        <mxCell id="flow5" value="&lt;b&gt;5&lt;/b&gt;&lt;br&gt;Tool result returns as an MCP response and is normalized" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#BCD0E5;fontColor=#334155;fontSize=11;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1203" y="790" width="235" height="80" as="geometry"/></mxCell>
        <mxCell id="flow6" value="&lt;b&gt;6&lt;/b&gt;&lt;br&gt;Host agent reasons over the result and responds or acts" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#BCD0E5;fontColor=#334155;fontSize=11;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1450" y="790" width="280" height="80" as="geometry"/></mxCell>

        <mxCell id="benefits" value="&lt;b&gt;KEY BENEFITS&lt;/b&gt;   ✓ Secure centralized tool access   ✓ Stateless scalable remote MCP   ✓ Auditable policy-governed execution   ✓ Clean separation of hosts, gateway, servers and tools" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F7FCF8;strokeColor=#8FC39F;fontColor=#176A39;fontSize=12;fontStyle=1;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="215" y="892" width="1515" height="44" as="geometry"/></mxCell>
        <mxCell id="foundation" value="&lt;b&gt;BUILT ON GOOGLE CLOUD:&lt;/b&gt;   Cloud Run  •  API Gateway / HTTPS LB  •  IAM  •  Workload Identity Federation  •  Secret Manager  •  Cloud KMS  •  Model Armor  •  Cloud Logging  •  Cloud Monitoring  •  BigQuery  •  AlloyDB  •  Cloud SQL  •  Cloud Storage" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B3B75;strokeColor=#0B3B75;fontColor=#FFFFFF;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="20" y="950" width="1730" height="36" as="geometry"/></mxCell>

      </root>
    </mxGraphModel>
  </diagram>
</mxfile>`;
}
