/**
 * MASTER BLUEPRINT 31: GO-LIVE CUTOVER & WAR ROOM RUNBOOK
 * Native editable mxGraph/Draw.io implementation aligned to the approved reference design.
 */

export function buildGoLiveWarRoomRunbookXml(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="app.diagrams.net" modified="2026-08-19T00:00:00.000Z" agent="PromptCanvas" version="24.0.0" type="device">
  <diagram id="golive_warroom_runbook" name="Go-Live Cutover &amp; War Room Runbook">
    <mxGraphModel dx="1600" dy="900" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1600" pageHeight="900" background="#FFFFFF">
      <root>
        <mxCell id="0"/>
        <mxCell id="1" parent="0"/>

        <!-- HEADER -->
        <mxCell id="bp_badge" value="&lt;b style=&quot;font-size:24px;color:#FFFFFF;&quot;&gt;31&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:9px;color:#DBEAFE;&quot;&gt;of 50&lt;/span&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B4EA2;strokeColor=#0B4EA2;align=center;verticalAlign=middle;arcSize=8;" vertex="1" parent="1">
          <mxGeometry x="16" y="16" width="74" height="68" as="geometry"/>
        </mxCell>
        <mxCell id="gcp_logo" value="GCP" style="ellipse;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#4285F4;strokeWidth=2;fontColor=#1A73E8;fontStyle=1;fontSize=12;align=center;verticalAlign=middle;" vertex="1" parent="1">
          <mxGeometry x="104" y="25" width="44" height="44" as="geometry"/>
        </mxCell>
        <mxCell id="title" value="&lt;b style=&quot;font-size:25px;color:#0F2747;&quot;&gt;Go-Live Cutover &amp;amp; War Room Runbook&lt;/b&gt;&lt;br&gt;&lt;span style=&quot;font-size:11px;color:#475569;&quot;&gt;Operational cutover blueprint for production release, controlled DNS/LB switch, verification, hypercare, and rollback governance on Google Cloud.&lt;/span&gt;" style="text;html=1;align=left;verticalAlign=middle;whiteSpace=wrap;fillColor=none;strokeColor=none;" vertex="1" parent="1">
          <mxGeometry x="166" y="14" width="650" height="68" as="geometry"/>
        </mxCell>

        <mxCell id="pill1" value="Controlled&lt;br&gt;Cutover" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FBFF;strokeColor=#93C5FD;fontColor=#0B4EA2;fontStyle=1;fontSize=10;align=center;verticalAlign=middle;arcSize=8;" vertex="1" parent="1"><mxGeometry x="840" y="22" width="115" height="46" as="geometry"/></mxCell>
        <mxCell id="pill2" value="War Room&lt;br&gt;Governance" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F0FDF4;strokeColor=#86EFAC;fontColor=#15803D;fontStyle=1;fontSize=10;align=center;verticalAlign=middle;arcSize=8;" vertex="1" parent="1"><mxGeometry x="965" y="22" width="115" height="46" as="geometry"/></mxCell>
        <mxCell id="pill3" value="Rollback&lt;br&gt;Ready" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FAF5FF;strokeColor=#C4B5FD;fontColor=#6D28D9;fontStyle=1;fontSize=10;align=center;verticalAlign=middle;arcSize=8;" vertex="1" parent="1"><mxGeometry x="1090" y="22" width="115" height="46" as="geometry"/></mxCell>
        <mxCell id="pill4" value="Live&lt;br&gt;Telemetry" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF7ED;strokeColor=#FDBA74;fontColor=#EA580C;fontStyle=1;fontSize=10;align=center;verticalAlign=middle;arcSize=8;" vertex="1" parent="1"><mxGeometry x="1215" y="22" width="115" height="46" as="geometry"/></mxCell>
        <mxCell id="pill5" value="Business&lt;br&gt;Validation" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FBFF;strokeColor=#93C5FD;fontColor=#0B4EA2;fontStyle=1;fontSize=10;align=center;verticalAlign=middle;arcSize=8;" vertex="1" parent="1"><mxGeometry x="1340" y="22" width="115" height="46" as="geometry"/></mxCell>

        <!-- STAGE CONTAINERS -->
        <mxCell id="s1" value="" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FBFF;strokeColor=#2563EB;strokeWidth=1.5;arcSize=4;" vertex="1" parent="1"><mxGeometry x="16" y="104" width="190" height="380" as="geometry"/></mxCell>
        <mxCell id="s2" value="" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F7FFF9;strokeColor=#16A34A;strokeWidth=1.5;arcSize=4;" vertex="1" parent="1"><mxGeometry x="220" y="104" width="190" height="380" as="geometry"/></mxCell>
        <mxCell id="s3" value="" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FCFAFF;strokeColor=#7C3AED;strokeWidth=1.5;arcSize=4;" vertex="1" parent="1"><mxGeometry x="424" y="104" width="220" height="380" as="geometry"/></mxCell>
        <mxCell id="s4" value="" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FBFF;strokeColor=#2563EB;strokeWidth=1.5;arcSize=4;" vertex="1" parent="1"><mxGeometry x="658" y="104" width="190" height="380" as="geometry"/></mxCell>
        <mxCell id="s5" value="" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F7FFF9;strokeColor=#16A34A;strokeWidth=1.5;arcSize=4;" vertex="1" parent="1"><mxGeometry x="862" y="104" width="190" height="380" as="geometry"/></mxCell>
        <mxCell id="s6" value="" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FCFAFF;strokeColor=#7C3AED;strokeWidth=1.5;arcSize=4;" vertex="1" parent="1"><mxGeometry x="1066" y="104" width="190" height="380" as="geometry"/></mxCell>

        <!-- STAGE HEADERS -->
        <mxCell id="h1" value="&lt;b&gt;1&amp;nbsp;&amp;nbsp; T-24h&lt;br&gt;Pre-Flight Validation&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#2563EB;strokeColor=#2563EB;fontColor=#FFFFFF;fontSize=12;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="16" y="104" width="190" height="54" as="geometry"/></mxCell>
        <mxCell id="h2" value="&lt;b&gt;2&amp;nbsp;&amp;nbsp; T-4h&lt;br&gt;Final Readiness&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#16A34A;strokeColor=#16A34A;fontColor=#FFFFFF;fontSize=12;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="220" y="104" width="190" height="54" as="geometry"/></mxCell>
        <mxCell id="h3" value="&lt;b&gt;3&amp;nbsp;&amp;nbsp; T-0&lt;br&gt;Go / No-Go Gate&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#7C3AED;strokeColor=#7C3AED;fontColor=#FFFFFF;fontSize=12;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="424" y="104" width="220" height="54" as="geometry"/></mxCell>
        <mxCell id="h4" value="&lt;b&gt;4&amp;nbsp;&amp;nbsp; Production&lt;br&gt;Cutover&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#2563EB;strokeColor=#2563EB;fontColor=#FFFFFF;fontSize=12;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="658" y="104" width="190" height="54" as="geometry"/></mxCell>
        <mxCell id="h5" value="&lt;b&gt;5&amp;nbsp;&amp;nbsp; Immediate Verification&lt;br&gt;(T+0 to T+1h)&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#16A34A;strokeColor=#16A34A;fontColor=#FFFFFF;fontSize=12;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="862" y="104" width="190" height="54" as="geometry"/></mxCell>
        <mxCell id="h6" value="&lt;b&gt;6&amp;nbsp;&amp;nbsp; Hypercare &amp;amp;&lt;br&gt;T+48h Stabilization&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#7C3AED;strokeColor=#7C3AED;fontColor=#FFFFFF;fontSize=12;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="1066" y="104" width="190" height="54" as="geometry"/></mxCell>

        <!-- SIMPLE STAGE ICONS -->
        <mxCell id="i1" value="CHECK" style="ellipse;whiteSpace=wrap;html=1;fillColor=#EFF6FF;strokeColor=#2563EB;fontColor=#2563EB;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="82" y="172" width="58" height="58" as="geometry"/></mxCell>
        <mxCell id="i2" value="READY" style="ellipse;whiteSpace=wrap;html=1;fillColor=#F0FDF4;strokeColor=#16A34A;fontColor=#15803D;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="286" y="172" width="58" height="58" as="geometry"/></mxCell>
        <mxCell id="i3" value="GATE" style="rhombus;whiteSpace=wrap;html=1;fillColor=#FAF5FF;strokeColor=#7C3AED;fontColor=#6D28D9;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="505" y="170" width="58" height="58" as="geometry"/></mxCell>
        <mxCell id="i4" value="CUTOVER" style="ellipse;whiteSpace=wrap;html=1;fillColor=#EFF6FF;strokeColor=#2563EB;fontColor=#2563EB;fontStyle=1;fontSize=8;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="724" y="172" width="58" height="58" as="geometry"/></mxCell>
        <mxCell id="i5" value="VERIFY" style="ellipse;whiteSpace=wrap;html=1;fillColor=#F0FDF4;strokeColor=#16A34A;fontColor=#15803D;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="928" y="172" width="58" height="58" as="geometry"/></mxCell>
        <mxCell id="i6" value="CARE" style="ellipse;whiteSpace=wrap;html=1;fillColor=#FAF5FF;strokeColor=#7C3AED;fontColor=#6D28D9;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;" vertex="1" parent="1"><mxGeometry x="1132" y="172" width="58" height="58" as="geometry"/></mxCell>

        <!-- STAGE DETAILS -->
        <mxCell id="d1" value="• Release readiness checklist&lt;br&gt;• Change freeze confirmed&lt;br&gt;• Stakeholder notifications sent&lt;br&gt;• Runbook review completed&lt;br&gt;• Final backups / snapshots taken&lt;br&gt;• Replication health check&lt;br&gt;• Secrets / config validation&lt;br&gt;• Rollback artifact validation" style="text;html=1;whiteSpace=wrap;align=left;verticalAlign=top;fontColor=#1E3A5F;fontSize=10;spacingLeft=8;spacingTop=4;" vertex="1" parent="1"><mxGeometry x="28" y="242" width="166" height="172" as="geometry"/></mxCell>
        <mxCell id="d2" value="• War room activation&lt;br&gt;• Command center roles confirmed&lt;br&gt;• Traffic forecast validated&lt;br&gt;• Final database sync&lt;br&gt;• Health baselines captured&lt;br&gt;• Smoke-test scripts prepared&lt;br&gt;• Cutover communications ready" style="text;html=1;whiteSpace=wrap;align=left;verticalAlign=top;fontColor=#14532D;fontSize=10;spacingLeft=8;spacingTop=4;" vertex="1" parent="1"><mxGeometry x="232" y="242" width="166" height="160" as="geometry"/></mxCell>
        <mxCell id="d3" value="&lt;b&gt;Decision Gate Reviewers&lt;/b&gt;&lt;br&gt;• Cutover Commander&lt;br&gt;• SRE Lead&lt;br&gt;• App Lead&lt;br&gt;• DB Lead&lt;br&gt;• Security Lead&lt;br&gt;• Business Owner" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#C4B5FD;fontColor=#4C1D95;fontSize=10;align=left;verticalAlign=top;spacing=7;arcSize=5;" vertex="1" parent="1"><mxGeometry x="442" y="238" width="184" height="130" as="geometry"/></mxCell>
        <mxCell id="go" value="&lt;b&gt;GO&lt;br&gt;FORWARD&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F0FDF4;strokeColor=#22C55E;fontColor=#15803D;fontStyle=1;fontSize=11;align=center;verticalAlign=middle;arcSize=8;" vertex="1" parent="1"><mxGeometry x="442" y="382" width="82" height="62" as="geometry"/></mxCell>
        <mxCell id="hold" value="&lt;b&gt;HOLD /&lt;br&gt;ROLLBACK&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FEF2F2;strokeColor=#EF4444;fontColor=#DC2626;fontStyle=1;fontSize=10;align=center;verticalAlign=middle;arcSize=8;" vertex="1" parent="1"><mxGeometry x="544" y="382" width="82" height="62" as="geometry"/></mxCell>
        <mxCell id="d4" value="• Cloud DNS switch&lt;br&gt;• Global HTTPS Load Balancer / traffic routing update&lt;br&gt;• Application release activation&lt;br&gt;• Database writer switch / replication promotion&lt;br&gt;• Feature flag enablement&lt;br&gt;• Queue drain / job resume" style="text;html=1;whiteSpace=wrap;align=left;verticalAlign=top;fontColor=#1E3A5F;fontSize=10;spacingLeft=8;spacingTop=4;" vertex="1" parent="1"><mxGeometry x="670" y="242" width="166" height="170" as="geometry"/></mxCell>
        <mxCell id="d5" value="• Synthetic tests execution&lt;br&gt;• Critical user journey checks&lt;br&gt;• API health validation&lt;br&gt;• Database validation&lt;br&gt;• Business KPI spot checks&lt;br&gt;• Incident triage bridge active&lt;br&gt;• Rollback trigger thresholds monitored" style="text;html=1;whiteSpace=wrap;align=left;verticalAlign=top;fontColor=#14532D;fontSize=10;spacingLeft=8;spacingTop=4;" vertex="1" parent="1"><mxGeometry x="874" y="242" width="166" height="174" as="geometry"/></mxCell>
        <mxCell id="d6" value="• Cloud Monitoring dashboards&lt;br&gt;• Cloud Logging analysis&lt;br&gt;• SLO / error budget watch&lt;br&gt;• PagerDuty / on-call engaged&lt;br&gt;• Stakeholder status updates&lt;br&gt;• Post-cutover review&lt;br&gt;• Incident ledger updated&lt;br&gt;• Cutover sign-off obtained" style="text;html=1;whiteSpace=wrap;align=left;verticalAlign=top;fontColor=#4C1D95;fontSize=10;spacingLeft=8;spacingTop=4;" vertex="1" parent="1"><mxGeometry x="1078" y="242" width="166" height="174" as="geometry"/></mxCell>

        <!-- DELIVERABLES -->
        <mxCell id="del1" value="Deliverable: Pre-Flight Sign-off" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#2563EB;strokeColor=#2563EB;fontColor=#FFFFFF;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;arcSize=6;" vertex="1" parent="1"><mxGeometry x="27" y="444" width="168" height="28" as="geometry"/></mxCell>
        <mxCell id="del2" value="Deliverable: Readiness Confirmed" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#16A34A;strokeColor=#16A34A;fontColor=#FFFFFF;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;arcSize=6;" vertex="1" parent="1"><mxGeometry x="231" y="444" width="168" height="28" as="geometry"/></mxCell>
        <mxCell id="del4" value="Deliverable: Cutover Complete" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#2563EB;strokeColor=#2563EB;fontColor=#FFFFFF;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;arcSize=6;" vertex="1" parent="1"><mxGeometry x="669" y="444" width="168" height="28" as="geometry"/></mxCell>
        <mxCell id="del5" value="Deliverable: Verification Passed" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#16A34A;strokeColor=#16A34A;fontColor=#FFFFFF;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;arcSize=6;" vertex="1" parent="1"><mxGeometry x="873" y="444" width="168" height="28" as="geometry"/></mxCell>
        <mxCell id="del6" value="Deliverable: Stabilization Sign-off" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#7C3AED;strokeColor=#7C3AED;fontColor=#FFFFFF;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;arcSize=6;" vertex="1" parent="1"><mxGeometry x="1077" y="444" width="168" height="28" as="geometry"/></mxCell>

        <!-- STAGE FLOW ARROWS -->
        <mxCell id="e12" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;strokeColor=#334155;strokeWidth=2;endArrow=block;endFill=1;" edge="1" parent="1" source="s1" target="s2"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e23" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;strokeColor=#334155;strokeWidth=2;endArrow=block;endFill=1;" edge="1" parent="1" source="s2" target="s3"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e34" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;strokeColor=#334155;strokeWidth=2;endArrow=block;endFill=1;" edge="1" parent="1" source="s3" target="s4"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e45" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;strokeColor=#334155;strokeWidth=2;endArrow=block;endFill=1;" edge="1" parent="1" source="s4" target="s5"><mxGeometry relative="1" as="geometry"/></mxCell>
        <mxCell id="e56" value="" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;strokeColor=#334155;strokeWidth=2;endArrow=block;endFill=1;" edge="1" parent="1" source="s5" target="s6"><mxGeometry relative="1" as="geometry"/></mxCell>

        <!-- RIGHT COMMAND STRUCTURE -->
        <mxCell id="cmd" value="" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#2563EB;strokeWidth=1.5;arcSize=5;" vertex="1" parent="1"><mxGeometry x="1272" y="104" width="312" height="230" as="geometry"/></mxCell>
        <mxCell id="cmdh" value="&lt;b&gt;War Room Command Structure&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B4EA2;strokeColor=#0B4EA2;fontColor=#FFFFFF;fontSize=12;align=center;verticalAlign=middle;arcSize=5;" vertex="1" parent="1"><mxGeometry x="1272" y="104" width="312" height="30" as="geometry"/></mxCell>
        <mxCell id="cmdtxt" value="&lt;b&gt;Cutover Commander&lt;/b&gt; — overall decision authority and risk acceptance&lt;br&gt;&lt;b&gt;App Lead&lt;/b&gt; — application release and feature management&lt;br&gt;&lt;b&gt;SRE Lead&lt;/b&gt; — platform reliability and observability&lt;br&gt;&lt;b&gt;Database Lead&lt;/b&gt; — data integrity, promotion and validation&lt;br&gt;&lt;b&gt;Network / DNS Lead&lt;/b&gt; — DNS, LB, routing and connectivity&lt;br&gt;&lt;b&gt;Security / Compliance&lt;/b&gt; — posture, access and guardrails&lt;br&gt;&lt;b&gt;Business Owner&lt;/b&gt; — business impact and acceptance&lt;br&gt;&lt;b&gt;Communications Lead&lt;/b&gt; — stakeholder updates" style="text;html=1;whiteSpace=wrap;align=left;verticalAlign=top;fontColor=#1E3A5F;fontSize=9;spacing=9;" vertex="1" parent="1"><mxGeometry x="1282" y="142" width="292" height="182" as="geometry"/></mxCell>

        <!-- ROLLBACK CRITERIA -->
        <mxCell id="rollback" value="&lt;b style=&quot;font-size:12px;color:#B91C1C;&quot;&gt;Rollback Criteria&lt;/b&gt;&lt;br&gt;• Sustained error rate above approved threshold (example: 1% for 5 min)&lt;br&gt;• Failed smoke tests or critical user journeys&lt;br&gt;• DNS / LB instability or elevated 5xx responses&lt;br&gt;• Data inconsistency or replication lag beyond SLA&lt;br&gt;• Critical business workflow failure / KPI breach" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF7F7;strokeColor=#EF4444;strokeWidth=1.5;fontColor=#7F1D1D;fontSize=9;align=left;verticalAlign=top;spacing=10;arcSize=5;" vertex="1" parent="1"><mxGeometry x="1272" y="346" width="312" height="138" as="geometry"/></mxCell>

        <!-- TELEMETRY BAND -->
        <mxCell id="telemetry" value="&lt;b&gt;End-to-End Telemetry &amp;amp; Audit&lt;/b&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp; | &amp;nbsp; Cloud Audit Logs &amp;nbsp; | &amp;nbsp; Cloud Monitoring Alerts &amp;nbsp; | &amp;nbsp; Cloud Logging &amp;amp; Trace &amp;nbsp; | &amp;nbsp; War Room Metrics Overlay" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FBFF;strokeColor=#2563EB;dashed=1;fontColor=#1E3A5F;fontSize=10;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="16" y="500" width="1240" height="34" as="geometry"/></mxCell>

        <!-- END-TO-END SUMMARY -->
        <mxCell id="seqh" value="&lt;b&gt;End-to-End&lt;br&gt;Sequence Summary&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B4EA2;strokeColor=#0B4EA2;fontColor=#FFFFFF;fontSize=10;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="16" y="550" width="115" height="64" as="geometry"/></mxCell>
        <mxCell id="seq" value="1  T-24h Pre-Flight Validation   →   2  T-4h Final Readiness   →   3  T-0 Go / No-Go Gate   →   4  Production Cutover   →   5  T+0 to T+1h Immediate Verification   →   6  T+48h Hypercare &amp;amp; Stabilization   →   Cutover Success" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#93C5FD;fontColor=#1E3A5F;fontStyle=1;fontSize=10;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="131" y="550" width="1250" height="64" as="geometry"/></mxCell>

        <!-- GOOGLE CLOUD SERVICES -->
        <mxCell id="svch" value="&lt;b&gt;Google Cloud Services Used&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B4EA2;strokeColor=#0B4EA2;fontColor=#FFFFFF;fontSize=10;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="16" y="630" width="190" height="26" as="geometry"/></mxCell>
        <mxCell id="svc" value="Cloud DNS   •   Global HTTPS Load Balancing   •   Cloud Monitoring   •   Cloud Logging   •   Cloud Audit Logs   •   Cloud SQL / Spanner Replication   •   Cloud Storage Backups   •   Cloud Workflows / Functions   •   Pub/Sub Notifications   •   Looker Executive Dashboard" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#93C5FD;fontColor=#1E3A5F;fontSize=9;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="16" y="656" width="790" height="64" as="geometry"/></mxCell>

        <!-- SUCCESS METRICS -->
        <mxCell id="metricsh" value="&lt;b&gt;Success Metrics&lt;/b&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#0B4EA2;strokeColor=#0B4EA2;fontColor=#FFFFFF;fontSize=10;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="820" y="630" width="150" height="26" as="geometry"/></mxCell>
        <mxCell id="metrics" value="RTO target ≤ 60 min   |   RPO target ≤ 5 min   |   Smoke-test pass rate ≥ 98%   |   Error-rate target ≤ 1%   |   Latency delta vs baseline ≤ 10%   |   Critical KPI status: on track" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#93C5FD;fontColor=#1E3A5F;fontStyle=1;fontSize=9;align=center;verticalAlign=middle;arcSize=4;" vertex="1" parent="1"><mxGeometry x="820" y="656" width="764" height="64" as="geometry"/></mxCell>

        <!-- BOTTOM FOUR PANELS -->
        <mxCell id="cap" value="&lt;b style=&quot;color:#0B4EA2;&quot;&gt;Cross-Cutting Capabilities&lt;/b&gt;&lt;br&gt;• Infrastructure as Code (IaC)&lt;br&gt;• Policy as Code / Org Policies&lt;br&gt;• Security Command Center&lt;br&gt;• VPC Service Controls&lt;br&gt;• IAM least privilege&lt;br&gt;• Backup &amp;amp; DR automation" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#CBD5E1;fontColor=#334155;fontSize=9;align=left;verticalAlign=top;spacing=9;arcSize=4;" vertex="1" parent="1"><mxGeometry x="16" y="736" width="360" height="138" as="geometry"/></mxCell>
        <mxCell id="roles" value="&lt;b style=&quot;color:#0B4EA2;&quot;&gt;Role Assignments (Examples)&lt;/b&gt;&lt;br&gt;Cutover Commander — final decision authority&lt;br&gt;SRE On-Call — monitoring, alerts, incident response&lt;br&gt;DB On-Call — replication, failover, validation&lt;br&gt;Network On-Call — DNS/LB/routing execution&lt;br&gt;Security On-Call — security posture &amp;amp; compliance&lt;br&gt;Business Owner — business impact &amp;amp; acceptance" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#CBD5E1;fontColor=#334155;fontSize=9;align=left;verticalAlign=top;spacing=9;arcSize=4;" vertex="1" parent="1"><mxGeometry x="390" y="736" width="390" height="138" as="geometry"/></mxCell>
        <mxCell id="criteria" value="&lt;b style=&quot;color:#15803D;&quot;&gt;Success Criteria&lt;/b&gt;&lt;br&gt;✓ Business KPIs within expected range&lt;br&gt;✓ All smoke tests and validations passed&lt;br&gt;✓ SLO met; error budget healthy&lt;br&gt;✓ No Sev-1 or Sev-2 incidents open&lt;br&gt;✓ Stakeholder sign-off captured" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#CBD5E1;fontColor=#334155;fontSize=9;align=left;verticalAlign=top;spacing=9;arcSize=4;" vertex="1" parent="1"><mxGeometry x="794" y="736" width="382" height="138" as="geometry"/></mxCell>
        <mxCell id="benefits" value="&lt;b style=&quot;color:#0B4EA2;&quot;&gt;Key Benefits&lt;/b&gt;&lt;br&gt;• Minimized risk with repeatable, governed cutover&lt;br&gt;• Faster detection &amp;amp; recovery with real-time telemetry&lt;br&gt;• Transparent communication &amp;amp; role clarity&lt;br&gt;• Rollback-ready posture improves resilience&lt;br&gt;• Higher confidence, reduced downtime &amp;amp; stakeholder trust" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#CBD5E1;fontColor=#334155;fontSize=9;align=left;verticalAlign=top;spacing=9;arcSize=4;" vertex="1" parent="1"><mxGeometry x="1190" y="736" width="394" height="138" as="geometry"/></mxCell>

      </root>
    </mxGraphModel>
  </diagram>
</mxfile>`;
}
